### ISSUE TITLE
tvorba postavy

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#1]
vlasy-styl-"žádný nesmysl"...............?
oči-barva-"lískové"=nesmysl, používá se název oříškové (myšleno hnědá). takže ostatní "lískové" jako šedozelená jsou uplný nesmysl.

**Comment by MartinTerran** [comment]
![fallout 4 -tvoreni postavy](https://user-images.githubusercontent.com/35099061/34559864-ee5181c0-f143-11e7-8749-24c4435b9fb7.png)
Ještě jedna chybka u tvoření postavy

**Comment by pavelhoral** [comment]
Opraveno na *oříškově hnědé*, *oříškově zelené* a *oříškově zarudlé*.,
