### ISSUE TITLE
Chybí část textu v kategorii úprav postavy

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#11]
![fallout 4 10 13 2016 - 18 23 17 04](https://cloud.githubusercontent.com/assets/22203490/19376996/e6df0a28-91e2-11e6-9f67-e25e0ad60cec.png)

Chybějící část textu v názvu kategorie + nepřeloženo pomalování "Bleck"

**Comment by pavelhoral** [comment]
Místo *obličejové barvy* jsem dal *malování*.
