### ISSUE TITLE
V popisu modifikace 2x zmíněn zpětný ráz

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#117]
![screenshot4](https://cloud.githubusercontent.com/assets/22203490/20524937/47ec8270-b0bd-11e6-9bdd-8790681d4633.png)

**Comment by pavelhoral** [comment]
Koukám, že tohle nemáme jednotně:
![image](https://user-images.githubusercontent.com/2012726/38486543-a8d725c0-3bdd-11e8-9ee8-d176bb123a33.png)

**Comment by pavelhoral** [comment]
Jak výrazy chápu:
* *Per-shot recoil* je jak moc zbraň skáče s každým výstřelem.
* *Recoil control* je jak moc "agresivní" daný odskok je. 

Všechny překlady jsem srovnal následovně:
* *improved per-shot recoil* → *menší zpětný ráz jednotlivých ran*
* *improved recoil control* → *lepší ovladatelnost zpětného rázu*
