### ISSUE TITLE
Dynamický název Gama zbraně

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#118]
![screenshot5](https://cloud.githubusercontent.com/assets/22203490/20524988/90902216-b0bd-11e6-99ea-627af76cbb83.png)

Modifikace hluboký talíř (din. název - Dlouhá hlaveň)

**Comment by pavelhoral** [comment]
Zavírám jako _neřešitelné_. V originále je přídavné jméno *Long*, které je mapované na všechny zbraně s dlouhou hlavní a pažbou pro pistole (modifikace typu `dn_HasBarrel_Long + dn_HasGrip_Pistol`). To, že má hluboký talíř stejný typ, bohužel neovlivníme. Jako jediné řešení by bylo překlad úplně odstranit (tzn. pro dlouhou hlaveň by se negeneroval žádný přívlastek), nebo vymyslet paskvil typu _velká hlaveň_ atp.

Pokud někdy budeme předělávat systém přívlastků, tak se k tomuhle určitě vrátíme.
