### ISSUE TITLE
Network Scanner není jednotně přeložen

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#121]
Všiml jsem si, že *Network Scanner*, což je poměrně významný předmět, nemá záznam ve slovníčku a není jednotně přeložen. Bude potřeba překlad doplnit a opravit.

Někde to máme jako skener a jinde jako snímač... ani jedno není moc vhodné. Pozor, aby se chybně nezměnil překlad Biometric Scanner (což naopak snímač je).

**Comment by StoupaJ** [comment]
existuje jen 10 záznamů s pojmem Network Scanner - vše je již přeloženo - takže bych to mohl přihodit do následujících korekcí. Kromě jednoho to je všechno v názvu holopásky. Mám ji tedy přejmenovat na: „**Holopáska se síťovým skenerem**“?

![image](https://cloud.githubusercontent.com/assets/17909494/21855572/3bae2c14-d81f-11e6-83b2-a7d01d789901.png)

**Comment by pavelhoral** [comment]
Mě se líbí *Holopáska pro skenování sítě*... pokud dáš do googlu "síťový skener", tak ti vylezou skenery, které můžeš zapojit do sítě.

**Comment by StoupaJ** [comment]
opraveno v rámci 02ed4f0 (Holopáska pro skenování sítě/Síťový skener)
