### ISSUE TITLE
Chyba v holopásce (Griswold)

### ISSUE THREAD

**Issue by StoupaJ** [prekladyher/fallout4-cestina#124]
možná to jsou přímo bugy Bethesdy, takže pro info:
 - „O Životě“ --> uvnitř není žádný text (nenalezen ale ani v datech hry)
 - nabídka „ZPĚT“ není funkční
![20161130120706_1](https://cloud.githubusercontent.com/assets/17909494/21153435/bd7581be-c16a-11e6-9ca3-2c0152d58797.jpg)

**Comment by pavelhoral** [comment]
Ano, prázdné to je i v originále. http://fallout.wikia.com/wiki/Griswold%27s_poetry_collection
