### ISSUE TITLE
modifikace - zásobník vs. buben

### ISSUE THREAD

**Issue by StoupaJ** [prekladyher/fallout4-cestina#127]
Jeden kotouč je jako „zásobník“, další tři typově stejné jako „buben“.
![buben_zasobnik](https://cloud.githubusercontent.com/assets/17909494/21154795/f740e370-c16f-11e6-9dbf-c00abb098eda.jpg)

**Comment by pavelhoral** [comment]
Sjednotil jsem na _zásobník_ (slovo _buben_ tam stejnak moc nepasovalo).
