### ISSUE TITLE
VATS - Brahmin

### ISSUE THREAD

**Issue by Racansky** [prekladyher/fallout4-cestina#129]
U brahminů v systému VATS jsou sice části těla počeštěné, ale
- zadní pravá noha je stále "righ leg"
- přední pravá noha je v množném čísle = "pravé nohy"
- levé nohy jsou spojeny do jednoho objektu a tudíž se ale správně hlásí jako "levé nohy"

**Comment by pavelhoral** [comment]
Díky za report. Tohle skoro vypadá na chybu ve hře, protože to množné číslo je i v originále. Změnil jsem na *Pravou přední nohu* a *Levou zadní nohu*. Opraveno bude v dalším releasu.
