### ISSUE TITLE
Zásobny ukazuje len dve cifry 

### ISSUE THREAD

**Issue by LogenSK** [prekladyher/fallout4-cestina#130]
![20161222034908_1](https://cloud.githubusercontent.com/assets/24708753/21413802/449e901e-c7fa-11e6-9086-e491ab511d50.jpg)
![20161222034915_1](https://cloud.githubusercontent.com/assets/24708753/21413803/44a07bd6-c7fa-11e6-861d-f6dde796b7ec.jpg)

Neviem či už to niekto mal alebo som prvý ale v preklade som si všimol zatiaľ iba tento problém, inak je všetko fajn.

**Comment by pavelhoral** [comment]
Jestli se cifra zastaví na 99, tak to spíš bude záměr hry... ještě zkontroluji, zda nám díky změně fontů nevylezlo třeba plusko "99+".

**Comment by pavelhoral** [comment]
Tak potvrzuji, že místo třech cifer tam jsou jen dvě. Na svědomí to bude mít zřejmě malinko novější řez použitého fontu... a to jsem si myslel, že problém s fonty už máme vyřešené :/. Každopádně díky za report.

**Comment by LogenSK** [comment]
V pohode som rad ze môžem pomôcť

2016-12-22 9:38 GMT+01:00 Pavel Horal <notifications@github.com>:

**Comment by pavelhoral** [comment]
V novém release bude čeština používat stejnou verzi fontů jako originál. Ověřil jsem, že se zobrazují 3 cifry. Možná tím vyřešíme i pár dalších problémů.
