### ISSUE TITLE
Stříbrný Thompson je označován jako kulomet

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#131]
Všiml jsem si, že na některých místech (NOINFO 24) se zbraň Stříbrného Rubáše označuje jako *kulomet*, což je samozřejmě blbost, neboť jde o *samopal*.

**Comment by StoupaJ** [comment]
opraveno v rámci 836452 (1x sID - jinde se již nevyskytuje); bude součástí příštího releasu
