### ISSUE TITLE
zámečník 

### ISSUE THREAD

**Issue by godzilak** [prekladyher/fallout4-cestina#132]
Drobná chybička .... "vypáčit pokročilé zmky" místo zámky :)

![fallout4 2016-12-20 23-25-48-82](https://cloud.githubusercontent.com/assets/24737476/21460240/58846d72-c946-11e6-9af5-9540c3af12ef.gif)

**Comment by pavelhoral** [comment]
Tohle není z našeho překladu... my máme jako popis *Tvé mrštné prstíky ti umožňují otvírat pokročilé zámky.*. U požadavků pak máme zkratku *VNI*.
