### ISSUE TITLE
počet nábojů

### ISSUE THREAD

**Issue by godzilak** [prekladyher/fallout4-cestina#133]
Pravděpodobně nikdo další tuto chybu nemá, protože by už byla hlášená, ale jak je vidět na obrázku špatně mi to ukazuje počet celkových nábojů.... Docela mi to štve. Ze začátku cca do nějakého 4-5 levelu to určitě fungovalo, pak to nějak přestalo, nejspíš jsem si toho nevšiml hned, tak nevím kdy přesně to začalo. Každopádně i po přeinstalaci hry je tam chyba stále. Může to tedy být i tím že používám sejvy, ale zkoušel jsem i nahrát pozici kde vím jistě že to fungovalo a stejně už to ten počet nábojů ukazuje špatně. Zajímavostí je že v energo zbroji ukazuje počet nábojů správně :) 

![fallout4 2016-12-22 01-04-58-61](https://cloud.githubusercontent.com/assets/24737476/21460267/9fd2a9dc-c946-11e6-8637-641bd9df18bf.gif)

**Comment by pavelhoral** [comment]
Nahlášno v #130 ... Jde o naší chybu, konkrétně pak chybu ve velikosti fontu. S dalším releasem bude opraveno.
