### ISSUE TITLE
Nepřeložená kategorie předmětů v qasmoke

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#134]
![fallout 4 12 25 2016 - 11 36 20 01](https://cloud.githubusercontent.com/assets/23583827/21470754/46c9b414-ca97-11e6-9fc3-55448d18b27e.png)

**Comment by marketa1610** [comment]
Nevím jestli se to někde ve hře vyskytuje.

**Comment by Martin005** [comment]
Ve hře se to nikde nevyskytuje, je to pouze v qasmoke.

**Comment by StoupaJ** [comment]
Tohle upozornění je v pořádku ;)
Ale objekty, ke kterým se hráč nemůže nijak dostat standardním hraním (jen pouze přes konzoli), nejspíš řešit nebudeme...
