### ISSUE TITLE
Nápověda (obtížnost přežití) působíš vs. způsobíš

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#135]
![fallout 4 12 25 2016 - 12 34 27 09](https://cloud.githubusercontent.com/assets/23583827/21470960/2b481890-ca9f-11e6-8647-55075a6a875d.png)

**Comment by StoupaJ** [comment]
hoj, to je dle mě správně - při hře Přežití totiž "působíš" (neustále), ne že "způsobíš" (jednou/několikrát).
