### ISSUE TITLE
čárka by tam být neměla.

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#136]
![fallout 4 12 25 2016 - 12 50 22 14](https://cloud.githubusercontent.com/assets/23583827/21470990/e8a86830-caa0-11e6-8009-b09f9b4593d9.png)

**Comment by StoupaJ** [comment]
sakriš, chybka :) díky...

**Comment by StoupaJ** [comment]
opraveno v rámci 9a260f4; bude součástí příštího releasu
