### ISSUE TITLE
Čárky tam nemají být 

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#137]
![fallout 4 12 25 2016 - 13 23 22 15](https://cloud.githubusercontent.com/assets/23583827/21471114/8378f740-caa5-11e6-9d12-d3641a49f8e4.png)

**Comment by StoupaJ** [comment]
hoj, před spojkami jak/jako/než, se nepíše čárka, pokud připojují větný člen; naopak se ale čárka píše, pokud připojují celou větu. Což je tenhle případ. Příklad: "Je línější než já." vs. "Je línější, než jsem já."

**Comment by marketa1610** [comment]
Ty čárky jsou zlo.
