### ISSUE TITLE
Čárky nemají být 

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#138]
![fallout 4 12 25 2016 - 13 34 33 16](https://cloud.githubusercontent.com/assets/23583827/21471134/104fa85c-caa7-11e6-9f7b-7a6daee24b05.png)

**Comment by StoupaJ** [comment]
hoj, tohle je jen doplňující info, které lze vynechat a význam věty přitom zůstává stejný (tedy s čárkami):
"Při objevování světa může být kompas cenným zdrojem informací. Jo a mimochodem, nachází se na spodní straně obrazovky"
