### ISSUE TITLE
Nepřeložen (receiver) 

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#139]
![screenshot12](https://cloud.githubusercontent.com/assets/23583827/21504424/1d5ac32e-cc5f-11e6-9c5d-04d5fe3622f4.png)

**Comment by StoupaJ** [comment]
hoj, tohle je divný... všechno je přeložený... Nemáš tam náhodou nějaký módy nebo DLC?
(základní hra přebírá texty některých DLC, takže když nejsou přeložený, není pak přeložený ani text)

**Comment by StoupaJ** [comment]
@pavelhoral - koukal jsem na to: jsou jen 2 výskyty (oba přeložený), v DLCs žádný samotný "Receiver" není...
Jenže to jsou MISC:FULL a to by přece snad měly být modifikace v inventáři - tahle modifikace v menu by měla být jestli se nepletu OMOD:FULL- tak fakt netuším :(
![image](https://cloud.githubusercontent.com/assets/17909494/21505325/83a64c78-cc66-11e6-9c3d-d2a5993bc25f.png)

**Comment by pavelhoral** [comment]
Tohle vypadá na nějaký nesmysl ve hře... když si tu zbraň přidáš přes konzoli, tak nemá žádné modifikace (normálně by měla mít zbraň vždy nějaký základ) a to menu je rozbité tak, jak je to v tom screenshotu. *Receiver* (a ostatní zde nezobrazené) v tomto případě není OMOD nebo MISC, ale název kategorie, což bude zřejmě nějaká bůhvíkde uložená konstanta.

**Comment by marketa1610** [comment]
To je jen u ručně vyrobené zbraně. U ostatních je to v pořádku.

**Comment by joel2910** [comment]
V misii 3. When Freedom Calls v Sanctuary keď vôjdete do múzea, výjdete po prestrelke s rebelmi hore do kancelárie kde je Preston spolu so svojimi ľuďmi. Jeho pobočník Sturges tam ma rozsiahlejší monológ ohľadne nájdení energozbroje, do ktorej treba zapojiť difúzny článok. Celý tento monológ nie je preložený.

**Comment by pavelhoral** [comment]
@joel2910 Díky za ohlášení. Jde o známou chybu https://github.com/prekladyher/fallout4-cestina/wiki/Zn%C3%A1m%C3%A9-(neopraviteln%C3%A9)-chyby . Dialog je přeložen, ale nezobrazují se správně titulky. Jinak Toto je issue ohledně nepřeloženého slova "receiver", takže to sem nepatří. Oba komentáře (můj i tvůj) tedy za chvilku smažu.

**Comment by pavelhoral** [comment]
Dovolím si zavřít jako nesmysl. Jde o `WEAP` s ID `AAA_StandardGun` a tahle zbraň by se ve hře vyskytovat snad neměla (samozřejmě přes konzoli si ji hráč může přidat).
