### ISSUE TITLE
Bostonský pivovar-terminál-problémy

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#14]
"Vyslal jsem Spartu a její bandu z BADTFL, jestli se jim nepodaří něco najít, ale lidi začnou dezertovat, pokud neseženeme brzy něco jedlého."
Podle mého,by bylo na místě z toho udělat 2 věty. ppř vypustit "ale".
Nebo vypustit "ale" a udělat 2 věty :-)

**Comment by pavelhoral** [comment]
Změněno při hromadné kontrole NOINFO 08 na:

> Vyslal jsem Spartu a její bandu z BADTFL, jestli se jim nepodaří něco najít. Lidi začnou dezertovat, pokud brzy neseženeme něco k jídlu.
