### ISSUE TITLE
Brnění vs. Oblek Stříbrného Rubáše

### ISSUE THREAD

**Issue by StoupaJ** [prekladyher/fallout4-cestina#140]
To přijde divný jenom mně, že jsou sako+kalhoty+kravata ve hře pod názvem brnění :) ?
Sice statistiky to má jako brnění, ale vizuálně to je oblek. Tak dávám návrh tohle předělat na „Oblek Stříbrného Rubáše“.
![image](https://cloud.githubusercontent.com/assets/17909494/21844148/db41a1ac-d7ed-11e6-9ad5-a52d6a69edaf.png)

**Comment by pavelhoral** [comment]
Změnil jsem na _obrněný kostým Stříbrného Rubáše_, jak navrhoval Milhousek v navázané issue. Ještě jsem zvažoval _zbroj Stříbrného Rubáše_, ale takhle je to konzistentní s _obrněným kabátem Železnice_ (a případným budoucím _obrněným oblekem provozáků_ z Nuka-Worldu).
