### ISSUE TITLE
Chyba v názvu likvidace odpadů

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#141]
![fallout 4 01 11 2017 - 18 57 55 01](https://cloud.githubusercontent.com/assets/23583827/21861694/2cbb45c2-d836-11e6-8e03-b6ebd678ffe6.png)

**Comment by StoupaJ** [comment]
Markét, musíš zase mít starou verzi češtiny... Tohle se opravovalo už 1.12.2016 - aktuální verze CZ je z 19.12.2016
