### ISSUE TITLE
Nastřelovací pistole je v LSCR jako hřebíková zbraň

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#142]
V LSCR na mě vyskočila *hřebíková zbraň* (nail gun), což je nesmysl.

http://www.rucni-naradi.cz/hitachi-nc40g
http://www.vseprodrevo.cz/elektricke-naradi/hrebikovacky/

Bohužel nevím, zda zda je oficiálnější *nastřelovací pistole* (což mi trošku zní jako něco, čím se nastřelují náušnice :)) nebo *hřebíkovačka*,

**Comment by Martin005** [comment]
Někdo tomu říká hřebíkovačka (např. společnost Makita) a někdo zase nastřelovací pistole (např. společnost DeWalt), podle mě je nastřelovací pistole oficiálnější.

**Comment by StoupaJ** [comment]
opraveno v rámci 8d658a3 (nastřelovací pistole)
