### ISSUE TITLE
Příkaz  nastup energozbroj 

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#144]
![fallout 4 01 22 2017 - 13 47 12 02](https://cloud.githubusercontent.com/assets/23583827/22184229/e39f10ee-e0cd-11e6-82e4-60c5a9b203ef.png)

**Comment by StoupaJ** [comment]
Tohle je, Markét, hezkej nález... 
Pavle, testnul jsem to a bohužel podstatný jméno se týká všech FURN:FULL, což jsou ale zároveň i přímo pojmenování pro samotnou zbroj (různé druhy), takže s tím se hýbat nemůže. Jedině tedy nějak upravit příkaz „Nastup“. Ale nenapadá mě jak, aby zůstala „zbroj“ v 1.pádu :( 

![schranka](https://cloud.githubusercontent.com/assets/17909494/22197688/6dc126a6-e153-11e6-9177-c746df6c5c83.jpg)
![02](https://cloud.githubusercontent.com/assets/17909494/22197695/720e3046-e153-11e6-8ad2-6840a7d13f3d.jpg)

**Comment by pavelhoral** [comment]
Hele, ukaž se taky na Discordu a zjistíš, že to tam řeším :)

**Comment by Mordrux** [comment]
Tvoje Energozbroj 

a to mi to trvalo ani né 10 vteřin lock vyřešeno 💃

**Comment by Fluik** [comment]
Až na to, že to nemusí nezbytně nutně být energozbroj hráče. Takže za 10 vteřin vyřešeno, ale úplně blbě :D

**Comment by pavelhoral** [comment]
Nejsme jediný národ, který skloňuje názvy. Já bych tu předně zkontroloval, jak se s tímhle popasovali jiné oficiální lokalizace. Pravděpodobně tam vrazíme dvojtečku nebo pomlčku.

**Comment by pavelhoral** [comment]
![obrazek](https://user-images.githubusercontent.com/2012726/33904011-8368a0b2-df7a-11e7-8ec3-32edbf0ce981.png)

**Comment by pavelhoral** [comment]
Dal jsem dvojtečky dle polského vzoru. Některé příkazy jsem malinko upravil (*Stay* →*Zůstaň tady* → *Čekej*).

Pro posazení NPC na kus nábytku je bohužel sdílený překlad *sSit*, který máme jako _Sednout si_. U příkazu pro NPC se za tento překlad lepí název nábytku. To ale nemáme šanci opravit.
