### ISSUE TITLE
Příkaz "prozkoumej" vyžaduje vyskloňovaný tvar předmětu

### ISSUE THREAD

**Issue by marketa1610** [prekladyher/fallout4-cestina#145]
![fallout 4 01 23 2017 - 17 27 02 02](https://cloud.githubusercontent.com/assets/23583827/22212910/accf3114-e192-11e6-8177-89bcff82c275.png)

**Comment by pavelhoral** [comment]
Jde o podobný problém jako v #144.

**Comment by pavelhoral** [comment]
Opraveno v rámci #144 na _Prozkoumej:_ .
