### ISSUE TITLE
Přehozený název questu BoS "Písařka Haylenová"

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#146]
![fallout 4 01 26 2017 - 07 26 09 01](https://cloud.githubusercontent.com/assets/22203490/22322329/950c10b4-e39b-11e6-9146-1ca49947f293.png)

Úkol spadá pod quest "Quartermastery" Hledání technologií je na Prydwenu u Proctora Quinlana !

**Comment by pavelhoral** [comment]
Moje vyjádření z Discordu:

> "Quartermastery" máme jako "Hledání technologií" asi proto, že nikdo netušil, jak to přeložit lépe (a ty úkoly jsou o hledání technologií). V historii Skypu jsem diskuzi nenašel, ale mám pocit, že jsme tohle téma řešili společně.
> U Quinlana máš pak asi na mysli tenhle quest http://fallout.wikia.com/wiki/Getting_Technical. Tenhle quest se mi podle překladů zdá, že nemá název... resp. hráč ho nikde neuvidí.

Nejde tedy o přehozený název questu, ale o úmysl (*Getting Technical* by se překládalo jinak). Samozřejmě můžeme debatovat o tom, zda nejde o špatný překlad.

**Comment by rado-p** [comment]
Snad by to šlo přeložit jako "Rozčtvrcená technotogie"

**Comment by pavelhoral** [comment]
*Quartermastery* pochází od [*quartermaster*](http://www.dictionary.com/browse/quartermaster). Tomu je nejblíže asi *proviantní důstojník*, což je ale, narozdíl od originálu, spjaté hlavně s jídlem. Žádné *rozčtvrcení* bych do toho tedy prosím netahal.

Jestli k tomu má připomínku někdo další, nechť se vyjádří. Prozatím to zavírám jako nevalidní issue.

**Comment by Dumec** [comment]
Ty části myslím nemají s Liberty Prime co dělat - je to prostě vatový quest, hledej donekonečna různé udělátka, serepetičky... v duchu té ideologie Bratrstva už od F1 (shraňují technologii, aby ji chránili před lidmi... a lidi před technologií). Udělal jsem nějaké 4 úkoly, myslím, že se to k tomu robotu nevztahuje (ale mohu se mýlit). Jinak co se čtvrcení týče, souhlasím s Pavlem.
