### ISSUE TITLE
"Ad Victoriam" - někde přeložené do češtiny, někde ne

### ISSUE THREAD

**Issue by Dumec** [prekladyher/fallout4-cestina#147]
Tuto hlášku (něco jako "k vítězství, za vítězstvím!", BoS zvolání) máme někde přeloženou do češtiny, někde ne. Určitě by překládáno být nemělo, ta latina je pochopitelně záměr autorů.

**Comment by pavelhoral** [comment]
Zatím se týká pouze DIAL 06. Přidal jsem to rovnou i do slovníčku.

**Comment by StoupaJ** [comment]
stávající překlady opraveny v rámci 8d658a3
