### ISSUE TITLE
Terminál Satelitní stanice Olivie "dezinsekci"

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#148]
![fallout 4 01 29 2017 - 11 19 24 01](https://cloud.githubusercontent.com/assets/22203490/22404213/778336e2-e62c-11e6-8ba2-118167a120ea.png)

Nejspíš dezinfekci.

**Comment by Martin005** [comment]
Ne, dezinsekce je přímo proces hubení hmyzu - https://cs.wikipedia.org/wiki/Dezinsekce.
