### ISSUE TITLE
Molekulární úroveň (Promluv si s Sturges-em)

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#149]
![fallout 4 01 29 2017 - 14 06 25 02](https://cloud.githubusercontent.com/assets/22203490/22404233/bec05a26-e62c-11e6-9dfc-fe4cccfc80af.png)

**Comment by StoupaJ** [comment]
hoj, tohle je dabl (řeší se v #39 )
jedná se o nutné úpravy všech "Alias" a bude to teda "trochu" obsáhlejší oprava...

**Comment by pavelhoral** [comment]
Zavírám jako duplikát (viz Stoupův komentář).
