### ISSUE TITLE
Nesmazané ID dialog

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#153]
![fallout 4 02 20 2017 - 18 59 19 02](https://cloud.githubusercontent.com/assets/22203490/23138535/4e498bea-f7a8-11e6-92da-fbf40bec3895.png)

Vím že dialogy ještě netestujeme ale už když jsem to objevyl :-)

**Comment by pavelhoral** [comment]
V rámci 6531b7ad jsem hromadně odstranil IDčka a mezery. Bylo toho celkem dost.
