### ISSUE TITLE
LSCR Commonwealth nedává smysl

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#154]
![fallout 4 03 04 2017 - 11 26 21 01](https://cloud.githubusercontent.com/assets/22203490/23578144/7ad61e5e-00d0-11e7-9b54-c56fe2f4f948.png)

**Comment by StoupaJ** [comment]
Hoj, a v čem vidíš nesmysl :) ? Jestli v tom, že se mluví o státu a na screenu je puška, tak to je sice pravda - taky bych tam tématicky očekával model města nebo nějakou mapu, ale překlad je prostě správně...

**Comment by pavelhoral** [comment]
I můj spolubydlící bohužel tvrdí, že ta věta nedává moc smysl a je překombinovaná. On to bude problém velké části LSCR, ale postupně bychom to mohli pořešit.

**Comment by Milhousek** [comment]
Možná by se mohlo použít - _Původnímu státu "Massachusettský Commonwealth" se po Velké válce roku 2077 začalo zkráceně říkat "Commonwealth"_.
