### ISSUE TITLE
Nevhodná hláška "Dosáhl jsi úrovně"

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#155]
https://youtu.be/tgPKofF9XFY?t=22m54s

Při nové úrovni je "neodpohlavněná" hláška (viz video).

V Translate_en.txt pod ID $YOU'VE_REACHED_LEVEL.

**Comment by StoupaJ** [comment]
tohle se opravilo už kdysi (netuším ale kdy...) teď je tam text: "Nová úroveň:"
