### ISSUE TITLE
Quest " Žádné slitování" tykání vs. vykání v jednom dialogu.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#156]
![tykani](https://cloud.githubusercontent.com/assets/22203490/24079012/1166a6fa-0c7e-11e7-833b-dbab19450f6b.PNG)
![vykani 2](https://cloud.githubusercontent.com/assets/22203490/24079014/182da61e-0c7e-11e7-8967-1f524655818e.PNG)
![vykani](https://cloud.githubusercontent.com/assets/22203490/24079015/1e698372-0c7e-11e7-8d8c-d8167f494368.PNG)

**Comment by rado-p** [comment]
Po přidání světlic Starší Maxson vyká.

**Comment by StoupaJ** [comment]
tohle jsem opravoval v rámci 97ce81d4.
Maxon má nějakejch ca 750 dialogů - z toho je momentálně přeloženo ca „jen“ 250 - ty všechny jsem projel a doufám, že snad všude, kde bylo vykání, opravil... 

Tak teď akorát netuším, jestli tedy nechat Issue otevřenou, nebo uzavřít...

**Comment by pavelhoral** [comment]
Hele dostatečně blbé je i to "letadlo", takže bych minimálně v téhle issue opravil ještě to. Originál je "aerial transport", tak bych se toho držel a použil např. *letecký přesun*.

**Comment by StoupaJ** [comment]
opraveno v rámci f521f52d (letecký přesun)
