### ISSUE TITLE
Manta Man není jednotně přeložen

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#157]
Komiksovou postavičku jsme neměli ve slovníčku a mezi překlady se tak různí:

* Manta Man (nepřekládáno)
* Rejnok
* Rejnočí muž

**Comment by pavelhoral** [comment]
Mě se celkem líbí *Rejnok*. Pokud bychom měli nepřekládat, tak bych tam možná po vzoru Spider-Mana vrazil pomlčku.

**Comment by StoupaJ** [comment]
Tak jen pro připomenutí do blízké budoucnosti -->momentálně je všude sjednoceno na "Manta Man" a zbývají ještě 4 nepřeložené řádky...

**Comment by pavelhoral** [comment]
Pokud je to v nepřidělených dávkách (nebo je to v té mé, díky které jsem na to přišel), tak je možné issue zavřít.

**Comment by StoupaJ** [comment]
momentálně vše opraveno (sjednoceno) - uzavírám...
