### ISSUE TITLE
Sjednocení překladu "Default Dummy"

### ISSUE THREAD

**Issue by Martin005** [prekladyher/fallout4-cestina#160]
Výraz "Default Dummy" máme přeloženo třemi různými způsoby:
- Default Dummy
- Výchozí panák
- Výchozí atrapa

Podle slovníčku se má překládat jako "Výchozí atrapa" a je to na 99 % technikálie. I přesto by se to mělo sjednotit.

**Comment by pavelhoral** [comment]
Sjednotil bych to tak, že bych to všude vyresetoval na originál a překlad ze slovníčku odstranil :D

**Comment by StoupaJ** [comment]
kromě jednoho je už všude ENG název - dnes založím hromadné korekce, v kterých toto bude doopraveno - uzavírám...
