### ISSUE TITLE
Oslovení společníka pro příkazy nedává moc smysl

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#161]
Pokud se oslovuje společník pro příkazový režim, tak hráč obvykle používá dvě fráze, které jsou nevhodně přeložené:

* *Heads up.* - *Buď na pozoru.*
* *Look alive.* - *Trochu života...*

Jsem si jistý, že pro obě fráze nalezneme lepší překlad. Navrhuji třeba něco ve stylu:

* *Heads up.* - *Poslouchej...*
* *Look alive.* - *Poslouchej...* (ano, klidně stejně) / *Dávej pozor...*

**Comment by StoupaJ** [comment]
bude nahrazeno v dnešních hromadných korekcích (uzavírám...):
Heads up - 6x DialogueCommandPlayer --> nahrazeno "Poslouchej..."  (zbytek EDID je OK)
Look alive - 4x DialogueCommandPlayer --> nahrazeno "Dávej pozor..."  (zbytek EDID je OK)

(Note: např. MrHandy už má "Look alive!" jako "Dávejte pozor!", tak to tak dáme i u těch 4 ostatních...)
