### ISSUE TITLE
Executive Terminál v MacCreadyho questu není jednotně přeložen

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#163]
Quest log mluví o "řídícím terminálu", terminál samotný se jmenuje "terminál vedení". V dialozích použiji asi to druhé.

http://fallout.wikia.com/wiki/Long_Road_Ahead

**Comment by pavelhoral** [comment]
Ještě je možnost změnit na úplně něco jiného - třeba "manažerský terminál" ("ředitelský terminál", ...). "Terminál vedení" nezní bůhvíjak. To by se ale chtělo do té lokace portnout a kouknout, čí je to kancelář.

**Comment by StoupaJ** [comment]
tohle jsme nejspíš asi už probírali, jen se neuzavřela tahle ISSUE?
 --> totiž všude, včetně obou QUST:xNAM, to je jako "terminál vedení"

**Comment by pavelhoral** [comment]
Potvrzuji sjednocení na _terminál vedení_.
