### ISSUE TITLE
Dialogy jsou v angličtině prosím Pomoc!

### ISSUE THREAD

**Issue by Goesss** [prekladyher/fallout4-cestina#165]
Všechno je v češtině ale dialogy mám ve hře furt v angličtině.

**Comment by Noxmen** [comment]
Mam ten stejny problem, dnes jsem zakoupil na Steamu Fallout 4, po stazeni hry verze 1.9.4.0.0 jsem do adresare \data vlozil cestinu verze 20170123-f4cs-eab4055 a soubor ini do \my games\fallout 4, vysledek je takovy, ze menu hry a nektere zelene texty ve hre jsou ok prelozeny, ale dialogy vzdy zacinaji vykricnikem a nasleduje EN text, napriklad !Oh, well done
viz screeny
![fallout4_1](https://user-images.githubusercontent.com/31324168/29687306-2b9368c2-891c-11e7-8bdb-152b2d8b09c3.jpg)
![fallout4_2](https://user-images.githubusercontent.com/31324168/29687307-2ec14762-891c-11e7-8007-b8494a3f15bb.jpg)
![fallout4_3](https://user-images.githubusercontent.com/31324168/29687313-32388eb4-891c-11e7-94b1-96d49ffa043d.jpg)

**Comment by pavelhoral** [comment]
Dialogy nejsou ještě přeložené. ALFA, která je k dispozici obsahuje překlad všeho, **kromě dialogů**. Více viz novinka, ve které jsme vydání ALFA verze oznámili - https://prekladyher.eu/tema/%C5%A0%C5%A5astn%C3%A9-a-vesel%C3%A9-od-p%C5%99ekladatelsk%C3%A9ho-t%C3%BDmu-fallout-4.1176/.

Češtinu i s dialogy chceme vydat v rámci BETA verze někdy okolo letošních vánoc. Více viz nedávno publikovaný rozhovor - https://www.facebook.com/videohrycesky/photos/a.1211681522263294.1073741828.1210744439023669/1358266460938132/?type=3&theater .

Postup překladu je možné sledovat na našem profilu - https://prekladyher.eu/preklady/fallout-4.79/ .
