### ISSUE TITLE
Diamond city-pastor Clements

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#17]
Opět problém s oslovením "slečno".

**Comment by Racansky** [comment]
@ Dumec ..... a co z toho vyjít po vzoru jednoho českého úsloví - "Do kdy můžete říkat ženě Slečno ..... dokud slyší " .... tedy i zachovalá 60tka by v tu chvíli mohla být "mladou paní"

**Comment by pavelhoral** [comment]
Oslovení jsem odstranil. *Mladá paní* tam působila jako pěst na oko.
