### ISSUE TITLE
Jiná složka než jakou má steam primární (Nefunguje překlad)

### ISSUE THREAD

**Issue by MotoCZ** [prekladyher/fallout4-cestina#170]
Ahoj, hry na steamu jsem si nastavil ať se mi stahují do jiné složky než do té normální a tak se mi tam stáhl i Fallout 4. A když jsem si stáhl manuální verzi překladu udělal všechno podle návodu tak nefunguje pořád angličtina. Fallout 4 mám zde: C:\Hry-Steam\steamapps\common\Fallout 4 PS: Nemusí to možná být tou jinou složkou.

**Comment by pavelhoral** [comment]
Ještě je potřeba nahrát na správné místo Fallout4Custom.ini. Viz 3. krok v [postupu instalace](https://github.com/prekladyher/fallout4-cestina#manu%C3%A1ln%C3%AD-instalace).

Jinak na případné rady doporučuji spíš Discord - https://discord.gg/rUxYwwp, než zdejší hlášení chyb.
