### ISSUE TITLE
Nefunkčné sťahovanie!

### ISSUE THREAD

**Issue by MaGotold** [prekladyher/fallout4-cestina#171]
Nejde mi stiahnúť ani jedna čeština na tejto stránke.Ak kliknem na stiahnúť tak mi to ukáže aby som sa prihlásil.pri registrácii mi to povie,že registrácia nie je dostupná...čo mám robiť?

**Comment by StoupaJ** [comment]
Hoj, soubor mi šel rovnou stahnout i bez přihlášení na GH... -->  neklikáš někam úplně jinam? 

![image](https://user-images.githubusercontent.com/17909494/33516754-498272e2-d778-11e7-8cec-9306bf4b2d16.png)
