### ISSUE TITLE
Safra...

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#172]
Na základě diskuze se zvažuje změnit na "Sakra"
![fallout 4 screenshot 2017 12 03 - 09 47 06 74](https://user-images.githubusercontent.com/22203490/33525090-922efb9a-d828-11e7-8486-dd7b5a1852ca.png)

**Comment by pavelhoral** [comment]
Dodávám, že to máme v překladech 14krát a jde o překlad slova *heck*.

**Comment by StoupaJ** [comment]
proboha proč změna? tohle je naprosto regulérní výraz a je naprosto rovnocennej s výrazem "sakra".
![image](https://user-images.githubusercontent.com/17909494/33525656-6677b396-d834-11e7-83e9-a09f58db2448.png)

**Comment by pavelhoral** [comment]
Netahej do toho Boha :)... *safra* používaj babičky a dědové. Můžu ti sem dát screenshot příručky *plantážníka* a taky nebude to argument pro jeho použití.

**Comment by StoupaJ** [comment]
změněno všech 13 výskytů - uzavírám...
