### ISSUE TITLE
Překlepy

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#174]
![fallout 4 screenshot 2017 12 03 - 14 39 31 42](https://user-images.githubusercontent.com/22203490/33526238-6c7daf7a-d83e-11e7-881e-ffa742d6d062.png)
![fallout 4 screenshot 2017 12 03 - 15 03 42 12](https://user-images.githubusercontent.com/22203490/33526240-707e2d7a-d83e-11e7-8723-7b3d45404ca1.png)

**Comment by rado-p** [comment]
Kellog: To ji "stále" víc než ...........
Edward: .... "kterř" se o sebe u......

**Comment by StoupaJ** [comment]
Chce to prostě vydat novou verzi CZ --> tyhle překlepy jsou už nějakej čas opravený...

**Comment by rado-p** [comment]
Aha, tak zatím nebudu testovat.

**Comment by pavelhoral** [comment]
Pokud je to opravené, tak to můžeme zavřít.
