### ISSUE TITLE
DN049 Director -> Řídící

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#175]
V galerii GA bych možná celkem rád vyměnil *Ředitele* za *Řídícího*. Dle mého to více odpovídá významu, kdy je v roli jakéhosi "robotického koordinátora".

**Comment by pavelhoral** [comment]
Koukám, že v tom questu DN049 je celkem bordel, takže by tohle skoro mohlo být evidováno jako chyba. Někde tam máme *vedoucího*, někde nahrazujeme za *řídící systém* (nemusí být nutně chyba). Každopádně *Director* pochází z *Director Management System*, což máme jako *Centrální Řídicí Systém*. Tedy tato úprava skoro není ani tak vylepšení, jako žádost o sjednocení.

**Comment by StoupaJ** [comment]
opraveno v předchozích úpravách
