### ISSUE TITLE
Překlep v pojmenovaní Rajče

### ISSUE THREAD

**Issue by White-Wolf-CZ** [prekladyher/fallout4-cestina#178]
![screenshot6](https://user-images.githubusercontent.com/34418862/33805963-00f7549e-ddc1-11e7-83f9-31b583ba2216.png)
V budovatelském pohledu je špatně pojmenovaná plodina Brajče -->Rajče viz. scr.

**Comment by pavelhoral** [comment]
Ta rostlina se tak jmenuje schválne, protože to je radiaci odolný hybrid brambory a rajčete. Ještě byla alternativa to pojmenovat *bramborajče*, ale nám se líbil víc ten kratší název.
