### ISSUE TITLE
Deezerova limonáda by měla být asi citronáda

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#179]
V několika dialozích jsou na tohle narážky a Nukapedia má například následující odstavec:

> *He is very enthusiastic about his lemonade, stating that the town had voted his drink the best drink in town for three years, despite not knowing what is in the lemonade exactly. It is very likely that the lemonade contains no lemons at all, as noted by a few people.*

Ve slovníčku překlad *Deezer's lemonade* zatím nemáme.

**Comment by Dumec** [comment]
Jj, já jsem to měl několikrát v té poslední dávce, ale nenapadlo mě, že vlastně existuje ještě výstižnější slovo citronáda... dokud jsi to tady nenapsal, vůbec by mi nepřišlo, že se lemonade dá přeložit i jinak než limonáda, byla to pro mě stejná automatika jako třeba tea = čaj... ale rozhodně dejme citronádu, díky tomu bude několik dialogů mnohem lepších a vtipy pochopitelnější.

**Comment by pavelhoral** [comment]
Deezerova je ve hře už jen *citronáda* :).
