### ISSUE TITLE
Instalátor češtiny, chybová hláška.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#183]
![vystrizek](https://user-images.githubusercontent.com/22203490/34263088-9889eb04-e66e-11e7-8a61-e4e5de30e6c5.JPG)

Je potřeba prvotní spuštění hry aby se zapsal "Custom.ini" který pak instalátor přepíše.

**Comment by Martin005** [comment]
Instalátor by mohl v takovém případě vložit Custom.ini do složky `~/My Documents/My Games/Fallout4/`. Při spuštění totiž hry totiž hra nepřepíše Custom.ini, jen do něj doplní
```
[Display]
iLocation X=0
iLocation Y=0
```

**Comment by pavelhoral** [comment]
Upravil jsem chybovou hlášku:

![obrazek](https://user-images.githubusercontent.com/2012726/34321410-eecc8174-e80e-11e7-8396-f6cee811626a.png)

Donutit instalátor nahrát soubor jednoduše neumím.

**Comment by Martin005** [comment]
Kontrolu existence souboru Fallout4Custom.ini jsem z instalátoru smazal. Takže teď, pokud tento soubor neexistuje, je instalátor schopen ho sám vytvořit.
