### ISSUE TITLE
PS4: Nefunguje navázaná akce na dialog

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#186]
Vytvářím na základě hlášení z FB:

> ahoj tak první chybka k nahlášení. Na Ps4 při hře za ženu je rozbité vlákno kdy u plotu reknete důstojníkovi že musíte do valutu a on misto aby vás pustil tak se sekne a stale se ptá zda máte povolení

https://www.facebook.com/falloutczsk/posts/892793294222809

**Comment by Martin005** [comment]
Uživatel "testik" na Discordu potvrdil, že na PC tento problém nenastává. Ještě by to chtělo někoho s XB1.

**Comment by pavelhoral** [comment]
Já bych sem hlavně přidal info, že popsanou chybu se podařilo obejít přepnutím do angličtiny a zopakováním rozhovoru. Takže to úplně hru naštěstí úplně nezablokuje.

**Comment by Martin005** [comment]
Po vyzkoušení samostatného esp na PC se tento problém taky objevuje (jak za ženu, tak za muže).

**Comment by pavelhoral** [comment]
https://www.youtube.com/watch?v=27Cm_V8GrCU&t=948s

**Comment by pavelhoral** [comment]
Naše modifikace z nějakého důvodu nezachovává pořadí některých dialogových hlášek. Jelikož hra bere tu první, která sedí na herní podmínky, tak tady vybere bohužel obecnou reakci, místo té správné, která posouvá quest do další fáze.

![obrazek](https://user-images.githubusercontent.com/2012726/34338866-2eb30b1e-e96d-11e7-8d5f-c0e52d8a704c.png)

Zatím ještě zkoumáme, čím se to pořadí řídí.

**Comment by pavelhoral** [comment]
Na INFO záznamech chyběl PNAM určující jejich pořadí v rámci modifikace. Po doplnění to funguje. Do hodinky nahraju opravnou verzi 0.9.1 na Bethesda.net.
