### ISSUE TITLE
Nepřeložený kompas v energozbroji

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#187]
Hlášeno Aramonem na prekladyher.eu:

![image](https://user-images.githubusercontent.com/2012726/34327497-96ad55d2-e8c6-11e7-92e8-0f2b619ae265.png)

**Comment by StoupaJ** [comment]
tohle jsem už říkal někde úplně na začátku překladu - ale nejen kompas, jedná se o celé menu energozbroje (CORE/AP/HP/Ammo...) - jenže tohle je napřímo textura(y) v ba2 archivu

**Comment by pavelhoral** [comment]
Pokud je to textura, tak to můžeme zavřít. Dopíšu to do seznamu neopravitelných chyb.
