### ISSUE TITLE
Concord / postava Sturges

### ISSUE THREAD

**Issue by echo676** [prekladyher/fallout4-cestina#188]
Cca po 1 a pul hodině hraní nové hry ve městě Concord nefungují ubec titulky pro postavu Sturges (titulky zůstávají z poslední konverzace jiné postavy). Co jsem pochytil tak mluví o tom jak získat energozbroj a díly potřebné k jeho zprovoznění. Hledal jsem v příspěvcích zda už tohle není hlášeno, ale nenašel jsem to. Děkuji.

**Comment by Martin005** [comment]
Je to jeden z problémů hry, viz wiki https://github.com/prekladyher/fallout4-cestina/wiki/Zn%C3%A1m%C3%A9-(neopraviteln%C3%A9)-chyby
