### ISSUE TITLE
Preston Garvey

### ISSUE THREAD

**Issue by RomanQo** [prekladyher/fallout4-cestina#189]
Po prichode do Concord na zaciatku hry, Preston Garvey ma zamrznuty titulok: Sturgesi, Rekni ji to. napriek tomu, ze dialogov je tam kopec, vzdy ostane tento vysvieteny. A to aj p interakcii s mojou postavou.

R.

**Comment by Martin005** [comment]
Díky za report. Řešilo se to již v #188. Je to jeden z problémů hry, viz wiki https://github.com/prekladyher/fallout4-cestina/wiki/Zn%C3%A1m%C3%A9-(neopraviteln%C3%A9)-chyby
