### ISSUE TITLE
Neprelozene vlastnosti

### ISSUE THREAD

**Issue by RomanQo** [prekladyher/fallout4-cestina#190]
Vlastnost V.A.T.S. (V.A.N.S), Awareness, Lone Wanderer, Mysterious Stranger, Attack Dog, Scrapper, Rad resistant, Night Person, Strong back, Steady Aim, Critical Banker, Quick hands, Sniper, Ghouilsh, Wasteland Whisperer, v strome vlastnosti nie su prelozene :)

**Comment by perin225** [comment]
Tyto perky jsou v základní hře bez DLC přeloženy (hraješ pouze s Fallout4.esm). Pokud ovšem hraješ s DLC, tak je čeština přepsána u shora uvedených perků DLCčkama, myslíš, že konkrétně Nuka World a Far Harbor (.esm).  Musíš počkat na překlad DLC a nebo, pokud hraješ na PC, si je v FO4Edit dopřeložit (tj. jen zkopírovat již přeložený text ze základní hry - alespoň co se prvních pár ranků týče, poslední ranky pochází většinou s DLC).

Tohle upozornění je i na úvodní stránky češtiny:

https://github.com/prekladyher/fallout4-cestina/wiki/Zn%C3%A1m%C3%A9-(neopraviteln%C3%A9)-chyby

**Comment by pavelhoral** [comment]
Díky za report, nicméně je to tak, jak píše @perin225 . Zavírám.
