### ISSUE TITLE
Perk Kovář má nějaký divoký popisek

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#192]
![image](https://user-images.githubusercontent.com/2012726/34337174-a2b98a16-e95d-11e7-98ae-624714c89ee9.png)

**Comment by StoupaJ** [comment]
překlep opraven "Roztop kovárnu" --> v řešení, zda popis úplně přepsat...

**Comment by pavelhoral** [comment]
Změnil jsem *roztop kovárnu* na *roztop kovářskou výheň*.

**Comment by Milhousek** [comment]
Nebylo by lepší _rozžhav_?

**Comment by pavelhoral** [comment]
Výheň se podle mě roztápí.
