### ISSUE TITLE
získávání materiálu - guma z rádia

### ISSUE THREAD

**Issue by Ruppy84** [prekladyher/fallout4-cestina#193]
Nejsem si jistý, ale hodila by se spíš nějaká elektronika (děje se v každém případě min. v Senctuary).
`https://photos.app.goo.gl/Flt3gSnOA16Qr5Lf2`

**Comment by perin225** [comment]
Řekl bych, že tohle nebude problém češtiny.
V anglické verzi hry též člověk dostane gumu. Co se týče složení materiálu, je to divné, na druhou stranu, v rámci češtiny řešit, co člověk dostane za materiály je irelevantní. Zkus některé z módů, třeba existuje mód, který napravuje složení materiálů, které dostaneš rozložením rádia.

Jinými slovy, čeština jen přeložila položky. Neřeší složení materiálu jako takového.

**Comment by Ruppy84** [comment]
Jestli to není problém češtiny omlouvám se, napadl mě překlep v odkazu/referenci nebo tak, ale neznám detaily formy překladu. V anglické verzi jsem si toho nevšiml, zde to ale trochu bije moje technické oko :), předám Bethesdě ;)

**Comment by pavelhoral** [comment]
Občas z některých předmětů padají nesmyslné věci (např. z *hliníkového tácku* je tuším *ocel*). S tím překlad nemá nic společného :)
