### ISSUE TITLE
Chybky v překladu

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#194]
![chyba2](https://user-images.githubusercontent.com/34834709/34339465-d48d10d2-e974-11e7-813d-59270efacb58.png) - chválí jeho ne sebe
![chyba1](https://user-images.githubusercontent.com/34834709/34339466-d4acffc8-e974-11e7-8b55-9b6eb894fa8a.png) - 3x to samé a pokaždé jiný překlad :) varianta 2 mi připadá nejlepší

**Comment by pavelhoral** [comment]
Opraveno a sjednoceno (oboje jsem malinko upravil).
