### ISSUE TITLE
Nahradit uzmout něčím lepším

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#196]
Na Discordu padl návrh vyměnit *uzmout* za něco míň matoucího... 

![image](https://user-images.githubusercontent.com/2012726/34339828-de7a792c-e979-11e7-821c-84f5459071d0.png)

**Comment by StoupaJ** [comment]
(2a8f9d) --> upraveno na: "Prosím, přijměte leták a stavte se..."

**Comment by gugust** [comment]
uzmout je krásný slovo
