### ISSUE TITLE
Holopáska manželku adresuje jako může

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#197]
Založeno z diskuze na Discordu...

![image](https://user-images.githubusercontent.com/2012726/34339956-98ec5ce8-e97b-11e7-80ae-d6a7a58c618f.png)

Je teda potřeba ověřit, že neadresuje dítě, ale to by bylo hodně divné.

**Comment by ErinaCZ** [comment]
Jestli on Nate nemluvi k Shaunovi.

**Comment by Milhousek** [comment]
Vyřešeno v issue #3
