### ISSUE TITLE
Cricket - v jednom dialogu vyká

### ISSUE THREAD

**Issue by Fluik** [prekladyher/fallout4-cestina#198]
V tomhle dialogu vyká, ale v ostatních máme tykání.

![20171225193857_1 jinde tyka](https://user-images.githubusercontent.com/10829041/34343398-64c2169a-e9cd-11e7-8fbc-31e73a8abbd5.jpg)

**Comment by StoupaJ** [comment]
opraveno (d0d155c0)

**Comment by pavelhoral** [comment]
Otevírám, protože ten dialog je špatně. Jestli to chápu správně, tak volá na kolemjdoucí, aby si u ní koupili zbraně. Volání *no tak* je opravdu nesmysl.

**Comment by Fluik** [comment]
Hele mě to řekla po tom, co jsem ji oslovila. Ale je možný, že to říká i jen tak, když projdeš kolem.

**Comment by pavelhoral** [comment]
Ok... zavírám. Já jsem myslel, že by si to zasloužilo trošku přepsat, ale třeba na to narazím později :).
