### ISSUE TITLE
Křeslo pro Mámu Murphyovou

### ISSUE THREAD

**Issue by Fluik** [prekladyher/fallout4-cestina#199]
V dialogu žádá o "plstěné křeslo" ve workshopu je to ale jako křeslo pro Mámu Murphyovou nebo tak něco. Asi by neuškodilo to sjednotit, aby bylo jasné, že je to ono - původně jsem si myslela, že ji stačí jakýkoliv křeslo.

![20171225215403_1 ve workshopu to je jako kreslo mamy](https://user-images.githubusercontent.com/10829041/34343407-be1092f8-e9cd-11e7-9dde-432346b70a7d.jpg)

**Comment by Lukaszno1** [comment]
Souhlasím, měl jsem to stejně.

**Comment by TheSonny21** [comment]
Je pravda, že při prvním hraní v originále  jsem taky nevěděl, že musím hledat přímo to její křeslo, ale tady bych klidně byl pro "vylepšení nedokonalosti vývojářů"  a napsal to tam jasně, ať to nemate.

**Comment by StoupaJ** [comment]
já musím prásknout, že jsem byl o tuhle "stavbu" ochuzen, ba co víc - přímo okraden :D  !
Jak jsem je dovedl do Sanctuary, tak ještě na mostě jsem MM ukecal, aby přestala brát drogy... a tím po mně tak vůbec křeslo nechtěla (a samozřejmě její dialogy o Vidění tak byly taky pryč).

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "moje vlastní křeslo"
