### ISSUE TITLE
Správcův terminál Vault 111

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#2]
Slovo vzdálení (technici třeba), vzdáleně - není myšleno spíš dálkoví, externí, dálkově? Občas to tam zní vážně divně. 
Věta "Nepoužité kryopody jsou... atd." - nedává smysl.

**Comment by StoupaJ** [comment]
hoj,  co se týče věty: „Nepoužité kryopody jsou preferovanou metodou pro odklízení těl.“ Možná by to šlo napsat lépe, ale mně ta věta bez problémů dává smysl: 
„_Pro odklízení těl upřednostňujte ze všech možností uložení těl do nepoužívaných kryopodů._“

**Comment by pavelhoral** [comment]
Tohle si dovolím označit za nevalidní. Jinak slovo *vzdálený* je ofiko překlad slůvka *remote* ve smyslu, v jakém se to používá u počítačů (viz například https://cs.wikipedia.org/wiki/Vzd%C3%A1len%C3%A1_spr%C3%A1va).
