### ISSUE TITLE
Trochu jiné téma

### ISSUE THREAD

**Issue by pepiczech88** [prekladyher/fallout4-cestina#200]
Zdravím, už nevím kam se obrátit tak se obracím na vás. Nemohli byste mi poradit jak se zbavit rozpixelovaných okrajů postav? zkusil jsem už všechny různé kombinace nastavení grafiky a nic nepomohlo. Ani žádný mód to nedělá. Nevíte třeba o nějakém opravném modu nebo jiném řešení?

![screenshot0](https://user-images.githubusercontent.com/34847306/34344733-2ccdf09e-e9e9-11e7-9ae7-4b90fec25ff8.png)

**Comment by pavelhoral** [comment]
Tady bohužel s tímhle neporadíme. Můžeš zkusit oficiální podporu Bethesdy nebo nějaká fóra, která se hrou zabývají.
