### ISSUE TITLE
Chybná Shaunova reakce

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#202]
Předchozí věta je "Přijde mi, že máš vždycky dobrou náladu, prcku."

![image](https://user-images.githubusercontent.com/2012726/34364116-d01168be-ea82-11e7-8c1b-a33feb31caf2.png)

Místo slova nebyl, by mělo být neměl.

**Comment by StoupaJ** [comment]
opraveno (673cf4)
