### ISSUE TITLE
Chyba v textu "Kellogg Fort Hagen"

### ISSUE THREAD

**Issue by MikeFreedom** [prekladyher/fallout4-cestina#203]
**Stejná louka**
![20171227152910_1](https://user-images.githubusercontent.com/34890350/34384251-5ae21de2-eb1b-11e7-8e2d-1349c02a2eb4.jpg)

**Comment by StoupaJ** [comment]
díky za report, je opraveno (673cf4)

**Comment by pavelhoral** [comment]
Já bych tu větu ještě trošku učesal... *Kamaráde, jsem stejná loutka jako ty.* (první zájmeno je zbytečné a slůvko *jen* se mi tam trošku bije se stejným slovem ve druhé větě).

**Comment by StoupaJ** [comment]
(2a8f9d) --> upraveno na: "Kamaráde, jsem stejná loutka jako ty."
