### ISSUE TITLE
Nesrovnalost v textu

### ISSUE THREAD

**Issue by ghost** [prekladyher/fallout4-cestina#205]
![fallootbug](https://user-images.githubusercontent.com/34897122/34392474-9584462e-eb4c-11e7-9cde-ea4a120897bc.jpg)

Dobrý den,
 s hlášením bugů nemám zkušenosti, ale jelikož jste si udělali čas na češtinu, zkusím si udělat čas na vás a něco se naučit:)

Na začátku hry při opouštění Vaultu se mě nezdá hláška v terminálu, jak u něj leží ten vědec (nevím jak to líp popsat) 

text "dokonce i ta rodinka, co čekala na poslední chvíli"

mě přijde, že oni na nás čekali, až do poslední chvíle a ne, že já jsem čekal

pokud je to blbost omlouvám se za zdržování.
s pozdravem Tonavalec

**Comment by pavelhoral** [comment]
Významově to je, že "čekala s rozhodnutím, zda být součástí programu vault programu". Asi by se to dalo napsat "co to nechávala na poslední chvíli".

**Comment by ghost** [comment]
Ok děkuji, mám takové věci hlásit dál, nebo to pro vás nemá žádný přínos?

**Comment by pavelhoral** [comment]
Pokud si nejsi jistý, zda je něco chyba, tak je asi nejslepší před založením se zeptat v diskuzi na Discordu - https://discord.gg/rUxYwwp . Jinak to smysl určitě má.

**Comment by StoupaJ** [comment]
(2a8f9d) --> upraveno na: "i ta rodinka, co to nechávala na poslední chvíli."
