### ISSUE TITLE
Překlep v rozhovoru se Sturgesem

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#210]
![20171229194736_1](https://user-images.githubusercontent.com/34947824/34446820-b41b1fe8-ecde-11e7-8a4d-8ef962618da1.jpg)

Překlep v poslední větě - Ta věc **nejni** zdravá.

**Comment by StoupaJ** [comment]
Díky za report...  jedná se ale o nespisovný hovorový výraz (něco jako "pojď sem" --> "pocem")
