### ISSUE TITLE
Nepřeložené názvy dvou nápojů

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#211]
![20171229201306_1](https://user-images.githubusercontent.com/34947824/34446922-91ca6290-ecdf-11e7-935d-acd4741673ab.jpg)

Názvy Gwinnett Ale a Gwinnett Brew, by měly být přeloženy.

**Comment by pavelhoral** [comment]
Oba druhy piv jsou ponechány takto schválně. *Ale* se standaradně používá i v českých pivovarech (https://cs.wikipedia.org/wiki/Ale_%28druh_piva%29). *Brew* bohužel nemá moc český ekvivalent (alespoň my jsme na něj nepřišli)... je to potřeba brát jako značku piva. Inspirací nám bylo i například toto  - https://cs.wikipedia.org/wiki/Pivovar_N%C3%A1chod.
