### ISSUE TITLE
Špatný popis Kompenzátoru?

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#212]
![20171229195004_1](https://user-images.githubusercontent.com/34947824/34447335-1299cf3e-ece3-11e7-9d38-c812316cb907.jpg)

V popisku u kompenzátoru je napsané, že snižuje dostřel, avšak ve statistikách zbraně se dostřel zvyšuje.

**Comment by Milhousek** [comment]
Zjistil jsem, že kompenzátor u některých zbraní dostřel zvyšuje a u některých snižuje. Takže nejspíše chyba ve hře, nikoliv v překladu.

**Comment by pavelhoral** [comment]
Pozor, nahrazuješ bajonet, který snižuje dostřel. Kompenzátor očividně snižuje dostřel méně.
