### ISSUE TITLE
Hráč robotovi vyká, je to na té lodi.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#213]
![fallout 4 screenshot 2017 12 30 - 06 57 44 38_li](https://user-images.githubusercontent.com/22203490/34452350-bd001500-ed3d-11e7-834f-e4aac9a84f0b.jpg)

**Comment by StoupaJ** [comment]
Tohle ale není vykání robotovi. Hráč tak mluví směrem k celé posádce lodi. Např. jiná replika z questu:
"Opravte si tu loď sami. Vašimi rozkazy se neřídí­m."
