### ISSUE TITLE
Robot hráči tyká.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#214]
![fallout 4 screenshot 2017 12 30 - 06 58 33 58_li](https://user-images.githubusercontent.com/22203490/34452377-1dbc20be-ed3e-11e7-8905-fd2023670228.jpg)

**Comment by StoupaJ** [comment]
Díky... bude opraveno (pro jistotu jsem prošel všechny repliky Bocmana - ty jsou OK...)
