### ISSUE TITLE
Překlep v textu.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#215]
![fallout 4 screenshot 2017 12 30 - 07 02 33 62_li](https://user-images.githubusercontent.com/22203490/34452381-365537dc-ed3e-11e7-9219-ff658bc78aa1.jpg)

**Comment by StoupaJ** [comment]
"Systémy jsou hladovy" --> Bocman  má zastaralou mluvu a prostě se takto vyjadřuje :) 
Jedna jeho replika to tak trochu objasňuje:
"...jsem byl pětkrát přeprogramován, abych celým srdcem miloval ty úžasné slovní obraty a anachronismy."
