### ISSUE TITLE
Chybí "jste si"

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#216]
![fallout 4 screenshot 2017 12 30 - 07 03 28 88_li](https://user-images.githubusercontent.com/22203490/34452386-5fa89764-ed3e-11e7-997b-ecf1979017e6.jpg)

**Comment by StoupaJ** [comment]
Tady je to myšleno: Jistě by dokázali poradit (lidé z těch obchodů, které navrhuji navštívit).
