### ISSUE TITLE
Robot hráči tyká.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#217]
![fallout 4 screenshot 2017 12 30 - 07 11 05 67_li](https://user-images.githubusercontent.com/22203490/34452388-723b8b66-ed3e-11e7-8de6-1c1880a25c8e.jpg)

**Comment by StoupaJ** [comment]
díky... bude opraveno - prošel jsem všechny dialogy Navigátora - ještě je 1 k opravě, jinak všude už vyká.
Jediná jeho hláška je tak "Ahoj, vojáku" - což je ale přímo námořnickej pozdrav "Ahoy" - takže to zůstává...
