### ISSUE TITLE
Po updatu neslape...

### ISSUE THREAD

**Issue by vojtyz** [prekladyher/fallout4-cestina#220]
Zdravim borci,
Diky moc za ultra luxusni preklad hry, kazdopadne po poslednim updatu se hra po nacteni zasekne na loading screenu a nenacte se :( po idebrani modu vse ok...

**Comment by pavelhoral** [comment]
Používáš i jiné mody?

**Comment by vojtyz** [comment]
Neco tam mam ale vsechny jsem povypinal... Koukal jsem ze po odebrani i
odinstalovani cestiny zustavaji texty (napr nazvy zbrani) stale prelozene,
tak jestli v tom nemuze byt problem

Dne 30. 12. 2017 20:29 napsal uživatel "Pavel Horal" <
notifications@github.com>:

**Comment by vojtyz** [comment]
Ted zkousim preinstalovat hru, dam vedet jestli pomohlo

**Comment by vojtyz** [comment]
Tak reinstall nezabral :/ disable/enable taky ne, starsi save se taky nespusti, vsechny mody jsem odstranil, taky nic...

**Comment by pavelhoral** [comment]
Kdybys měl chuť to řešit online na Discordu, bylo by to příjemnější - https://discord.gg/rUxYwwp

**Comment by vojtyz** [comment]
Vyreseno odebranim vsech modu, reinstallem hry (neni podle me ani potreba), new game se zapnutou cestinou, vytvorit postavu, nechat ulozit, nacist ulozenou pozici - slape. Diky za vsechno :)

**Comment by pavelhoral** [comment]
Nakonec se ukázalo, že modifikace byla nějaká nakopnutá (po restartu hry přestávala fungovat). V noci jsme sestavili verzi 0.9.2 znovu a nahráli ji na Bethesda.net. Problém to vyřešilo. https://www.facebook.com/falloutczsk/posts/896303883871750
