### ISSUE TITLE
Rozhovor s paladinem Dansem - špatné "oslovení".

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#222]
![20171230225644_1](https://user-images.githubusercontent.com/34947824/34457990-7e3b601a-edc2-11e7-964c-515e0113d907.jpg)

Při oslovení paladina Danse občas zazní fráze - **"Excuse me, paladin Danse?"**, která je přeložena jako **"Omluvíte mě, paladine Dansi?"**

**Comment by StoupaJ** [comment]
týkalo se 14 oprav (2a8f9d)  --> upraveno "S dovolením" (aby odpovídalo tykání a zároveň je třeba něco formálnějšího než obyčejné "mohu?/ na slovíčko?)
