### ISSUE TITLE
korekce textu před atomovkou

### ISSUE THREAD

**Issue by StoupaJ** [prekladyher/fallout4-cestina#223]
Projel jsem předválečnej začátek a našel 5 chyb (z toho je jeden text v Translate_en.txt)
4 řádky jsem už našel a hned je opravím, jen ta 5. věta "Got that right...", jak jinak přeložit? Nemá to totiž jinak návaznost...
![20171230211415_1](https://user-images.githubusercontent.com/17909494/34458077-04c0df96-edc5-11e7-8550-45d0f873b67b.jpg)
![20171230211520_1](https://user-images.githubusercontent.com/17909494/34458078-06a3fadc-edc5-11e7-8c4c-cb2c06cc626c.jpg)
![20171230211630_1](https://user-images.githubusercontent.com/17909494/34458079-08069de4-edc5-11e7-80e2-c48a454b100d.jpg)
![20171230213323_1](https://user-images.githubusercontent.com/17909494/34458080-0937196e-edc5-11e7-9e20-4bd37ae3b693.jpg)
![20171231003113_1](https://user-images.githubusercontent.com/17909494/34458081-0a60452c-edc5-11e7-8343-cb7ee44180c3.jpg)

**Comment by StoupaJ** [comment]
4 řádky opraveny (2a8f9d) / 5. poslední čeká na vyjádření...

**Comment by pavelhoral** [comment]
> 5. poslední čeká na vyjádření...

A to je přesně důvod, proč by se v rámci jedné issue nemělo reportovat více věcí :D

**Comment by Fluik** [comment]
A nemělo by v tom prvním případě u všecho být "výrazná", když to jsou oční víčka? (Pokud to teda není společné pro jiné části)

**Comment by StoupaJ** [comment]
je to společný pro části očí --> včetně právě samotných očí :)

**Comment by StoupaJ** [comment]
vše je již upraveno - zavírám...
