### ISSUE TITLE
"Je na čase jít dál"

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#224]
![image](https://user-images.githubusercontent.com/2012726/34462187-63c320ac-ee3e-11e7-9452-3bd4f1a3a4e2.png)

Založeno dle hlášení z Discordu... as by se tam mohlo vrazit "**Je** na čase jít dál."

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "Je na čase"
