### ISSUE TITLE
Skloňování pneumatický

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#227]
MISC - miscmod_mod_armor_VaultTec_Lining_Torso_LessStagger[00245AF4]
MISC - miscmod_mod_armor_Metal_Lining_Torso_LessStagger[00245AF0]

Chce to synchronizovat jestli se odkazuje na zbroj nebo na trup. 
"pneumatická pneumatický"

Je to tak 50/50 u všech výskytů

**Comment by StoupaJ** [comment]
opraveno (51c532) --> projeto všech ca 150 pojmů pro "(trup)"- opraveno 5 na "á" (tak jak je u ostatních).
![image](https://user-images.githubusercontent.com/17909494/34469553-db7ebbcc-ef21-11e7-8469-466c6224a203.png)
