### ISSUE TITLE
Chyba v popisku u LSCR

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#228]
![20180101134852_1](https://user-images.githubusercontent.com/34947824/34468771-4d960df8-ef10-11e7-910d-ecaf77194b6f.jpg)

V popisku by mělo být - _zkus odložit svou zbraň_ nikoli _zkus odhodit zbraň_.

**Comment by StoupaJ** [comment]
No ve hře ale opravdu přímo "zahazuješ" zbraň (a i jiné nepotřebné položky) - je to přímo nabídka v menu. A řekl bych, že policie tě taky vyzývá spíš "odhoďte zbraň", než "odložte zbraň" - tam ale má vlastní zkušenost nezasahuje :)

**Comment by pavelhoral** [comment]
@StoupaJ Nerozumím poznámce. Jestli je ta mnechanika založená na schování zbraně, tak je jedno jestli se dá ve hře zahodit.

**Comment by StoupaJ** [comment]
No já právě netuším, jestli ji stačí "pouze" schovat... měl jsem pocit, že ji hráč musí úplně odhodit... aby případně protivník přestal útočit...

**Comment by Milhousek** [comment]
Ano v inventáři je nabídka pro odhození věcí z inventáře, ale tady je to myšleno jako odložit či sklonit zbraň.
Edit: Jednoduše řečeno, jde o to aby jsi v ruce zbraň nedržel, což se dá provést podržením tlačítka R. A taktéž je v originále napsáno _try putting away your weapon_.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "odložit"
