### ISSUE TITLE
Špatné výrazy v terminálu

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#229]
![20171230221450_1](https://user-images.githubusercontent.com/34947824/34468790-a34bea4c-ef10-11e7-87c1-357c2922b0a2.jpg)

Chyby v názvu terminálu a některých větách. Viz. Rozpad signálů, širokopásmové frekvence apod.

**Comment by pavelhoral** [comment]
Přidávám své poznámky z Discordu:

> * Naměřit "údaje" vs "hodnoty"...
> * To, že se signál objevuje v rámci extrémně vysokofrekvenčního pásma není "širokopásmová frekvence" (extreme high-band spectrum frequency).
> * A nejsem si jistý, že slůvko decay se česky řekne rozpad... každopádně já bych si z té věty třeba nedomyslel, že se mluví o velmi ostrém útlumu / ukončování signálu (The decay on these signals is severe).

Nevhodných obratů tam je vícero.

**Comment by pavelhoral** [comment]
Prošel jsem a upravil celý terminál.
