### ISSUE TITLE
Buben vs zásobník

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#230]
MISC - miscmod_mod_SubmachineGun_Mag_MediumQuick[001B290B]

má být buben ne zásobník (v návaznosti na ostatní)

**Comment by StoupaJ** [comment]
díky za info. Tohle se řešilo ještě v 2016 a nějak nedotáhlo (na screenu ještě původní chybný "kulomet")
 - opravit by se ještě měla 2. věc - samotný popis modifikace zbraně: mod_SubmachineGun_Mag_Medium 
![image](https://user-images.githubusercontent.com/17909494/34469669-a9011c0a-ef24-11e7-8503-4e773b4c2d1e.png)

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno "buben"
