### ISSUE TITLE
Střelecká vs Ostrostřelecká

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#231]
MISC - miscmod_mod_Gammagun_Grip_Better2[001889DE]

asi u 2 zbraní je střelecká místo ostrostřelecká

**Comment by StoupaJ** [comment]
díky za info - ten druhej záznam je:
dn_CommonGun INNR:WNAM - Sharpshooter's - [Střelecká]

**Palko**, je tam ještě druhá varianta modifikací "Marksman" a v INNR máme:
dn_CommonGun INNR:WNAM - Marksman's - [Střelec]

 - tak tohle by chtělo sjednotit -dej když tak vědět kterou variantu a já to upravím (kratší se mi zdá lepší):
 buď obě [Ostrostřelecká] & [Střelecká], nebo [Ostrostřelec] & [Střelec]

**Comment by cert23** [comment]
pro marksman určitě střelec a sharpshooter ostrostřelec

**Comment by pavelhoral** [comment]
Jestli mě tu chceš označovat, tak musíš používat správný nick @StoupaJ ;). Kouknu se na to.

**Comment by StoupaJ** [comment]
nee :) to by už byl zbytečnej třetí spam (na ISSUE je už jeden v emailu,  druhej je v Discordu) Jen sem tě zvýraznil :)

**Comment by pavelhoral** [comment]
@StoupaJ Ne, spam je tvá odpověď a teď moje reakce. Je to spam, který bychom mohli řešit, kdybys byl na Discordu. Označování má smysl, pokud chceš reakci někoho konkrétního. Zvýraznění jména je naprosto zbytečné... vůbec jsem si to nemusel přečíst, protože to nebylo adresované mně.

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno
