### ISSUE TITLE
Kapacitor vs kondenzator

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#232]
Record: MISC - miscmod_mod_LaserMusket_Receiver_4[001AB283]

pouze u muškety je překlad jako kapacitor všude jinde kondenzátor

**Comment by StoupaJ** [comment]
u muškety to je kompletní popis (8 záznamů) - tak to možná byl záměr.
K tomu se musí vyjádřit @pavelhoral (jsou to dávky N20/N22)
![image](https://user-images.githubusercontent.com/17909494/34469886-4905b68c-ef27-11e7-9a20-77d0b2e20cb6.png)

**Comment by StoupaJ** [comment]
u muškety zůstává kapacitor...
