### ISSUE TITLE
Překlep v dialogu s Piper

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#234]
![20180101232312_1](https://user-images.githubusercontent.com/34947824/34472451-2ea61278-ef63-11e7-95a3-aef4f45f703c.jpg)

**Comment by pavelhoral** [comment]
Nějak ten překlep nevidím. Mohl bys kdyžtak vždy u screenshotů psát i pár klíčových slov v textové formě (ono se to hodí i třeba když člověk hledá, zda danou chybu už někdo nenahlásil)?

**Comment by Milhousek** [comment]
Omlouvám se, moje chyba, nevšiml jsem si dlouhého i ve slově _příkras_ a tím pádem mi to nedávalo smysl.

**Comment by pavelhoral** [comment]
Zavírám tedy jako *nevalidní*.
