### ISSUE TITLE
Nepřeložený název zbraně

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#235]
![20180101235633_1](https://user-images.githubusercontent.com/34947824/34472507-225c37e4-ef64-11e7-9d76-102d166fc711.jpg)

**Comment by pavelhoral** [comment]
FYI tohle máme ve slovníčku s následujícím komentářem:

> Unikátní laserová pistole. Může odkazovat na gejzír v Yellowstonu, který se ani u nás nepřekládá. Pokud to ale chcete přeložit, tak klidně sem s návrhy.

Mám to tam ale poznačené, že se k tomu mám vrátit. Přeložil bych to... někde v historii našeho překladatelského chatu bude jistě spousta návrhů.

**Comment by gugust** [comment]
Vydrž, brnknu kamarádovi do USA, on je magor přes zbraně a určitě proto má českej výraz.

**Comment by pavelhoral** [comment]
@gugust To asi nemusíš :). Já to stejně vidím, že skončíme na *Staré věrné* (ve stylu predátorovské *bezbolestné*... my ten překlad podle mě máme někde vymyšlený).

**Comment by gugust** [comment]
Už to mám, takle se říkalo 50tce medvědibijce v dobách zlatokopecký horečky. Jinak ano, stará věrná je stejné jak místní daný vodotrysk nazývají. Nazývají ho tak proto, že co tryská tak stále stejně, "starý dobrý co nezklame, vždy na čas a vždy stejně"
Kdby jsi to nazval "moje věrná stará" nic tím nezkazíš"

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "Stará věrná"
