### ISSUE TITLE
Překlep v dialogu s Moe-m

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#236]
![20180101235852_1](https://user-images.githubusercontent.com/34947824/34472531-c07f86d8-ef64-11e7-8d59-a977627a88a4.jpg)

Asi by tam měl být _Obří chlapi_ a ne _Olbřímí chalpi_

**Comment by pavelhoral** [comment]
*Olbřímí* je [normální slovo](http://prirucka.ujc.cas.cz/?slovo=olb%C5%99%C3%ADm%C3%AD), nicméně tady bych asi souhlasil, že zrovna u Moe Cronina nevidím důvod, proč by tenhle tak trošku anachronismus měl používat (spíše by se hodilo *ohromní chlapi* / *ohromný chlapiska*... nevím co tam je v originálu).

**Comment by StoupaJ** [comment]
Big brutes of guys

**Comment by pavelhoral** [comment]
Změnil jsem na *obří chlapiska*. Upravil jsem i *Bloody Mary Sue* z *Otravné Krvavé Mary* na pouhou *Krvavou Mary* (je mi jasný dvojsmysl originálu, ale v češtině mi to znělo krkolomně).
