### ISSUE TITLE
Špatný překlad nájezdníka?

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#237]
![20180102004509_1](https://user-images.githubusercontent.com/34947824/34472557-12ddff4a-ef65-11e7-9c49-494b9f9ba1ec.jpg)

_Přeživší nájezdník_ by asi bylo lepší, než ten výraz survivalista.

**Comment by gugust** [comment]
Stím absolutně nesouhlasím, Survival je celosvětově uznávaný název a nelze ho překládat jako přeživší, ale jako "znalý technik pro přežití" a je úplně jedno jestli se jedná o bojové techniky či schopnost přežít sám v pralese. Prostě Survivalista je noční můra. Přeživší může bejt každej kdo zalezl do kanálu co ho sundám jednou ranou.

**Comment by gugust** [comment]
Už to mám, takle se říkalo 50tce medvědibijce v dobách zlatokopecký horečky. Jinak ano, stará věrná je stejné jak místní daný vodotrysk nazývají. Nazývají ho tak proto, že co tryská tak stále stejně, "starý dobrý co nezklame, vždy na čas a vždy stejně"

**Comment by gugust** [comment]
Ono kdyby jsi to nazval "moje věrná stará" tak tím nic nezkazíš

**Comment by gugust** [comment]
už jsem to smáznul, nespal jsem 72 hodin, stavím Vault 88

**Comment by pavelhoral** [comment]
Toto je překlad ze slovníčku. Jako obvykle se nebrátním diskuzi o volbě překladu, nicméně nejde o chybu. V tomto případě issue zavírám, protože mi to přijde jako dobrý překlad :). https://cs.wikipedia.org/wiki/Survivalismus
