### ISSUE TITLE
Steak z radškorpiona - popisek efektu

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#239]
![20180102013051_1](https://user-images.githubusercontent.com/34947824/34472586-88283536-ef65-11e7-8189-dfcb12b80bc2.jpg)

Asi by to chtělo zkrátit popisek efektu - _Odolnost vůči energetickému poškození_ - aby byl čitelnější.

**Comment by pavelhoral** [comment]
Tady bych poprosil, ať už to bude opravovat kdokoliv, aby dotyčný zkontroloval délku všech podobných záznamů (zřejmě MGEF?).

**Comment by Milhousek** [comment]
![20180103130624_1](https://user-images.githubusercontent.com/34947824/34520681-0062dbb2-f08a-11e7-9c03-354fe9dbaa89.jpg)

Narazil jsem na další předmět s tímto problémem, tak to dám sem ať zbytečně nezakládám další issue.

**Comment by Milhousek** [comment]
![20180104195415_1](https://user-images.githubusercontent.com/34947824/34586550-be4efbfe-f1a4-11e7-8499-100b7025cf07.jpg)

Stejný případ, jen jiný předmět.

**Comment by StoupaJ** [comment]
hledal jsem řetězec "odolnost vůči energetickému poškození" a je to pouze AVIF - ty jsou ale dva AVIF:ANAM & AVIF:FULL - tak netuším, který je pro co...  jinak jsem tedy u AVIF vyjel délku znaků a tady jsou všechny "delší"  - teoreticky by stačilo zkrátit 4 z nich (délka přes 36 znaků)...
![image](https://user-images.githubusercontent.com/17909494/34588792-2a92bf80-f1af-11e7-96bd-164117910ff4.png)

**Comment by pavelhoral** [comment]
Je to ANAM. A zkrátit jich bude potřeba vícero. Já bych všechny "Odolnost vůči" dal na "Odoln. v." (už takhle tam máme MGEF *DMG Resist* jako *Odoln. v. ZRA*). Resp. mělo by se to udělat podobně.
  
![obrazek](https://user-images.githubusercontent.com/2012726/34589388-a50faf74-f1b0-11e7-8d60-4db1ba8cf898.png)

**Comment by StoupaJ** [comment]
no - samozřejmě stačí určit do kolika znaků to nechat --> třeba zkracovat od 20 výš... Některý by tak ale jako třeba "Závislost na Bzukoblížcích" nevypadaly zkráceně nic moc... Takže takový nechat a zkracovat jen tam, kde jsou ta tři slova: "odolnost" - "odol." / "poškození" - "pošk." / "vůči" - "v."

Jestli takhle ano, stačí dát vědět - mrknu na to při nejbližší příležitosti...

**Comment by pavelhoral** [comment]
Takové tam určo nebudou. Tzn. ne všechny budou zobrazovaný tady v tom dialogu. Závoslost je něco, co je vidět v přehledu efektů, ale ne v tomhle mini-okénku. Víceméně se bavíme jen o "Odolnost vůči..."

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno (zkráceno) 8x
