### ISSUE TITLE
Pochybný Valentýn

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#240]
![20180102020535_1](https://user-images.githubusercontent.com/34947824/34472602-c5531db8-ef65-11e7-8667-e2593de5e0ec.jpg)

Jelikož se v téhle misi vydáte zachránit Nicka valentina, tak by se asi název questu měl jmenovat _Pochybný Valentine_ (tedy jako NPC).

**Comment by pavelhoral** [comment]
Jde o hru se slovy... ano, zachraňuje se Nick Valentine, ale v originále je Valentine's Day svátek svatého Valentýna, aka. Valentýn. Název questu naráží na to, že je quest o nějakém podivném Valentýnu.
