### ISSUE TITLE
Pohledem z Vaultu, část 3. - překlep

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#241]
![20180102021239_1](https://user-images.githubusercontent.com/34947824/34472613-0d3e7f32-ef66-11e7-846f-11cdf9408c00.jpg)

Na začátku poslední věty přebývá písmeno _M_

**Comment by neradplatim** [comment]
V druhé části by asi mělo být **my** 
![screenshot1](https://user-images.githubusercontent.com/35042916/34497878-a59d4774-efff-11e7-8aac-e006eee92bb7.png)

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno
