### ISSUE TITLE
Překlep v dialogu s Maxson-em

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#243]
![20180102175957_1](https://user-images.githubusercontent.com/34947824/34494632-c1af1f9a-eff1-11e7-81ef-c353970c7140.jpg)

Překlep ve slově _experimentování_ - chybí _**x**_
Asi by bylo lepší celou větu upravit, zní celkem kostrbatě. Např. - Nejsem ochoten dovolit Institutu aby pokračoval v tomto experimentování.

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno
