### ISSUE TITLE
Překlep v dialogu s Maxson-em ohledně přesunu hlavic na Prydwen

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#245]
![20180102190016_1](https://user-images.githubusercontent.com/34947824/34495313-f5af885e-eff4-11e7-9488-0c7b6f32e892.jpg)

Přesun válečných hlavic Tlusťoch na Prydwen - asi by bylo lepší něco jako - přesun jaderných hlavic do Tlusťocha na Prydwen

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno "do Tl."
