### ISSUE TITLE
Překlep u střelci

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#246]
![20180101210619_1](https://user-images.githubusercontent.com/34834709/34495411-50378b96-eff5-11e7-8019-6b25552535a0.jpg)

Je nějaký speciální důvod pro velké S?

**Comment by Milhousek** [comment]
Střelci - officiální název pro NPC, se kterými se lze setkat při plnění úkolu kdy zachraňuješ Nicka  Valentina.

**Comment by pavelhoral** [comment]
Tohle možná ještě vysvětlí Stoupa, ale je rozdíl, když se mluví o pojmenované skupině (Střelci, Ranaři), nebo když se mluví o členech skupiny (střelci, ranaři).

*Přepadli nás 4 střelci.  Byli ze skupiny jménem Střelci.*

**Comment by pavelhoral** [comment]
I když asi to otevřu. Možná by si to zasloužilo přeformulovat, aby bylo jasnější, že jde o název skupiny... *těší se velké oblibě mezi členy gangsterské skupiny Střelci.* Názor?

**Comment by Milhousek** [comment]
To by bylo nejspíše lepší, více to objasňuje o koho se jedná.

**Comment by cert23** [comment]
Jo tak tak daleko jsem se ještě nedostala. A takto to na mě působilo jako střelci z 30tých let.

**Comment by pavelhoral** [comment]
Opraveno dle mého posledního komentáře.
