### ISSUE TITLE
Způsobilé k palbě

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#249]
Nemělo by tady být "připravené k palbě" (nekoukal jsem, co je v originále)?

![image](https://user-images.githubusercontent.com/2012726/34506981-28f821de-f032-11e7-9802-a1b23029b755.png)

**Comment by StoupaJ** [comment]
capable of live-fire...

**Comment by pavelhoral** [comment]
Díky. Pak by to asi mělo být *schopné palby*. Slůvko *způsobilé* mi tam nesedí.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "schopné palby"  (2x)
