### ISSUE TITLE
Hmoždinky - terminál Red Rocket

### ISSUE THREAD

**Issue by Fluik** [prekladyher/fallout4-cestina#250]
Z Discordu: 

Red Rocket Terminal hned ten u Sanctuary...asi bych změnil hmoždinku za šroubek ...přeci jenom u výroby nahradních dílů na auta se hmoždinky nepoužívaj..

![20180103175749_1](https://user-images.githubusercontent.com/10829041/34533841-3ccd600e-f0bc-11e7-82d7-b857678b3d82.jpg)

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "... pokaždé, když změní specifika u pitomýho šroubku. Prostě vezmeme nějakej, co máme, a seříznem ho, aby seděl."
