### ISSUE TITLE
Vault 81 - "stavím se sem"

### ISSUE THREAD

**Issue by Fluik** [prekladyher/fallout4-cestina#252]
Screen jsem nestihla, ale máme tam "Pokud budu někdy potřebovat nový účes, stavím se sem." Mělo by tam být "stavím se tady", řiká to hráč klukovi při prohlídce vaultu.

**Comment by StoupaJ** [comment]
Tohle je ale OK varianta: "stavím se sem." --> "dojdu si sem."   Záleží, jak se zeptáš: "kam" nebo "kde".

**Comment by Fluik** [comment]
To se na mě nezlob, ale to je OK varianta jen pro nějakej místní dialekt :D Kdyby to bylo "dojdu si sem" tak to beru, ale "stavím se" jedině "tady".

**Comment by Fluik** [comment]
Opraveno v ff63367
