### ISSUE TITLE
LSCR 2813 - modifikace zbraní

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#253]
![20180103145502_1](https://user-images.githubusercontent.com/34947824/34534208-959b4fec-f0bd-11e7-82a6-0c44555ae998.jpg)

Nebylo by lepší - _Modifikace zvyšující váhu zbraně, zároveň prodlužují čas potřebný k zamíření._

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno dle popisu
