### ISSUE TITLE
překlep v terminálu producenta v Hubris Comics

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#254]
![20180103151314_1](https://user-images.githubusercontent.com/34947824/34534351-17695cf8-f0be-11e7-8616-ab78db1e9b34.jpg)

Místo _musíme s ní podepsat_, má asi být _musíme to s ní podepsat_ nebo _musí to s námi podespat_, jelikož se tam jedná (nejspíše) o podepsání smlouvy.
V originále je - we need to sign her.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "to s ní"
