### ISSUE TITLE
překlep v LSCR 8995 - perk Přátel zvířat

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#255]
![20180103152336_1](https://user-images.githubusercontent.com/34947824/34534620-20e9b4d4-f0bf-11e7-9907-974f6c6856bc.jpg)

místo slova _zamířit_, by bylo vhodnější _namířit_ (svou zbraň na zvířata).

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "namířit" (3x)
