### ISSUE TITLE
Překlep v LSCR 5138 - Strážní robot

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#256]
![20180103153049_1](https://user-images.githubusercontent.com/34947824/34534698-7ae6fce4-f0bf-11e7-846b-9bb937acad11.jpg)

Nejspíše by mělo být _Strážní robot_ s velkým **_S_**, jelikož se jedná o vlastní název.

**Comment by StoupaJ** [comment]
hoj,  "strážní robot" bereme jako obecný název robota --> stejně jako "očko" / "anihilatron"
