### ISSUE TITLE
Překlep v holopásce Jsme hotovi

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#260]
![20180103230648_1](https://user-images.githubusercontent.com/34947824/34545855-0754963e-f0f0-11e7-9fe6-21d87d088ba5.jpg)

Nikomu _nám_ nic neříkali. _Nám_ je tam navíc, případně upravit např. na _Nikomu z nás nic neříkali / neřekli._
_Informovali mě dnešní odpoledne_ - je taky takové e-e, řekl bych.

**Comment by pavelhoral** [comment]
Upravil jsem věty napříč celou holopáskou.
