### ISSUE TITLE
Překlep v terminálu písařky Haylenové

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#261]
![20180103233031_1](https://user-images.githubusercontent.com/34947824/34545983-2716b53c-f0f1-11e7-8f4c-0117cf3bf5d7.jpg)

Slovo _nedostatečné_ bych nahradil slovem _nevyhovující._

**Comment by pavelhoral** [comment]
V rámci #229 jsem tu větu přepsal na:

> Pokusila jsem se o vnitřní šití, ale naše zázemí je naprosto nedostatečné pro operaci takového rozsahu.

V tomhle tvaru slůvko *nedostatečné* už tolik nevadí a issue tedy zavírám.
