### ISSUE TITLE
Překlep v terminálu USS Constitution

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#262]
![20180104005333_1](https://user-images.githubusercontent.com/34947824/34546115-1778fc10-f0f2-11e7-802d-e0df5af2d161.jpg)

Jelikož se jedná o proměnnou, tak by se tam více hodilo _Proměnná RevoluceZacina nebyla deklarována_ namísto _nevyhlášena_.

**Comment by pavelhoral** [comment]
Upraveno.
