### ISSUE TITLE
MSI instalátor nefunguje, pokud chybí Fallout4Custom.ini

### ISSUE THREAD

**Issue by SickBoy161** [prekladyher/fallout4-cestina#263]
MSI instalátor po spuštění neustále píše, že hru je před instalací češtiny nutno alespoň jednou spustit (obr. v příloze). Hra však byla spuštěna již několikrát. Zkoušel jsem instalovat i za chodu hry a stále ta samá odezva.
![bez nazvu](https://user-images.githubusercontent.com/35094108/34553908-54f680fc-f12a-11e7-8541-5e83ba9ac07e.jpg)

**Comment by pavelhoral** [comment]
Tohle se dá obejít tím, že se soubor `Fallout4Custom.ini` (klidně prázdný) vytvoří ručně ve složce `__Uživatel__/Dokumenty/My Games/Fallout4`. Instalátor se pak na něj chytne.

**Comment by SickBoy161** [comment]
pavelhoral: Díky za radu! Sice nevím, jak vytvořit .ini soubor, ale dík tobě mě napadlo "Fallout4Custom.ini" vygooglovat a stáhnout.

**Comment by StoupaJ** [comment]
Můžeš si "vytvořit" klidně i exe, dll, xls soubor (samozřejmě nefunkční) :D
Nejjednodušší je (třeba na Ploše) pravým myšítkem - volba "Nový", tam vybrat "Textový dokument".
A takovýhlemu obyčejnýmu texťáku pak už jen stačí přepsat název a **hlavně tu příponu** na jakou zrovna potřebuješ. Jde o to, že je prostě jen potřeba, aby ho instalátor viděl...

**Comment by pavelhoral** [comment]
Jen si sem (pro sebe) odložím dva odkazy, abych je nemusel znovu hledat, až to budu řešit:

* http://wixtoolset.org/documentation/manual/v3/xsd/wix/customaction.html
* http://wixtoolset.org/documentation/manual/v3/customactions/qtexec.html

Ideální by bylo, pokud by instalátor `Fallout4Custom.ini` uměl vytvořit.

**Comment by Martin005** [comment]
Kontrolu existence souboru Fallout4Custom.ini jsem z instalátoru smazal. Takže teď, pokud tento soubor neexistuje, je instalátor schopen ho sám vytvořit.
