### ISSUE TITLE
Překlep v LSCR 9699 - blokování útoku z blízka

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#265]
![20180104003729_1](https://user-images.githubusercontent.com/34947824/34565619-d31bae18-f15b-11e7-9914-41ff2f6396dd.jpg)

Myslím, že z téhle věty není jasno, zda útočník nezpůsobí žádné poškození nebo hráč útočníkovi.
Pro ujasnění by bylo dobré odebrat _**t**_ ze slova _nezpůsobit_

Případně popis upravit např. - _Aktivním blokováním útoku z blízka, můžeš útočníka odrazit a jeho úder/útok ti nezpůsobí žádné poškození._

**Comment by Milhousek** [comment]
![20180104211100_1](https://user-images.githubusercontent.com/34947824/34587242-c1cd8f72-f1a7-11e7-9bcf-100adba6a8d6.jpg)

Duplikát LSCR s č. 9698 s jiným překladem.

**Comment by gugust** [comment]
Aktivním blokováním útokem zblízka, můžeš útočníka odrazit a nezpůsobí ti tak žádné zranění.
nebo
Aktivním blokováním útočníka útokem zblízka, ti nezpůsobí žádné zranění.

**Comment by pavelhoral** [comment]
V rámci sjednocování překladu *damage* bylo již opraveno na:

> Aktivní blokování útoku zblízka může útočníka odrazit a zabránit tak jakémukoliv zranění.
