### ISSUE TITLE
Slovo navíc - terminál dozorčího

### ISSUE THREAD

**Issue by Steedr** [prekladyher/fallout4-cestina#266]
![screenshot0](https://user-images.githubusercontent.com/35104379/34567333-230aae46-f162-11e7-9607-65700f5919a4.png)

Řekl jsem to panu Feldovi a on "se" (je tam navíc).

**Comment by pavelhoral** [comment]
Celé je to takové e-e.

> *aby zkontroloval, **co děláme**... začal mít podezření ohledně toho, **co** tu ve skutečnosti **děláme***

A obrat *nadosmrti zavřou* se mi také moc nelíbí.

**Comment by pavelhoral** [comment]
Záznamy v tom terminálu jsem malinko upravil. Konkrétně tenhle záznam je teď:

> Dnes přišel na neohlášenou kontrolu inspektor práce s nebezpečnými materiály. Přišlo mi, že trošku začíná tušit, co tu ve skutečnosti děláme. Řekl jsem to panu Feldovi a ten prohlásil, že jestli se v tom začne inspektor šťourat, tak se ho máme zbavit - a nemyslel tím, že ho mám poprosit, aby odešel. No, šťoural... tak jsme se ho museli zbavit. Jestli někdo zjistí, co jsme provedli, tak mě nadosmrti zavřou...
