### ISSUE TITLE
myslím, že si budeme rozumět

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#268]
![20180104152031_1](https://user-images.githubusercontent.com/34834709/34572248-39d045d2-f171-11e7-8e9c-2db93532cacb.jpg)

**Comment by StoupaJ** [comment]
Že hraješ mužskou postavu? Tuhle a ještě tři podobné další repliky říká Magnolie, ale dle scriptů jen mužské hráčské postavě - tím by to tak bylo OK. **EDIT: beru zpět - tohle může říkat F/M hráči...**

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno (4x)
