### ISSUE TITLE
Překlep a podivná věta v dialogu s Jackem Cabotem

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#269]
![20180104221451_1](https://user-images.githubusercontent.com/34947824/34586605-edcb37da-f1a4-11e7-8fcc-72f64084ff69.jpg)

Ve slově _zmocnil_ chybí **_L_**.

**Comment by Milhousek** [comment]
![20180104221848_1](https://user-images.githubusercontent.com/34947824/34588048-43f94c4a-f1ab-11e7-8ba1-63c78566b042.jpg)

Bylo by asi lepší upravit druhé souvětí, je takové kostrbaté.

**Comment by StoupaJ** [comment]
Já tam spíš vidím přebytečné "o" ve slově dobou - pak by to bylo celkem OK. "... strávil jsem takovou **dobu** snahou..."
  
Možná ještě by šlo zcela vypustit slovo "nechat".

**Comment by pavelhoral** [comment]
Já bych ještě *ho* dal před *vyléčit*.

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno "zmocnil" - na druhý screen jsem zapomněl...

**Comment by pavelhoral** [comment]
Přepsáno na:

> Navždy bych pak o svého otce přišel. To odmítám dopustit, když už jsem věnoval tolik času snaze o jeho vyléčení.
