### ISSUE TITLE
Překlep v holopásce Vojína Hartové

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#270]
![20180104205138_1](https://user-images.githubusercontent.com/34947824/34587192-7dcd8b88-f1a7-11e7-9779-f90e63a957cd.jpg)

Správně by tam mělo být _Co nás našlo!_.

**Comment by StoupaJ** [comment]
No, to ale vůbec nezní česky...  "Majore, co nás našlo!" - Všeobecně se u překladu do jiného jazyka někdy nedá držet striktně originálu, protože to v jiné řeči zní nesmyslně nebo to mění význam.

Tedy věta by šla: "Majore, **ně**co nás našlo!" --> jenže takto to právě mění význam originálu, kdy na pásce probíhá dialog ve stylu: "Něco tu je... útočí to... --> našlo nás to!" (přesně si už ten text holopásky samozřejmě nevybavuju).

**Comment by Milhousek** [comment]
V originále je - _What found us!_ navazuje to na řeč Majora, která začíná -  _It found us_

**Comment by pavelhoral** [comment]
Dal jsem tam oproti originálu otazník:

> Majore. Majore! Co nás našlo?
