### ISSUE TITLE
Hráč Kentu Connollymu vyká

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#272]
![20180105105951_1](https://user-images.githubusercontent.com/34947824/34610272-b09e7e68-f220-11e7-8601-ec519a5a37c9.jpg)

Po zachránění Kenta před Sinjinem a následném rozhovoru je v nabídce vykání, místo tykání.

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno
