### ISSUE TITLE
Překlep v rozhovoru s Clair

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#273]
![20180105113514_1](https://user-images.githubusercontent.com/34947824/34610396-38213e48-f221-11e7-8a12-9a0be37ba882.jpg)

_že kdyby ti viděli_ - _ti_ by bylo vhodnější vynechat.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "kdyby viděli"
