### ISSUE TITLE
Holopáska Sal

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#274]
![20180104193051_1](https://user-images.githubusercontent.com/34834709/34614083-8658e7f0-f230-11e7-9b41-82ea982db281.jpg)

To "Aji" mi připadá jako překlep

**Comment by Milhousek** [comment]
Pripada mi to v poradku, pripadne zamenit za _i_

**Comment by cert23** [comment]
V pořádku? Slovo "aji" opravdu neznám.

**Comment by Milhousek** [comment]
Asi ti to prijde absurdni, ale ja takove slovo znam :)

**Comment by cert23** [comment]
V českém pravopise?

**Comment by Milhousek** [comment]
Zalezi jestli dana postava mluvi spisovne nebo ne.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "I kdybych"

**Comment by Martin005** [comment]
Našel jsem "aji" ještě v [000F787A]. Opravil jsem to v (267d1d8).
