### ISSUE TITLE
Překlep v dialogové volbě s Jackem Cabotem

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#276]
![20180105230338_1](https://user-images.githubusercontent.com/34947824/34635083-e7c0b5ae-f28a-11e7-8279-f12de0faa777.jpg)

_Nejsem si jistá_ je špatně, vzhledem k tomu, že hraju za mužskou postavu. Každopádně se tato volba musí upravit tak aby byla použitelná jak pro ženskou tak pro mužskou postavu.

Edit: Možná něco jako _Nevím jistě._

**Comment by StoupaJ** [comment]
(d8eb04b) opraveno "Nevím jistě" (3x)
