### ISSUE TITLE
Špatné zobrazení potřebných zátek pro stavbu obchodu v osadě

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#277]
![20180105221014_1](https://user-images.githubusercontent.com/34947824/34635123-7e843f38-f28b-11e7-91a0-7b55c377704a.jpg)

V požadavcích je napsáno 100 zátek, přičemž je potřeba 1000.

**Comment by StoupaJ** [comment]
vyzkoušeno na ENG hře bez CZ - to samé -> bohužel to je bug Bethesdy, ne češtiny.
