### ISSUE TITLE
Nepřeloženo

### ISSUE THREAD

**Issue by BohyCZ** [prekladyher/fallout4-cestina#279]
Závodiště easy city, při ovládání závodů není přeložen terminál 
<img src='https://i.imgur.com/ZSUJtDG.png' />

Kráter Atoma při hledání Virgila je komunikace taky v eng

<img src='https://i.imgur.com/1wRwz5v.jpg' />
  

A vstup do základny železnice je označen jako RaiRoad HQ.

**Comment by Milhousek** [comment]
Nehraješ náhodou s nějakýma módama? Protože já mam vstup do základny Železnice přeložen - Velitelství Železnice.
Mám jen základní hru bez žádných DLC nebo modifikací.

![20180106190929_1](https://user-images.githubusercontent.com/34947824/34642570-46d6218e-f315-11e7-8816-cf6ed1bc1f30.jpg)

**Comment by BohyCZ** [comment]
Ano na mapě je označeno správně, ale jdi ke kostelu, nebo jak jdeš po stesce tak při vstupu hlavních dvěří 
DLC mám všechny, nějak nevím jak je dát pryč a hrát jen se základní hrou a modifikace jen HDtexturpack

<img src='https://i.imgur.com/OJru2wN.jpg' />

**Comment by Milhousek** [comment]
![20180107160727_1](https://user-images.githubusercontent.com/34947824/34650762-83ce457e-f3c6-11e7-99a4-1db4eb09c447.jpg)

Musí ti to upravovat nějaké DLC, protože já to mám v češtině.
