### ISSUE TITLE
Překlep v dialogu s Písařem Bratrstva

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#284]
![20180106224046_1](https://user-images.githubusercontent.com/34947824/34644543-e7cf0fc4-f338-11e7-92d8-bf5685d7f33a.jpg)
![20180106224057_1](https://user-images.githubusercontent.com/34947824/34644544-e7f039a6-f338-11e7-9e80-3fda673a409d.jpg)

_Vy_ by mělo být s velký _**V**_, jelikož písař hráči vyká, v důsledku vyšší hodnosti.

**Comment by pavelhoral** [comment]
Velké *v* je mám pocit vyjádření úcty v psaném textu. Nemyslím si, že pro titulky bude tohle pravidlo platit také.

**Comment by Martin005** [comment]
V titulcích u filmů či seriálů se v takovémto případě píše malé _v_. Velké _V_ se má používat pouze v dopisech a jiných textech, kde opravdu chceš vyjádřit úctu.
