### ISSUE TITLE
Překlep v popisu úkolu Postup v učení

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#285]
![20180106230359_1](https://user-images.githubusercontent.com/34947824/34644556-2ac6e824-f339-11e7-9214-8886799edf58.jpg)

Nejedná se o písařku, ale o písaře.

**Comment by Milhousek** [comment]
![20180106224220_1](https://user-images.githubusercontent.com/34947824/34644607-0aa417aa-f33a-11e7-8428-9c68f39e3488.jpg)

Přikládám ještě jeden screen ze stejné mise. 
_Písař bratrstva mi dal místo naší mise_ zní celkem divně. Upravil bych to. Třeba - _Písař bratrstva mi pověděl o místě výkonu naší mise._

**Comment by StoupaJ** [comment]
první věta bohužel --> ve hře jsou texty pro písaře i písařky, ale tyhle questové "Eskortuj..." jsou jen v jedné verzi a nerozlišují pohlaví (což v angličtině problém samozřejmě nebyl).

Tady by mělo jít, stejně jako u podobných questů, o to, že se jedná přímo o naloudování lokace dat do hráčova Pip-Boye. Tak by možná bylo dobrý větu napsat: "Písař bratrstva mi nahrál místo naší mise."
Námitky...?

**Comment by Milhousek** [comment]
![20180110163444_1](https://user-images.githubusercontent.com/34947824/34799122-dd4eb396-f65e-11e7-862e-fb3af3639478.jpg)

Co se týče k té mapě, tak narazil jsem na tohle.

**Comment by Milhousek** [comment]
>Tady by mělo jít, stejně jako u podobných questů, o to, že se jedná přímo o naloudování lokace dat do hráčova Pip-Boye. Tak by možná bylo dobrý větu napsat: "Písař bratrstva mi nahrál místo naší mise."
>
Takže třeba - _Písař bratrstva mi označil místo mise na mé mapě._

**Comment by pavelhoral** [comment]
Malinko jsem ten quest log učesal, i když to je stále dost divoké (ale on je takový trošku i originál).
