### ISSUE TITLE
Překlep v dialogu s Proktorem Quinlanem

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#286]
![20180106222727_1](https://user-images.githubusercontent.com/34947824/34644649-9262229a-f33a-11e7-9812-cb75e18c9b9a.jpg)

_... ve chvíli, kdy vrátíš písaře i s daty._ Myslím, že by bylo lepší nahradit slovo _vrátíš_, slovem _přivedeš_.
A v důsledku toho bych možná i upravil tu druhou větu, jelikož když někoho přivedu, tak je logické, že nebude mrtvý.
Napadlo mě: _Hlídka bude úspěšná, když přivedeš písaře i s daty. Samozřejmě v jednom kuse._

**Comment by pavelhoral** [comment]
Upraveno na:

> Hlídka bude úspěšná ve chvíli, kdy se vrátíš s písařem i s daty.

S tou druhou větou jsem nic nevymyslel.

**Comment by pavelhoral** [comment]
Nevšiml jsem si tvého dobrého návrhu na konci issue... ještě jsem to tedy změnil na:

> Hlídka bude úspěšná, až zpátky přivedeš písaře i s daty. Samozřejmě v jednom kuse.
