### ISSUE TITLE
Ustálení pojmů v dialogu s kapitánem Kellsem.

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#290]
![20180107000154_1](https://user-images.githubusercontent.com/34947824/34645390-68134f34-f34c-11e7-9d1c-f55d76aee097.jpg)
![20180107000155_1](https://user-images.githubusercontent.com/34947824/34645391-702496f6-f34c-11e7-8438-4af42f0cbf89.jpg)

Hráč označí Prydwen jako "_loďku_", ale Kells mu odpoví, že ji nazývá "_lodí_". Bylo by lepší to ustálit, nejspíše na tu _loďku_, aby to bylo více "pobuřující".

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno "loďkou"
