### ISSUE TITLE
Zasvěcenec Clarke hráči tyká.

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#292]
![20180107001431_1](https://user-images.githubusercontent.com/34947824/34645421-6e750768-f34d-11e7-9357-b37dcd9f2d6d.jpg)

Jako zasvěcenec by měl Clarke hráči vykat, jelikož hráč má vyšší hodnost - Rytíř. Zároveň během tohoto úkolu - Duty or Dishonor (Povinnost nebo hanba) - nejdříve tyká, ale když mu řeknete aby si dával pozor s kým mluví, tak následuje dialog, ve kterém se omluví a vyká, bohužel poté opět hráči tyká (později dodám screen). 

Při rozhovoru v Ruinách Bostonského letiště, bych ale vykání zanechal. Je to tam už takové méně formální.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno (tykání - quest může hráč plnit bez hodnosti - většina textů je jednotných)
