### ISSUE TITLE
Rytíř Lucia hráči chvíli vyká a chvíli tyká.

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#293]
![20180107002234_1](https://user-images.githubusercontent.com/34947824/34645474-a6e323b8-f34e-11e7-9028-0c57ebd25002.jpg)
![20180107002108_1](https://user-images.githubusercontent.com/34947824/34645476-a84d6c40-f34e-11e7-806e-48b58d6a0793.jpg)
![20180107002440_1](https://user-images.githubusercontent.com/34947824/34645478-a966e890-f34e-11e7-8baf-fffc9857b9fc.jpg)

Tady bych nechal klidně tykání. 

Edit:
![20180107002806_1](https://user-images.githubusercontent.com/34947824/34645487-0b042888-f34f-11e7-9ea0-c7aa0f3f274c.jpg)
Ještě tady přidávám tohle, jelikož se to týká stejného questu - Duty or Dishonored (Povinnost nebo hanba) a je to součástí rozhovoru s Luciou . Tady bych zaměnil _ztratila jsi_ za _ztratili jste_, ve smyslu že oddělení logistiky ztratilo elektronky.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno (tykání + "ztratili jste")
