### ISSUE TITLE
Zoemu na ponorce vykáme.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#294]
![fallout 4 screenshot 2018 01 03 - 19 15 19 85](https://user-images.githubusercontent.com/22203490/34647555-8ef34cd8-f385-11e7-832d-dbe6656b4893.png)
![fallout 4 screenshot 2018 01 03 - 20 19 14 56](https://user-images.githubusercontent.com/22203490/34647563-907a8710-f385-11e7-828d-79cafaa1332d.png)

**Comment by StoupaJ** [comment]
hoj, tohle není vykání (by v té první větě jinak bylo "Byl jste tu 200 let.").
Ve větách se zase jedná o případ, kdy hráč mluví o celé posádce: ("Tys tu byl i s posádkou 200 let?")...

**Comment by rado-p** [comment]
Aha, no já na to koukal tak, že v těch možnostech otázek/odpovědí je " JAK DLOUHO ČEKÁŠ?"
Buď to jedno nebo druhé je špatně.

**Comment by StoupaJ** [comment]
(d8eb04b) upraveno RNAM (Jak dlouho čekáte?)
