### ISSUE TITLE
Vodka / Láhev od Vodky

### ISSUE THREAD

**Issue by Steedr** [prekladyher/fallout4-cestina#295]
![screenshot6](https://user-images.githubusercontent.com/35104379/34648296-df08c7d6-f397-11e7-9136-29ac496e50f4.png)
![vodka](https://user-images.githubusercontent.com/35104379/34648299-ee9c21f2-f397-11e7-81b2-31e2053929d0.jpg)

Má tam být pouze Vodka, řádek 1F4CF

**Comment by StoupaJ** [comment]
máš to nejspíš nějaký přemodovaný :) Tohle prostě musí být nějakým modem nebo něčím jiným. Ve hře jsou tři druhy láhve+vodky: pouze 1x to je plná láhev a 2x to je prázdná láhev. Lze to poznat i typem -> ALCH vs. MISC
![image](https://user-images.githubusercontent.com/17909494/34649462-28d9d914-f3b0-11e7-8770-ff464cd7c1ef.png)

Schválně jsem si obě "láhve od vodky" teď nahodil přes konzoli:
![schranka](https://user-images.githubusercontent.com/17909494/34649485-9e6df750-f3b0-11e7-9a83-70eb0649e2d6.jpg)
