### ISSUE TITLE
"That's some serious protection" je divně přeložené / Slovo "Vágní"

### ISSUE THREAD

**Issue by ghost** [prekladyher/fallout4-cestina#297]
![screenshot3](https://user-images.githubusercontent.com/35178069/34648880-8170124e-f3a3-11e7-949e-8443e2209b33.png)

Překlad "That's some serious protection" jako "To je něco málo seriózní ochrany" se mi zdá divný. Lepší by bylo "To je celkem seriózní ochrana" a nebo něco podobného.

![screenshot4](https://user-images.githubusercontent.com/35178069/34648894-c4ad6dcc-f3a3-11e7-97c4-6a2b5681d7b4.png)

Slovo "Vágní" je sice slovo s významem, ale není tak často používané. Místo "vágní" bych spíše dal "Nejasný", "Nepřesný".

**Comment by pavelhoral** [comment]
Oboje jsem přepsal:

> V tom se dá už lecos ustát. / Se zbrojí můžeš z vertibirdu urvat rotační kulomet. No a nájezdníky pak pošleš první třídou rovnou do pekla. Kapišto?


> Příliš neurčité / Jo je dost... nic neříkající.
