### ISSUE TITLE
Interpunkce 

### ISSUE THREAD

**Issue by ghost** [prekladyher/fallout4-cestina#298]
![screenshot6](https://user-images.githubusercontent.com/35178069/34648943-c86f57f8-f3a4-11e7-8cc4-460b40a20a86.png)

"Nemám, čeho se chytnout" Ta čárka mi tam přijde zbytečná.

[When Freedom Calls | Dialog s Mámou Murphyovou]

**Comment by Milhousek** [comment]
Ještě lepší by bylo dát _se_ před _čeho_.
  _Nemám se čeho chytnout._

**Comment by pavelhoral** [comment]
Upraveno dle Milhouskova komentáře.
