### ISSUE TITLE
Holopáska "Ahoj miláčku!" + Codsworth mě osluvuje "slečno"

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#3]
Hraju za ženskou, mluví na mě Nate, oslovuje mě v mužském rodě (jsi skvělý, úžasný...).
V první části řekl Nate "maličký", ale myslím, že oslovoval mě, "Honey" - miláčku.

Codsworth mě oslovuje "Miss" - přeloženo asi správně jako slečno, ale zní to vážně divně vzhledem k tomu, že jsem vdaná a mám i dva snubáky :). Možná je problém v tom, že používá britskou angličtinu.

**Comment by ErinaCZ** [comment]
ja bych rekla, ze Nate mluvil se Shaunem.

**Comment by Milhousek** [comment]
![20180117214133_1](https://user-images.githubusercontent.com/34947824/35074855-2d6aa556-fbf0-11e7-82f0-538e86290e71.jpg)

Ne mluví ke své manželce. 
Nate v holopásce mluví k Noře a Nora mluví k Nateovi.

**Comment by pavelhoral** [comment]
Holopásku jsem opravil.
