### ISSUE TITLE
Překlep v popise úkolu Vedení příkladem

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#300]
![20180107130120_1](https://user-images.githubusercontent.com/34947824/34649465-30b563c4-f3b0-11e7-91f3-c421e7e94b04.jpg)

Ve slově _trénink_ je  _**G**_ místo _K_.
Zároveň bych upravil název úkolu - _Vést příkladem._

**Comment by StoupaJ** [comment]
díky za report - "g" tam máme v 10 řádcích - vše bude opraveno

**Comment by Martin005** [comment]
@StoupaJ opravil v rámci (d8eb04b).
