### ISSUE TITLE
Špatný výraz v dialogu s P.A.M

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#301]
![20180107160931_1](https://user-images.githubusercontent.com/34947824/34650780-c122740e-f3c6-11e7-95c2-0bbf1e2d5b41.jpg)

Místo slova _Zpacifikovat_ by bylo asi vhodnější _Zajistit._

**Comment by pavelhoral** [comment]
Upraveno dle návrhu.
