### ISSUE TITLE
Vykání - Kent Connolly

### ISSUE THREAD

**Issue by Steedr** [prekladyher/fallout4-cestina#302]
![screenshot7](https://user-images.githubusercontent.com/35104379/34669946-76387732-f474-11e7-96f7-a1c9a96436dd.png)

Po záchraně Kenta Connollyho hráč v jedné nabídce odpovědí vyká.

**Comment by pavelhoral** [comment]
Již vyřešeno v rámci #272. Bude opraveno v rámci verze 0.9.3.
