### ISSUE TITLE
Velké/malé písmeno

### ISSUE THREAD

**Issue by ghost** [prekladyher/fallout4-cestina#303]
![screenshot10](https://user-images.githubusercontent.com/35178069/34686720-c38d0a6a-f4ac-11e7-998f-927b0bf4a06a.png)

![screenshot11](https://user-images.githubusercontent.com/35178069/34686750-d6c822f4-f4ac-11e7-82c9-8a7e1470003c.png)

Malá chybička mezi "dr." a "Dr."

[Vault 81 | Dr. Penskeová]

**Comment by StoupaJ** [comment]
Hoj, tohle není chyba --> (teď neřeším, že většinou jsou celé texty všude velkým písmem). Ve hře každý začátek textu (tedy nejen věta, ale i označení čehokoli) začíná velkým písmenem --> když na zemi leží "láhev" - bude to zobrazeno jako Láhev s velkým "L". V podstatě to samé máš na tom stejným screenu vlevo nahoře: text "Dokončeno". A jinak pro upřesnění, co se týče konkrétně "dr.": ve Falloutu to značí všeobecné označení, ne konkrétní titul (pro který jsou v češtině zcela jiné zkratky a platí pro to jiná pravidla než v angličtině) - takže dr. je uprostřed věty správně malým... ;)

**Comment by ghost** [comment]
Dobrá, děkuji za vysvětlení :)
