### ISSUE TITLE
Překlepy v dialogu s doktorkou Amariovou.

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#307]
![20180108224136_1](https://user-images.githubusercontent.com/34947824/34697090-c91488c6-f4d1-11e7-9532-91231290be49.jpg)

Bylo by vhodnější dát _**si**_ za **můžeme.**

![20180108224227_1](https://user-images.githubusercontent.com/34947824/34697091-c9593a3e-f4d1-11e7-853d-a64de57cf468.jpg)

Tady mi přijde divné, že se nejdříve mluví o _zpřetrhání synapsí_ a pak o opětovné _stáhnutí_.

![20180108225212_1](https://user-images.githubusercontent.com/34947824/34697092-c98afcb8-f4d1-11e7-8277-b19a20923792.jpg)

_Povinována_ je totální nesmysl. Mělo by tam být _povinna_.

![20180108220103_1](https://user-images.githubusercontent.com/34947824/34697198-58c720fa-f4d2-11e7-996d-83425d486653.jpg)

Ve slově _jakákoli_ bych doplnil _**v**_, přece jen v pozdějším dialogu je už slovo _jakékoliv_, viz. screen výše.

**Comment by Milhousek** [comment]
Dalších pár chyb.
![20180108223421_1](https://user-images.githubusercontent.com/34947824/34698172-05090d34-f4d7-11e7-95fe-8172b219633d.jpg)

Místo - _Jakmile budete připraveni_- by mělo být- _Jakmile budeš připraven_, jelikož doktorka Amariová mluví pouze k hráči.

![20180108223839_1](https://user-images.githubusercontent.com/34947824/34698443-6cdab650-f4d8-11e7-8b48-369c695af93c.jpg)
Nesmyslné věty. Možná něco jako - _Dovil mi tě odtamtud dostat. Hned jakmile budeš připraven._
Originál: Let me pull you out of there. As soon as you're ready...

**Comment by StoupaJ** [comment]
"povinována" rozhodně není nesmysl :)
1) UJC slovník + 2) výtažek z nějakýho zákoníku:
![image](https://user-images.githubusercontent.com/17909494/34701214-2f274a1c-f4e7-11e7-8387-c68442fb6839.png)

**Comment by Milhousek** [comment]
I přesto, že to slovo existuje, bych tam osobně dal _povinna_, zní to lépe.

**Comment by Dumec** [comment]
_Jakmile budeš připraven_ ne, hráč může být ženská... _povinna_ a _povinnována_, za mě je to jedno, divně mi nezní ani jedno (povinnována formálněji + archaičtěji, čili spíš otázka na někoho, kdo překládal hodně doktorky Amariové a dokázal by odpovědět, jestli se to na ni hodí (mně se ale zdálo, že mluví celkem standardně)... _Dovol mi_ a _Nechej mě_ - obojí mi zní, upřímně řečeno, vachrlatě, ale to je u toho anglického výrazu "Let sb. do sth." úplná klasika. Občas si říkám, jestli by nebylo lepší překládat to prostě bez _Let_ (zde Vytáhnu/Dostanu tě odtamtud).

**Comment by pavelhoral** [comment]
Přepsal jsem to víceméně dle návrhů (+ u *jakékoli* jsem dal v celém překladu **v**). U poslední věty jsem se malinko odchýlil od originálu:

> Jsem připravená tě odtamtud vytáhnou... až budeš chtít.
