### ISSUE TITLE
Nick Valentine doktorce Amariové většinu času vyká, ale chvilku tyká.

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#308]
![20180108215252_1](https://user-images.githubusercontent.com/34947824/34697315-ddaf6232-f4d2-11e7-99a1-8262e23d3c7d.jpg)

Místo _jsi_ by mělo být _jste_. Přece jenom v jiných případech Nick doktorce vyká a taktéž doktorka Nickovi.

**Comment by pavelhoral** [comment]
Vykání je chyba.

**Comment by pavelhoral** [comment]
Nakonec jsem upravil texty tak, že Nickovi Irma a Amariová vykají, ale on jim tyká. Jelikož ho obě oslovují *pane Valentine*, tak to moc jinak nešlo. Je tu tedy trošku otočená role, kdy lidé robotovi vykají a on jim tyká :).
