### ISSUE TITLE
V některých případech přidání koncovky -ova/ovi ke jménu Valentine je vypuštěno koncové e ve jméně.

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#309]
![20180108213412_1](https://user-images.githubusercontent.com/34947824/34697901-8661b270-f4d5-11e7-8cec-847b1b4604dc.jpg)
![20180108220240_1](https://user-images.githubusercontent.com/34947824/34697905-8992ed9c-f4d5-11e7-8445-36bb5558917a.jpg)

**Comment by Fluik** [comment]
Tohle klidně sjednotím, ale nejsem si jistá, jak to má být správně.

**Comment by pavelhoral** [comment]
Ve slovníčku je schválený a překontrolovaný výraz "Valentineova detektivní agentura", takže tam to e asi patří. Jinak o té koncovce je zmínka i u pavelhoral/fallout4-preklad#75.

Taky předpokládám, že k tomu bude dohledatelná i diskuze na Skype nebo Discordu.
