### ISSUE TITLE
Překlep - Malcolmův terminál

### ISSUE THREAD

**Issue by Steedr** [prekladyher/fallout4-cestina#315]
![screenshot9](https://user-images.githubusercontent.com/35104379/34723225-061dd088-f54a-11e7-8f54-e2c8dfbd0ae3.png)

Asi by tam mělo být: Po tom, co jsem _to nandal_ tomu hlupákovi.

**Comment by pavelhoral** [comment]
Tohle je správně - http://prirucka.ujc.cas.cz/?slovo=nadat... nicméně mám občas pocit, že nám v týmu překládají lidé z první republiky :D. Takže se nebráním vylepšení na nějaký jiný výraz.

**Comment by MANUS-manww** [comment]
Vynadal...
