### ISSUE TITLE
dialog u otce

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#316]
![20180109165136_1](https://user-images.githubusercontent.com/34834709/34738851-a65fb23e-f57a-11e7-9e88-cce179e9b970.jpg)
QUST: Inst301 (Synth Retention) [000E2058] | DIAL: [00123B85] | Record: INFO - [00123BB2]

chybějící slovo "jsem"
I've dispatched a Courser to Libertalia.

**Comment by Fluik** [comment]
Opraveno v ff63367
