### ISSUE TITLE
Divný popis úkolu Zářící moře

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#322]
![20180109180451_1](https://user-images.githubusercontent.com/34947824/34740690-8f3c39c8-f580-11e7-8937-1e10cd4c069a.jpg)

Popisek by chtěl upravit, není z něj úplně jasné, kam se má hráč s Virgilovou pomocí dostat.

**Comment by MANUS-manww** [comment]
To si myslím že je v poho... - je to popis questu... předtím se setkáš z někým jiným... (BRATRSTVO,ŽELEZNICE) pak ti dá směr...

**Comment by Milhousek** [comment]
Právě, že tento úkol můžeš udělat bez toho aniž by jsi dělal úkoly pro bratrstvo/železnici. K tomuto úkolu se dostaneš celkem rychle, vzhledem k tomu, že to navazuje na úkoly s Nickem Valentinem. 
Osobně vím o co se jedná v tom úkolu, ale bez znalosti kontextu ten popisek celkem nedává smysl.

**Comment by MANUS-manww** [comment]
Pise se tam ze je to vedec Institutu... Tam se musi hrac dostat... Takze porad je to v poho.
