### ISSUE TITLE
Dialog v rámci úkolu Braň osadu

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#323]
![20180109171756_1](https://user-images.githubusercontent.com/34947824/34740978-76f67c06-f581-11e7-88c9-61223cd6a898.jpg)

Druhá část zní celkem divoce.

**Comment by Milhousek** [comment]
Napadlo mě:
_Ocenili bychom, jakoukoliv pomoc s obranou._ 
Jen takový nástřel. Neznám originál, ale tohle mi příjde až moc doslovně přeložené.

**Comment by MANUS-manww** [comment]
Origo:
4159        <Source>We barely held them off the first time... we'd appreciate anything you can do to help us defend ourselves.</Source>
 4160:       <Dest>Poprvé jsme je zadrželi jen ztěží... ocenili bychom vše, co můžeš udělat s pomocí nám se ubránit.</Dest>

**Comment by MANUS-manww** [comment]
@Milhousek Máš pravdu - je to doslova...
