### ISSUE TITLE
Překlep (OUT OF TIME)

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#324]
Mno - (WELL)
![screenshot18](https://user-images.githubusercontent.com/35151787/34741244-460e5d74-f582-11e7-9071-c74541509c3d.png)

**Comment by Martin005** [comment]
[Mno](http://ssjc.ujc.cas.cz/search.php?heslo=mno&sti=38228&where=full_text&hsubstr=no)
