### ISSUE TITLE
Špatný rod

### ISSUE THREAD

**Issue by ghost** [prekladyher/fallout4-cestina#330]
![snimek obrazovky 2](https://user-images.githubusercontent.com/35178069/34782875-42b71a32-f62a-11e7-9db7-59162dfbc71c.png)

Místo mužského rodu se zde objevil ženský.

[Dialog s Bobbym DeLucou | Vault81]

**Comment by Milhousek** [comment]
Tohle už bylo reportováno. Jen je záhadou, že to ve verzi češtiny 0.9.3 není, přitom to Stoupa opravoval, pokud se nepletu.

**Comment by pavelhoral** [comment]
V 0.9.3 je opraveno.
