### ISSUE TITLE
Špatný rod #2

### ISSUE THREAD

**Issue by ghost** [prekladyher/fallout4-cestina#331]
![snimek obrazovky 3](https://user-images.githubusercontent.com/35178069/34783244-610bbf32-f62b-11e7-9f69-265048b67700.png)

Starý Rusty mluví o panu DeLucovi. Pak se zmíní o jeho sestře. "Co se jí týká, je velmi štědrý". V této větě se příčí 2 rody. Věta by měla vypadat následovně: "Co se jí týče, je velmi štědrá."

[Dialog se Starým Rustym | Vault 81]

**Comment by pavelhoral** [comment]
To je blbost... říká, že Bobby je ke své sestře velmi štědrý (právě proto, že dbá na to, aby se jí Rusty věnoval).

**Comment by ghost** [comment]
Tak to se omlouvám. Zřejmě jsem to blbě pochopil..
