### ISSUE TITLE
Překlep v dialogu s McDonough

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#340]
![20180110185047_1](https://user-images.githubusercontent.com/34947824/34796051-9ef15b44-f654-11e7-8c48-7f03de2e35fa.jpg)

Místo _energii_ by bylo asi lepší _elektřinu_ -> _Máme tu obchody, doktory, školy, elektřinu, tekoucí vodu_ 
 ..._

**Comment by Fluik** [comment]
Opraveno v ff63367
