### ISSUE TITLE
Překlep v rozhovoru s Mámou Murphyovou

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#341]
![20180110181252_1](https://user-images.githubusercontent.com/34947824/34797485-cb091c68-f658-11e7-9536-6aca7033e538.jpg)

_Jako_ bych tam vynechal.

**Comment by Milhousek** [comment]
![20180110180849_1](https://user-images.githubusercontent.com/34947824/34799784-72e3fc02-f661-11e7-968d-a1eeee83f1b9.jpg)

_Ne, pane_. - Bylo by to dobré nějak upravit aby to bylo použitelné jak pro mužskou, tak pro ženskou postavu. Napadlo mě něco jako - _Ne, panečku._ (jako když údiv)

**Comment by pavelhoral** [comment]
@Milhousek Ne všechny dialogy jsou sdílené mezi chlapa a ženskou. Proto je důležité tyhle věci testovat i za ženskou.

**Comment by Milhousek** [comment]
Tohle jsem testoval za ženskou.

**Comment by MANUS-manww** [comment]
jj vpoho - opravit...

**Comment by MANUS-manww** [comment]
Jako bych tam nechal...

**Comment by Fluik** [comment]
"Ne, pane" upraveno. Nechávám otevřené, kvůli tomu prvnímu screenu.

**Comment by Fluik** [comment]
První screen upraven, zní mi to líp bez toho "jako".
