### ISSUE TITLE
Načítání holopásky - Dvě mezery

### ISSUE THREAD

**Issue by Martin005** [prekladyher/fallout4-cestina#35]
sPleaseWaitHolotape - V původním "Loading holotape.  Please wait..." jsou dvě mezery mezi tečkou a "Please" stejně tak jako v překladu. Nebylo by lepší tam dát pouze jednu mezeru?

![screenshot10](https://cloud.githubusercontent.com/assets/10096404/19872000/deceb972-9fb7-11e6-9bb9-a1e984ee6796.png)

**Comment by pavelhoral** [comment]
Odstranil jsem dvojité mezery všude, kde jsem na ně narazil... *když se kácí les, musí lítat třísky*.
