### ISSUE TITLE
Chyby v dialogu s Nickem Valentinem

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#351]
![20180112001726_1](https://user-images.githubusercontent.com/34947824/34854220-99a46dcc-f738-11e7-8bdd-80feb1e59e1e.jpg)
Tady by mělo být - _jako t**i** skvěl**í** syntetici_.

![20180112002355_1](https://user-images.githubusercontent.com/34947824/34854222-9d63609e-f738-11e7-9c68-005e524da9d3.jpg)
Tady by mělo být - _mechanik se na **mě** dokonce podíval_.

![20180112002750_1](https://user-images.githubusercontent.com/34947824/34854223-9f15e4c0-f738-11e7-9487-2fb35d584007.jpg)

_Policajta_ bych zaměnil za _policistu,_ jelikož Nick se má vyjadřovat spisovně.

**Comment by Milhousek** [comment]
![20180113015554_1](https://user-images.githubusercontent.com/34947824/34901264-5b7b585a-f808-11e7-8cbc-8525e11e6971.jpg)

Jednou je _cop_ přeložen jako policajt, podruhé jako polda.

**Comment by Fluik** [comment]
Že jednou řekne policajt jednou polda bych neřešila. Ty určitě taky nepoužíváš vždy přesně stejný slovo pro jednu věc. (Pokud se teda nedomluvíme, že mluví ultraslušně a řekl by jen "policista", ale to mi na něj nesedí.)

**Comment by Fluik** [comment]
První dva screeny opraveny. Policajta/poldu nechávám - v originále je cop a to neodpovídá policistovi.
