### ISSUE TITLE
Chyba v termnálu Piper

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#353]
![20180112005302_1](https://user-images.githubusercontent.com/34947824/34854667-580b16a6-f73b-11e7-89b9-dcfeeb1c7c11.jpg)

Druhý odstavec - Přiběhly stráže, začaly pálit, ...
Zaměnil bych to - Přiběhla stráž, začala pálit, ... nakonec ho stráž dostala.

**Comment by Perunko** [comment]
Čo sa jej článkov týka, chyba je aj na poslednej strane tretieho dielu Pohľad z vaultu, minimálne pri mojom interview. "MJe potřeba udržet nadeji".

**Comment by Milhousek** [comment]
@Perunko Tu chybu jsem tu už hlásil a už je opravena.

**Comment by Milhousek** [comment]
Vzhledem k tomu, že v Diamond city je _ostraha_, tak by se možná mohlo použít _Ostraha_ místo _stráže_?
