### ISSUE TITLE
Rozhovor s Abraham-em Finch-em (out of the fire)

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#356]
![screenshot54](https://user-images.githubusercontent.com/35151787/34887094-99890662-f7c5-11e7-8d4c-57d7b0bc340e.png)
![screenshot56](https://user-images.githubusercontent.com/35151787/34887102-9fcc2338-f7c5-11e7-987d-864e6f0515be.png)
![screenshot55](https://user-images.githubusercontent.com/35151787/34887108-a5458476-f7c5-11e7-9527-9d4504c0fa87.png)

Když Finchovi vracím ten meč (říkám že už ho mám) a on odpoví uděláš to? - nevím co je v originále,ale rozhodně to chce předělat.

**Comment by Fluik** [comment]
Opraveno v ff63367
