### ISSUE TITLE
Rozhovor s Roger Warwick,osada Wawrickova usedlost (Greenskins)

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#357]
![screenshot60](https://user-images.githubusercontent.com/35151787/34894043-18c91c90-f7e0-11e7-831c-dbe77034486e.png)

Bývali to Minutemani - Dal bych - _Byli to Minutemani_ nebo spíše - _Bývali tu Minutemani_...

**Comment by Milhousek** [comment]
Nevidím na tom nic divného. Říka, že kdysi by to byli minutemani, kdo by jim pomohl. Takže slovíčko _bývali_ mi přijde v pohodě.

**Comment by MANUS-manww** [comment]
Pak ale říká hráč že Minutemani jsou zpět - (Garvey na začátku říká že s Minutemanů zbyl jen on...) Proto to slovo _tu..._

**Comment by Fluik** [comment]
Tady bych řekla, že není co opravovat. A věta "Bývali tu Minutemani, kdo by nám pomohl" podle mě nedává smysl.

**Comment by MANUS-manww** [comment]
Je to v pohodě - closed
