### ISSUE TITLE
Codsworth

### ISSUE THREAD

**Issue by maarten93** [prekladyher/fallout4-cestina#358]
![obrazek](https://user-images.githubusercontent.com/2012726/34897501-8c0f3014-f7ee-11e7-9eb1-ee4ae69e341c.png)

https://idioms.thefreedictionary.com/As+I+live+and+breathe!

**Comment by MANUS-manww** [comment]
A problém?

**Comment by pavelhoral** [comment]
https://kontext.korpus.cz/view?ctxattrs=word&pcq_pos_neg_intercorp_v10_cs=pos&attr_vmode=visible&pagesize=40&align=intercorp_v10_cs&q=~ie7yuDEe63&viewmode=align&attrs=word&corpname=intercorp_v10_en&refs=%3Ddoc.id&attr_allpos=kw&maincorp=intercorp_v10_en

Asi bychom z toho mohli udělat něco ve stylu *Mě snad šálí zrak* / *No to se mi snad zdá* / ...
