### ISSUE TITLE
Chybějící "t" loutka

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#360]
![inkedfallout 4 screenshot 2018 01 12 - 23 09 58 06_li](https://user-images.githubusercontent.com/22203490/34897474-6f37b614-f7ee-11e7-9429-ae39af4af6d5.jpg)

**Comment by StoupaJ** [comment]
máš neaktuální verzi češtiny! --> je 0.9.3

**Comment by pavelhoral** [comment]
Tohle bylo opravené v rámci #203.
