### ISSUE TITLE
Popis úkolu Palebná podpora + Volání do zbraně

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#365]
![20180112211816_1](https://user-images.githubusercontent.com/34947824/34901312-1c762120-f809-11e7-8deb-d0a438badd56.jpg)
_Po rozhovoru s paladinem Dansem, jsem přijal jeho nabídku a přidal se k Bratrstvu oceli_. - Např. tohle zní rozhodně lépe než momentální popisek

![20180112211842_1](https://user-images.githubusercontent.com/34947824/34901317-26a8c1ca-f809-11e7-8324-29a454526619.jpg)

_Nabídku, abych se přidal k Bratrstvu oceli, jsem přijal_. - To samé.

**Comment by pavelhoral** [comment]
Souhlasím, že současný popisek je hrozný. Místo něj je ale potřeba vymyslet bezpohlavní variantu :)... s tím si ale nějak poradíme (není potřeba vymýšlet návrhy - odhalení nesmyslu je pro chybu dostačující).
