### ISSUE TITLE
Extrakce ze vzpomínky"Chybí "tě"

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#370]
![amariova extrakce ze vzpominky](https://user-images.githubusercontent.com/22203490/34904886-bcca7d3e-f84e-11e7-8614-dbf3b1f5c61b.JPG)

**Comment by Milhousek** [comment]
Tohle jsem již reportoval v issue #307

**Comment by pavelhoral** [comment]
Zavírám jako duplikát.
