### ISSUE TITLE
Překlep v dialogu hráče s Desdemonou

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#379]
![20180112125818_1](https://user-images.githubusercontent.com/34947824/34905612-0f7e65aa-f85d-11e7-8c08-55619c394050.jpg)

Mělo by tam být - _Potřeboval jsem lovcův čip._

**Comment by Fluik** [comment]
Tady je jiný čas kvůli tomu, aby to byla bezpohlavní varianta. Otázka je jestli to tam takhle vůbec nedává smysl nebo ti jen nedošlo, že to musí bejt bezpohlavní :)

**Comment by Milhousek** [comment]
Jde o to, že se jedná o rozhovor kdy se baví proč hráč šel po Lovci z Institutu, tím pádem hráč odpovídá v minulém čase. Takže tady věta _Potřebuju lovcův čip_ je nesmyslná, protože ho už dávno má.
