### ISSUE TITLE
úpravna vod Weston-terminály

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#38]
Prakticky ve všech terminálech na tomto místě se vyskytuje zvláštní formulace..Westonská "zdravá"mediální udalost.
Jako jak "zdravá"? O zdraví?
Je to vždy pod hlavičkou: Westonská mediální událost.

**Comment by pavelhoral** [comment]
Terminál Westonské úpravny vody jsem upravil. Mám to tam jako *Mediální událost Westonská studnice zdraví*. Více viz diskuze na Discordu.
