### ISSUE TITLE
Chyby v dialogu s Dohlížitelem Zeleným

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#382]
![20180113132918_1](https://user-images.githubusercontent.com/34947824/34908765-65219102-f895-11e7-8140-9c3caa7381a1.jpg)
![20180113133106_1](https://user-images.githubusercontent.com/34947824/34908767-655dc00a-f895-11e7-8ec3-690f8a36b5ef.jpg)
![20180113133329_1](https://user-images.githubusercontent.com/34947824/34908781-9bdfc84e-f895-11e7-801a-a96e9396a2ad.jpg)

Všude je psáno **V**ám, **V**ás, **V**ámi apod. 
Týká se to celého rozhovoru ohledně "soutěže", ale nechci tu dávat tolik screenů, 3 bohatě stačí.

**Comment by Fluik** [comment]
Založená hromadná issue na velká písmena ve vykání #717 , takže zavírám.
