### ISSUE TITLE
Brnění Stříbrného Rubáše

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#384]
![20180113155038_1](https://user-images.githubusercontent.com/34947824/34908913-5334907c-f898-11e7-9049-5a2682685446.jpg)

_Brnění_ bych zaměnil za _Oblek_.

**Comment by Milhousek** [comment]
Nejdříve je to kostým Stříbrného Rubáše, poté je vylepšen na Brnění Stříbrného Rubáše, ale i přesto bych to upravil. Přece jen je to stále kostým/oblek, takže by mohlo klidně být Obrněný kostým Stříbrného Rubáše.

**Comment by Milhousek** [comment]
Všiml jsem si, že to tu už zakládat @StoupaJ v issue #140

**Comment by pavelhoral** [comment]
Pak tohle nedává smysl držet otevřené.
