### ISSUE TITLE
překlep Wilhelmína Cabotová

### ISSUE THREAD

**Issue by Paynex** [prekladyher/fallout4-cestina#388]
![screenshot0](https://user-images.githubusercontent.com/35418988/34914394-7d6a5618-f912-11e7-8ff6-919a94e82e04.png)

**Comment by MANUS-manww** [comment]
To nebude chyba - zřejmě mluví nespisovně...

**Comment by Paynex** [comment]
mluvila o svem manželovi tak nevím :)

**Comment by pavelhoral** [comment]
Je dobré u chyb uvádět, kde člověk vidí tu chybu. Z prostého označení *překlep* nemusí být všem jasné, o co jde. Tedy - jde ti o "**chtěj** mě", nebo o to, že tam má být "chtějí **ho**"?

**Comment by Paynex** [comment]
chtě**l** (místo chtěj) mě zabít. Nás vsechny... .... aspoň tak bych to pochopil z konextu

**Comment by pavelhoral** [comment]
Aha, to dává smysl :)... já myslel, že tam mělo být "chtějí mě zabít". Nedošlo mi, že mluví o Lorenzovi.

**Comment by Paynex** [comment]
v pohodě :)

**Comment by MANUS-manww** [comment]
Taky jsem to tak pochopil (chtěj) - vždy to chce konkrétní popis chyby...

**Comment by Paynex** [comment]
jasně, jasně se přístě polepším :D

**Comment by Fluik** [comment]
Opraveno v ff63367
