### ISSUE TITLE
Chyby u <Alias...> - špatně vyskloňované názvy

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#39]
Najdi senzor toku v "nádrž" ( i ) na Kaštanovém Návrší.
Vypadlo i

**Comment by pavelhoral** [comment]
Přepsal jsem velkou část textů s aliasy. Bohužel až na konci mě napadlo se podívat, jak to řeší třeba v polském překladu. Tam si dost pomohli tím, že aliasy u radiant questů dávali před dvojtečku na začátek věty... někdy v budoucnu bych to klidně udělal i u nás, nicméně pro teď považuji bug za vyřešený.
