### ISSUE TITLE
špatný rod v rozhovour o zbrani co dostaneš od cabota

### ISSUE THREAD

**Issue by Paynex** [prekladyher/fallout4-cestina#394]
hraju za chlapa :) tzn "nejsem si jistý"
![cabot](https://user-images.githubusercontent.com/35418988/34916346-4aa7847e-f937-11e7-9458-3302af600b5a.png)

**Comment by Milhousek** [comment]
Máš opravdu nejnovější verzi češtiny (0.9.3)? Tahle chyba už byla opravena.
Viz. Issue #276

**Comment by pavelhoral** [comment]
Zavírám jako duplikát.

**Comment by Paynex** [comment]
aha omlouvam se nevsiml jsem si že vyšla nová verze
