### ISSUE TITLE
Rozhovor s Deaconem-"práce"

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#396]
![vystrizek](https://user-images.githubusercontent.com/22203490/34918543-44d29990-f954-11e7-8f59-3bdd520e04b9.JPG)

**Comment by rado-p** [comment]
![zrovna prevlek](https://user-images.githubusercontent.com/22203490/34918604-6ed7d178-f955-11e7-8def-bfe3a609c320.JPG)

Tady bych dal spíš "To není zrovna převlek" Naráží na to, že si Deacon chtěl změnit obličej. Odpověď Deacona je pak " Převlek nejsou jenom hadry a klobouk" nebo tak nějak.

**Comment by MANUS-manww** [comment]
Scr. 2 už jsem založil...

**Comment by rado-p** [comment]
Tohle jsem tam nenašel.

**Comment by Fluik** [comment]
Opraveno v ff63367
