### ISSUE TITLE
NEJDE SPUSTIT

### ISSUE THREAD

**Issue by PATRIK777CZ** [prekladyher/fallout4-cestina#400]
Nainstaluju game, zkušebně spůstím, jede to v cajku v originálu. nakopíruju data češtiny podle návodu (easy) a pak už nejde spustit :( - nějaká rada?

**Comment by Fluik** [comment]
Hlášení chyb na Githubu slouží pouze pro hlášení chyb v překladu. Pokud máš problém se spuštěním, ozvi se na Discordu a hlavně víc popiš svůj problém - z informace "nejde spustit" se nic moc poznat nedá.
