### ISSUE TITLE
Dialog s Ednou - Vy, Vaši, Vaše, ...

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#401]
![20180113195727_1](https://user-images.githubusercontent.com/34947824/34922636-f18437f0-f992-11e7-97d2-00df599eca9d.jpg)
![20180113195813_1](https://user-images.githubusercontent.com/34947824/34922637-f1a56a56-f992-11e7-9fcc-27bb1473da7a.jpg)
![20180113195939_1](https://user-images.githubusercontent.com/34947824/34922639-f1e3a29e-f992-11e7-9970-43cf5bc35484.jpg)

Edna hráči vyká, ale v dialozích je psáno **V**ám, **V**aši, **V**ás atd. s velkým **V**.

**Comment by Fluik** [comment]
Založená hromadná issue na tenhle problém #717 , zavírám.
