### ISSUE TITLE
Rytíř Lucia - osobní záznamy

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#405]
![20180114235641_1](https://user-images.githubusercontent.com/34947824/34923245-819f44e0-f99a-11e7-9e12-5039f70a6ab1.jpg)
_Zítra ráno_ jednou přebývá.

![20180114235728_1](https://user-images.githubusercontent.com/34947824/34923246-81bd5e30-f99a-11e7-895a-b16765bb9f9c.jpg)
_Starším_ by asi mělo být velké **S**, protože se jedná o Staršího Maxona.
_Ale ne Clarke_ -> _Ale Clarke ne._
_Nikdo nevěděl, kde je. -> Nikdo nevěděl, kde byl._

![20180114235822_1](https://user-images.githubusercontent.com/34947824/34923247-81dab14c-f99a-11e7-9188-cd036ff6fe48.jpg)
Mělo by tam být - _Když už se mnou vůbec **ne**mluví._

**Comment by Fluik** [comment]
Starší je hodnost, takže určitě malé "S". Opravím to i jinde.
