### ISSUE TITLE
VDSG 9700

### ISSUE THREAD

**Issue by maarten93** [prekladyher/fallout4-cestina#407]
![image](https://user-images.githubusercontent.com/2012726/34939000-8e935f24-f9ea-11e7-91ea-90424c690192.png)

Vypustil bych to poškození před radiací.

**Comment by Milhousek** [comment]
Neni pro to důvod, tohle tam zcela určitě patří.

**Comment by maarten93** [comment]
jen mi přijde zbytečné to tam mít dvakrát.

**Comment by Milhousek** [comment]
Jo, ty myslíš jenom to slovíčko _poškození_, to by se tam mohlo klidně vynechat no.
