### ISSUE TITLE
Do Sedla

### ISSUE THREAD

**Issue by maarten93** [prekladyher/fallout4-cestina#409]
https://snag.gy/t6fbGi.jpg

Jen návrh co místo Do Sedla nechat Saddle Up, hodně názvů zahraničních firem se nepřekládá (Amazon, Apple, Canon.....)

**Comment by pavelhoral** [comment]
Ve světě Falloutu se ale většina značek překládá (*Tlačenice*, *Rozmarný mladík*, ...). Nejde o zažité názvy mezinárodních firem a často jde o celkem úsměvné názvy. Navíc naše pravidlo zní - překládat vše, co překládat jde a nezní blbě.
