### ISSUE TITLE
Dialog Daisy po vyčištění knihovny

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#424]
![20180115235840_1](https://user-images.githubusercontent.com/34834709/34991930-a8b661ee-facb-11e7-9703-ef9df7c6e427.jpg)
V druhé větě nějak postrádám předmět.

**Comment by Fluik** [comment]
Já osobně tam problém teda nevidím.

**Comment by MANUS-manww** [comment]
Taky ne...

**Comment by Milhousek** [comment]
Asi by se dalo přidat _těch_  - Podařilo se ti zbavit **těch** supermutantů.
Ale osobně si myslí, že i takhle je to v pořádku a nechybí tam nic co by dělalo problém s pochopením věty.
