### ISSUE TITLE
Ostraha Diamond City vyká poté co zabije Kyle-a

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#428]
![20180116134149_1](https://user-images.githubusercontent.com/34947824/34997499-ec359c08-fadc-11e7-9e43-8b73d2a5b793.jpg)

**Comment by MANUS-manww** [comment]
Ve scr. vidím že vyká...

**Comment by Milhousek** [comment]
Jop, moje chyba, špatný název issue.
