### ISSUE TITLE
Dialog s Jakem Finchem 

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#431]
![20180116212401_1](https://user-images.githubusercontent.com/34947824/35012140-ef73d49e-fb08-11e7-9b2f-fe29308923d0.jpg)

Myslím, že by tam mělo být _meč mého pradědečka._

**Comment by MANUS-manww** [comment]
Ne,mluví o dědečkovi - To říká i jeho otec Abraham - (říká Grandfather)
![20180116220851_1](https://user-images.githubusercontent.com/35151787/35012590-8d4abd76-fb0a-11e7-84e6-28a172470057.jpg
Kontroluji to znova...

**Comment by Milhousek** [comment]
Právě že Abrham mluví o svém dědečkovi, tím pádem je to Jakeův pradědeček, 
A pokud se nepletu tak Jake říká great-granddad.

**Comment by pavelhoral** [comment]
*Great grandfather* jako *úžasný dědeček* :D

**Comment by MANUS-manww** [comment]
Jj - sry Abe mluví Grandfather - tudíž ok issue.

**Comment by MANUS-manww** [comment]
Sjel se tu misi - tohle jem přehlédl... asi 20x load... Jen v tomhle rozhovoru.
Proto je good,aby to projelo více lidí.

**Comment by MANUS-manww** [comment]
To jsem se k***a přehlíd - přepracování... Ale nechám koment pro založení nového štítku...

**Comment by Milhousek** [comment]
Přikládám stejnou chybu - Jackova holpáska
![20180117215500_1](https://user-images.githubusercontent.com/34947824/35075666-bddb5cda-fbf4-11e7-8769-a905ac6ff071.jpg)
