### ISSUE TITLE
Kincaidův terminál v továrně General Atomics

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#432]
![20180116200643_1](https://user-images.githubusercontent.com/34947824/35012177-2bf303ae-fb09-11e7-9999-1dfbeb41711c.jpg)

**V**áš přesun ... Ujišťujeme **V**ás ... z **V**aší strany ... **V**aše služby

**Comment by Fluik** [comment]
Na velké V je založená issue #717, i když teda v terminálech by to snad mělo být ok.
