### ISSUE TITLE
Holopáska det. McDonnella

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#438]
![20180117131429_1](https://user-images.githubusercontent.com/34947824/35046346-fdbdf4ec-fb96-11e7-814c-14a865a003c0.jpg)

Tech chlápek -> te**n** chlápek

**Comment by Milhousek** [comment]
![20180117131418_1](https://user-images.githubusercontent.com/34947824/35046515-7cc89666-fb97-11e7-917f-8b38c6d758e1.jpg)

Ještě jedna chybka - dokonce na mě **ten** mamrd vytasil  zbraň.

**Comment by Fluik** [comment]
Na tom druhým screenu se mi spíš zdá divný to "přichytil" než, že by tam chybělo "ten" :D

**Comment by Milhousek** [comment]
No, dalo by se to zaměnit za _přistihl_ nebo _chytnul_.

**Comment by Milhousek** [comment]
Ještě taková poznámka k prvnímu screenu. Asi bych to rozdělil alespoň na 2 věty, tolik čárek ve větě nevypadá přívětivě.
