### ISSUE TITLE
Cruzova holopáska

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#439]
![20180117130847_1](https://user-images.githubusercontent.com/34947824/35046641-e1087916-fb97-11e7-9b65-b4aec7fb1f3e.jpg)

_Houfují_ bych zaměnil např. za _shromažďují._

**Comment by Fluik** [comment]
~~A já bych to klidně nechala, jestli si dobře pamatuju, tak v domě Fallon jsou ghúlové ne? K nim se mi to houfování nezdá špatné.~~ 
Tak kecám, prej supermutanti, tak to opravím.
