### ISSUE TITLE
úprava výrazu v Textu projevu

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#459]
![20180117234704_1](https://user-images.githubusercontent.com/34947824/35100481-3e2a4740-fc5c-11e7-87be-6c90933fc0bd.jpg)

_Neuposlechnutí žádosti bude mít **katastrofální následky**_ - by tam bylo lepší.

**Comment by pavelhoral** [comment]
To si nemyslím... *katastrofální následky* chápu jako obecnou hrozbu pro komunitu / prostředí, *fatální důsledky* pak chápu jako hrozbu osobní likvidací.

**Comment by Fluik** [comment]
Souhlasím s Palkem, nikdo jinej se k tomu stejně už nevyjádří, takže zavírám.
