### ISSUE TITLE
Chybí písmeno v dialogu s Virgilem

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#463]
![20180118192820_1](https://user-images.githubusercontent.com/34947824/35117776-feb7bb22-fc8f-11e7-99e8-bd6e5b1d9ced.jpg)

dokážet**e**.

**Comment by MANUS-manww** [comment]
Nebo tam má být - _dokážeš to sestrojit?_

**Comment by Milhousek** [comment]
Ne, mylí tím jestli to dokážeš sestrojit s někým dalším (bratrstvo, železnice, minutemani), takže _dokážete_

**Comment by MANUS-manww** [comment]
je to myšleno v mn. čísle? - neznám org...

**Comment by Milhousek** [comment]
V angličtině používají stejný výraz pro _ty_ a _vy_ - _you_. Ale vzhledem k tomu jak se Virgil zakoktal po první větě, tak myslel _you_ jako vy. Předtím se ještě ptá kdo ti pomohl dešifrovat lovcův čip, takže už počítá s tím, že ti někdo pomáhá.

**Comment by MANUS-manww** [comment]
Tak OK.Podle kontextu před...
