### ISSUE TITLE
Diamond City - prodejce SURPLUS

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#472]
![20180118231428_1](https://user-images.githubusercontent.com/35151787/35124708-5e928588-fca7-11e7-896b-fd43d1d50d61.jpg)

Tady by to chtělo doplnit slovo _to_ nebo _tu_.

**Comment by Milhousek** [comment]
Mně to příjde v pohodě.

**Comment by MANUS-manww** [comment]
nechybí tam předmět?

**Comment by Fluik** [comment]
Za mě taky v pohodě, zavírám.
