### ISSUE TITLE
Terminály - stop páska

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#480]
![20180120163627_1](https://user-images.githubusercontent.com/34947824/35187028-c5abb394-fe1d-11e7-94d7-bc8b2e752d0a.jpg)

Na tuhle chybu jsem narazil konkrétně u _terminálu starosty_ a _Jacquelinina terminálu_ (Univerzitní bod)

**Comment by MANUS-manww** [comment]
Tato chyba se vyskytuje u všech holopásek,které se přehrávají na terminálech... .

noinfo-edids-33.xml:
 2986        <REC>GMST:DATA</REC>
 2987        <Source>Stop Tape</Source>
 2988:       <Dest>Stop páska</Dest>
 2989      </String>
 2990      <String List="0" sID="035A61">
