### ISSUE TITLE
Cestina pro VR verzi

### ISSUE THREAD

**Issue by Konycz** [prekladyher/fallout4-cestina#488]
Hoj, chtel jsem pozadat o presny postup instalace cestiny pro VR verzi. Mam Fallout 4 VR ze steamu (original) a nikde ve slozce jsem nenasel soubory podobne tem co obsahuje cestina. Diky moc

**Comment by Milhousek** [comment]
Přijď na náš [Discord](https://discordapp.com/invite/rUxYwwp), takové věci na Githubu neřešíme.
