### ISSUE TITLE
Špatně vyskloňované příd. jméno "Geigerovu"

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#489]
![gingerovu](https://user-images.githubusercontent.com/22203490/35195826-5f2e9166-fec9-11e7-900b-4279a1ff6e09.JPG)

**Comment by Milhousek** [comment]
Neřekl bych, že je to špatně vyskloňované.

**Comment by rado-p** [comment]
3 pád ? Ne 4 pád? "Geigerova počítači"

**Comment by cert23** [comment]
Jak bys tam chtel dat 4 pad? Jsi tady kvuli koho co? Urcite tam ma byt 3 pad. Jsi tady kvuli komu cemu.

**Comment by StoupaJ** [comment]
Jsi tu kvůli "komu čemu" --> je to dobře...
