### ISSUE TITLE
Dialog s doktorkou Amariovou - moc čárek ve větě

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#492]
![20180121230658_1](https://user-images.githubusercontent.com/34947824/35200013-ecfc6d0a-ff06-11e7-9bea-8a63af613369.jpg)

Myslím, že je tam moc čárek, tím pádem to nevypadá moc dobře a na čtení to taky není ono.

**Comment by StoupaJ** [comment]
no pravopisně to je ale dobře - podřadicí spojka, oslovení, vedlejší věta... Jediná možnost je, že by to nebylo psáno jako konkrétní oslovení směřované na lidi: "Myslela jsem, že si lidé více cení opatrnosti."

**Comment by Milhousek** [comment]
No řekl bych, že Amariová mluví obecně o členech Železnice. Baví se totiž o plánu, který vymyslela Železnice, pro přesun Syntetika z Hnízdečka vzpomínek.
Možná by tedy stačilo jen _- To je plán? Myslela jsem si, že si více ceníte opatrnosti._
