### ISSUE TITLE
Rozhovor s Travis-em (Confidence Man)

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#499]
![20180121130219_1](https://user-images.githubusercontent.com/35151787/35288535-39e4b32a-0065-11e8-8df1-ddf552ce06f0.jpg)

Myslím že po slově "ztratil" má být čárka.
Mít dvaktrát slovo v jedné větě - moc nezní (změnil bych - "nebo co" na _či co_).
A poslední věta by měla být - "Tak _ti_ ho pomůžu" (nebo lépe _pomohu_)

**Comment by Fluik** [comment]
"Tak ti ho pomůžu" je opravené, zbytek nechávám. Čárka tam být podle mě nemá a zdá se mi divný, aby člověk použil v konverzaci jednou "nebo" a pak hned "či".

**Comment by MANUS-manww** [comment]
OK nech ,ale tu poslední větu změň na (Tak ti ho pomohu dostat zpátky)
