### ISSUE TITLE
Nepřeložené názvy účesů.

### ISSUE THREAD

**Issue by rado-p** [prekladyher/fallout4-cestina#5]
Nepřeložené názvy účesů.
![fallout 4 10 12 2016 - 17 11 16 01](https://cloud.githubusercontent.com/assets/22203490/19321866/01535148-90b7-11e6-88ad-bf4abf8d98a7.png)
![fallout 4 10 12 2016 - 17 11 45 02](https://cloud.githubusercontent.com/assets/22203490/19321867/0155d2e2-90b7-11e6-9c72-3e30965e2d9a.png)

**Comment by pavelhoral** [comment]
*Miss Noir* jsem nasprosto změnil na *Film noir*, neboť si jsem na 99,99 % jistý, že jde o narážku na [tenhle pojem](https://cs.wikipedia.org/wiki/Film_noir). Pokud bychom kombinovali jako *Slečna noir*, tak by to nebylo tak zřejmé.
