### ISSUE TITLE
Dopis pro Coryho

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#512]
![20180126210136_1](https://user-images.githubusercontent.com/34947824/35472758-70c9658a-0375-11e8-9684-751c6a908709.jpg)

Poslední věta je, podle mého, nesmyslná - nevím o čem je řeč,

**Comment by StoupaJ** [comment]
já to teda pochopil... :) Jinými slovy:
"Řekni, že tě posílám já. Ale řekni, že tě posílá Klikový Hřídel. Pod mým starým jménem Melvin mě tu nikdo nezná."
