### ISSUE TITLE
Terminál ředitele - J. Elwood

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#516]
![20180126222011_1](https://user-images.githubusercontent.com/34947824/35475561-f2fe1804-03a0-11e8-8696-67fb8cd07aa9.jpg)

_On nám zamknul přístup_, myslím že to nezní moc dobře.

**Comment by MANUS-manww** [comment]
Záleží jak je to v origo... - jinak bych dal _znemožnil_,nebo _uzavřel_.
