### ISSUE TITLE
Gaussova puška - komenzátor

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#523]
překlep - chybějící písmenko - kom**p**enzátor

**Comment by MANUS-manww** [comment]
Máš scr...?

**Comment by pavelhoral** [comment]
Tohle najdeme... (resp. už jsem to našel).

![image](https://user-images.githubusercontent.com/2012726/35485081-51acb860-045a-11e8-8bcd-022cea999cbe.png)

**Comment by MANUS-manww** [comment]
Ověřím to...

**Comment by MANUS-manww** [comment]
![20180128184807_1](https://user-images.githubusercontent.com/35151787/35485180-ee72e858-045b-11e8-9f3e-0abf00f0e5bc.jpg)

Tohle jsem našel...

**Comment by pavelhoral** [comment]
Miscmod jsou předměty v inventáři (tzn. když modifikaci vytvoříš, ale nedáš ji na zbraň)...

**Comment by MANUS-manww** [comment]
Jasná chyba v překladu..

**Comment by Fluik** [comment]
Koukala jsem, že už je opraveno, takže zavírám.
