### ISSUE TITLE
Otevírání zámku.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#525]
![20180129222205_1](https://user-images.githubusercontent.com/35151787/35590845-55e84570-0608-11e8-95ba-839c69770ab2.jpg)

Asi vynechat (si myslím,že) 
Prostě  - _Tohle neotevřu_.

**Comment by Milhousek** [comment]
Stačilo by upravit slovosled.
_Myslím, že tohle neotevřu._

**Comment by MANUS-manww** [comment]
Mám pocit že to říká prostě - A nejde to ani zkusit vyháčkovat.

**Comment by Milhousek** [comment]
Pokud na daný zámek nemáš požadovanou úroveň perku, tak ti hra ani nedovolí aby jsi zámek zkusil otevřít.

**Comment by MANUS-manww** [comment]
Ale neříká I think...

**Comment by pavelhoral** [comment]
```
    <String List="2" sID="029402">
      <EDID>PlayerLockedShared02</EDID>
      <REC>INFO:NAM1</REC>
      <Source>Don't think I can pick this...</Source>
      <Dest>Tohle si myslím, že neotevřu...</Dest>
    </String>
```

**Comment by MANUS-manww** [comment]
Má více komentářů... Closed.
