### ISSUE TITLE
Quest The Disappearing Act [Zmizení] 2

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#530]
![20180131181210_1](https://user-images.githubusercontent.com/35151787/35637076-669ea3fe-06b3-11e8-91dc-79b7692da9b3.jpg)

Určení místa - _tady dole._
Vzhledem k tomu že tady jsme.

**Comment by Milhousek** [comment]
Tato chyba uz je nahlasena viz. #349
Zaviram jako duplikat

**Comment by MANUS-manww** [comment]
Nevšiml jsem si... OK
