### ISSUE TITLE
Čeština mi nefunguje :/

### ISSUE THREAD

**Issue by Bulderoid** [prekladyher/fallout4-cestina#532]
Zkoušel sem prvně manuální. Udělal jsem vše podle návodu a nic.
Poté sem zkoušel MSI Instalátor a taky nic..

**Comment by pavelhoral** [comment]
Na základě prostého "nefunguje mi to" nic nepoznáme. Kdyžtak se připoj na Discord, kde se podobné problémy řeší jednodušejí - https://discord.gg/rUxYwwp
