### ISSUE TITLE
HalluCigen Inc. - Očiš(s)ťovač

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#544]
![20180202235741_1](https://user-images.githubusercontent.com/34947824/35759225-96288c54-0878-11e8-9084-5f74d358b951.jpg)
![20180203000250_1](https://user-images.githubusercontent.com/34947824/35759227-9742e51c-0878-11e8-82d7-181712886953.jpg)

Všude se používá pojem _Oči**š**ťovač_, ale v jednom případě je _Oči**s**ťovač._

**Comment by MANUS-manww** [comment]
Taky se mi nezdá slovo (těžce ozářena)-lepší dát _silně_
