### ISSUE TITLE
Instalace Steam

### ISSUE THREAD

**Issue by VlastimilZach** [prekladyher/fallout4-cestina#550]
Nefunguje instalace na steam pokud je steam uložište her na jiném než defaultním umístění. Osobně mám stema hry na disku F a instalátor nemá možnost vybrat  cíl instalace

**Comment by MANUS-manww** [comment]
To je blbost - já mám taky hru FALLOUT4 na jiném disku... a vše funguje . Systém a Steam na C: a hru na B: ...

**Comment by StoupaJ** [comment]
Potvrzuju funkčnost: Mám instalaci Steamu i samotnou hru na D: --> instalátor bez problémů češtinu automaticky nainstaloval...

**Comment by pavelhoral** [comment]
Jen dodám, že instalátor vůbec Steam nezajímá. Instalátor čte umístění instalace Falloutu z registrů, kam lokaci zapisuje hra samotná.

```
<Property Id="INSTALLDIR">
    <RegistrySearch Id="Fallout4Registry" Root="HKLM" Type="directory"
            Key="SOFTWARE\WOW6432Node\Bethesda Softworks\Fallout4" Name="installed path" />
</Property>
<Condition Message="Nebylo možné najít složku Fallout 4.">
    <![CDATA[Installed OR INSTALLDIR]]>
</Condition>
```
