### ISSUE TITLE
Svářený a standardní plát

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#552]
Nájezdnická energozbroj má *Standard Plate* a *Welded Plate* přeložené jako *standardní* a *svářený **plát***. Přijde mi to takové divné... asi bych spíše čekal *standardní* a *svářené **plátování***.

**Comment by pavelhoral** [comment]
V kontextu ostatních modifikací asi není o čem debatovat:

![obrazek](https://user-images.githubusercontent.com/2012726/35817827-b292d6ce-0a9e-11e8-81f6-a0e88daee3d8.png)

Jinak nejedná se jen o MISC, ale i OMOD.

**Comment by Dumec** [comment]
Plate a Plating? ... ale asi to sedí více no.

**Comment by pavelhoral** [comment]
Beru to podle *Plate Armor* ::= *plátová zbroj* a tomu je blíže právě *plátování*, než jen jeden *plát*.

**Comment by pavelhoral** [comment]
Opraveno,.
