### ISSUE TITLE
Nejde hackovat žádný terminál

### ISSUE THREAD

**Issue by PATRIK777CZ** [prekladyher/fallout4-cestina#554]
Ahoj lidi překlad super, ale nejde hekovat žádný terminál. Mám verzi 0.9.4 jsem seknutý u mise, kde mám nahodit engine v továrně s tím borcem z bratrstva oceli, hned na začátku. V terminálu jsou jen znaky a nejsou tam žádná slova, takže každý klik je chyba a nejde nic hekovat. Projel jsem Fallout 3, new wegas, postup hekování znám, ale tady jde fakt o error a v úkolech nejde pokračovat.

Screeny níže

![bez nazvu 1 kopie 2](https://user-images.githubusercontent.com/35434285/35857992-18775a40-0b3b-11e8-8217-fdf0e7743bf2.JPG)

![bez nazvu 1 kopie](https://user-images.githubusercontent.com/35434285/35857993-18a2c5fe-0b3b-11e8-998b-b46299839b98.JPG)

**Comment by pavelhoral** [comment]
Díky za nahlášení. Takhle se screenem je to dobře vidět... večer se na to podívám.

**Comment by pavelhoral** [comment]
@PATRIK777CZ Instaloval jsi instalátorem nebo ze ZIPu? Co máš v souboru `Fallout 4/Data/Interface/FalloutDict.txt`?

**Comment by PATRIK777CZ** [comment]
Jo zipem, dělalo mi to i u verze 0.9.3

**Comment by Martin005** [comment]
@PATRIK777CZ Můžeš se prosím podívat do souboru `Fallout 4/Data/Interface/FalloutDict.txt` a zjistit, jestli jsou tam česká slova?

**Comment by Milhousek** [comment]
Musíš mít problém s některým ze souborů, jak psal Martin, tak asi s **FalloutDict.**
Do teď jsem s terminály neměl žádný problém. Co se týče této konkrétní mise, tak jsem ji teď v rychlosti proletěl a s terminály taktéž nebyl problém.
![20180206125949_1](https://user-images.githubusercontent.com/34947824/35858903-60be0f6c-0b3e-11e8-96a7-74a9678981ef.jpg)
![20180206130302_1](https://user-images.githubusercontent.com/34947824/35858904-60dc95c2-0b3e-11e8-9233-2a0bb3a3b09d.jpg)

**Comment by PATRIK777CZ** [comment]
Tak kluci koukal jsem tam a vypadá to takto

![bez nazvu 1 kopie](https://user-images.githubusercontent.com/35434285/35859192-6a32b074-0b3f-11e8-96da-49d8a4edc3d6.JPG)

**Comment by pavelhoral** [comment]
Pojď asi na Discord - https://discord.gg/rUxYwwp . Tam se to bude řešit pohodlněji.

**Comment by PATRIK777CZ** [comment]
Vyřešeno, bylo to programem Advanced System Care 11, musíte ho odinstalovat ;)
