### ISSUE TITLE
Dialog s Tonym Savoldim #2

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#559]
![20180206174304_1](https://user-images.githubusercontent.com/34947824/35877051-8722c7b6-0b74-11e8-9703-e7970c1e8ff5.jpg)

_Karavanisti_ je takové divné slovo, nebylo by lepší _Majitelé karavan_?

**Comment by gugust** [comment]
Zkus říct karavnistům ve skupině na FB že je to divný slovo a rozcupujou tě, to je úplně normální a zcela běžný slovo

**Comment by Milhousek** [comment]
Neříkám, že není běžné, ale že zní vcelku divně a dalo by se nahradit něčím lepším.

**Comment by gugust** [comment]
nejlogičtější by bylo Obchdodníci s karavanama, ale zrovna v rámci mluvy ve hře nesdílím tvůj názor

**Comment by pavelhoral** [comment]
Jakým *karavanistům* a v jaké skupině? :D

**Comment by gugust** [comment]
https://www.facebook.com/groups/1702558016639049/

**Comment by pavelhoral** [comment]
Aha... oni to jsou lidé, co mají karavan. Nevím, jestli tohle označení platí i pro honáky / členy karavany :P.

**Comment by gugust** [comment]
spíš že karavning jako takovej, vzešel z názvu původního účelu kdy si obchodník veze vše sebou včetně střechy nad hlavou

**Comment by gugust** [comment]
http://nase-rec.ujc.cas.cz/archiv.php?art=5649
