### ISSUE TITLE
Dialog s Deb #2

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#568]
![20180206175323_1](https://user-images.githubusercontent.com/34947824/35881048-d5e64d68-0b7f-11e8-8623-c955234ee31e.jpg)

_Možná by jsi chtěl nejdříve doplnit nějaké zásoby._ - Zní lépe než _Možná se chceš prvně zásobit_.

**Comment by pavelhoral** [comment]
@Milhousek Nezapomínáš na pohlaví hráče?

**Comment by Milhousek** [comment]
_Možná chceš nejdřív doplnit nějaké zásoby_?

**Comment by Milhousek** [comment]
Případně - _Nechceš doplnit nějaké zásoby_
