### ISSUE TITLE
Chybka ve slově - Quest (Special Delivery [Speciální zásilka]).

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#572]
![20180208211229_1](https://user-images.githubusercontent.com/35151787/35995871-fe63c126-0d14-11e8-9467-d50ef83ad994.jpg)
Slovo - povim - _povím_

**Comment by StoupaJ** [comment]
podobné výrazy je hovorová nebo nespisovná mluva:  např. místo "pojď sem" je v textu "pocem"
tedy se nejedná o chybu v textu...

**Comment by MANUS-manww** [comment]
OK. Close.
