### ISSUE TITLE
Rozhovor s Isolda-ou (Crater of Atom)

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#575]
![20180204093815_1](https://user-images.githubusercontent.com/35151787/36053456-0fc24126-0df2-11e8-863b-c2e0fa934039.jpg)
Slovo - rozprávíme - změnil bych na _promluváme_.

**Comment by Fluik** [comment]
Už si to nepamatuju, ale řekla bych, že u nich je normální mluvit tímhle stylem. Takže bych to nechala.

**Comment by MANUS-manww** [comment]
Už si vzpomínám, že mněli tu mluvu zvláštní. Tak asi ok.

**Comment by Fluik** [comment]
Ok, tak zavírám.
