### ISSUE TITLE
Dialog Piper

### ISSUE THREAD

**Issue by gugust** [prekladyher/fallout4-cestina#577]
Piper tento dialog říká bez jakéhokoliv popudu, prostě sama od sebe, nemá na nic návaznost a proto je zcela nejasný o kom hovoří. Domnívám se že by měl znít následovně:
**Můžou** se nás neustále snažit zabít.... Nebo **Můžeš** se nás...?
Bohužel neznám originál, ale i po úpravě mi tam chybí smysl v tom dialogu.
Postněte prosím originál znění
![20180209235047_1](https://user-images.githubusercontent.com/34898590/36055602-e9e9102c-0dfd-11e8-9be6-924c8d1b8696.jpg)

**Comment by Fluik** [comment]
Tam jde o to, že se tě snaží zabít Commonwealth :) 

Originál: It may be constantly trying to kill us, but the Commonwealth never lacks for excitement.

**Comment by Milhousek** [comment]
Právěže ne, jde o to, že se je snaží zabít Institut (pokud to chápu dobře), ale v Commonwealthu bude vždycky vzrušení, tak jako tak. 
Ale i přesto v tom chybu nevidím.
