### ISSUE TITLE
Překlep v rozhovoru s Maxsonem - quest A New Dawn

### ISSUE THREAD

**Issue by cert23** [prekladyher/fallout4-cestina#585]
![20180213225325_1](https://user-images.githubusercontent.com/34834709/36282363-3793ce78-12a1-11e8-87f3-9b89dee79abc.jpg)

**Comment by MANUS-manww** [comment]
A kde je chyba?

**Comment by Milhousek** [comment]
repektu -> re**s**pektu

**Comment by MANUS-manww** [comment]
Skoro to není vidět.:)

**Comment by cert23** [comment]
Jojo oko vidí co si myslí, že by tam mělo být :)
