### ISSUE TITLE
Quest na čínské ponorce Yangtze (kapitán Zao) 

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#590]
![20180218120951_1](https://user-images.githubusercontent.com/35151787/36351167-0741e500-14a6-11e8-9e2d-363159634e69.jpg)
![20180218121043_1](https://user-images.githubusercontent.com/35151787/36351168-076f8abe-14a6-11e8-9a45-79471b6571f0.jpg)
![20180218121103_1](https://user-images.githubusercontent.com/35151787/36351169-078cfb76-14a6-11e8-932e-d00da5327316.jpg)
Občas vyká.

**Comment by Milhousek** [comment]
Tohle se řešilo v issue #294 
Ta dialogová možnost - _Jak dlouho čekáte_ je správně - viz. issue #294 
Ohledně toho Ghůla, záleží jestli se postava ptá, zda jsou všichni na posádce ghúlové (Všichni jste ghúlové? / Jste ghúlové?) nebo se táže jen daného NPC.
