### ISSUE TITLE
Hľadanie Virgila - rozhovor s Isoldou 

### ISSUE THREAD

**Issue by Johnny808** [prekladyher/fallout4-cestina#591]
Niektoré časti textov boli po anglicky a niektoré boli preložené po česky. Mám nainštalovanú verziu 0.9.4.
![screenshot5](https://user-images.githubusercontent.com/36645441/36395454-879b9e76-15b9-11e8-8d09-3fb19a069593.png)
![screenshot4](https://user-images.githubusercontent.com/36645441/36395461-8e5b5fb2-15b9-11e8-9ee6-6e1e424bf2be.png)
![screenshot3](https://user-images.githubusercontent.com/36645441/36395465-926185c8-15b9-11e8-94b7-1cbecf538698.png)

**Comment by pavelhoral** [comment]
To jsou texty z DLC Far Harbor.
