### ISSUE TITLE
Dialog s Kentem #1

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#593]
![20180220192307_1](https://user-images.githubusercontent.com/34947824/36477296-e7a123a2-1700-11e8-985c-798b07fd6454.jpg)

Mezi **5 kilový**, by měla být mezera.

**Comment by pavelhoral** [comment]
No, nevím - http://prirucka.ujc.cas.cz/?id=790

**Comment by Fluik** [comment]
Vzhledem k odkazu od Palka zavírám jako nevalidní.
