### ISSUE TITLE
Nápověda-kompas

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#6]
Posl.odstavec textu- Stejně jako u nepřátel,šipka na čtverci značí jejich "relativní vertikální pozici".
To už je asi trochu moc,řekla bych...

**Comment by pavelhoral** [comment]
Dal jsem tam stejnou větu, jako v případě nepřátel. I tak je to takové nic moc, ale v rozumném čase se mi nepodařilo vymyslet lepší formulaci (šipka značící *pozici* cíle vs. *směr* cíle).
