### ISSUE TITLE
Chyba v nazvoch zbroji

### ISSUE THREAD

**Issue by Oriny** [prekladyher/fallout4-cestina#605]
Nenasiel som toto medzi uz nahlasenymy problemamy ani medzi neopravitelnymy tak pre istotu to tu hodim.

Medzi zbrojamy vo Fallout 4 su varianty ako standart, sturdy a heavy priklad combat armoru 
http://fallout.wikia.com/wiki/Combat_armor_(Fallout_4)

Bohuzial co som si vsimol tak preklad nerobi rozdiely medzi tymyto variantamy a vsetky sa volaju rovnako...a cestina hadze rovnaky nazov bez ohladu na variant zbroje  bez ohladu na to ci je to standart, sturdy alebo heavy a robi v hre zbytocne zmetky z toho.

Ak sa to tu uz riesilo alebo je chyba u mna tak sa dopredu ospravedlnujem za tento prispevok a dakujem za pripadny rychly fix problemu.

**Comment by cert23** [comment]
Nejak nechapu, kde presne ma byt problem. Hra toto normalne zobrazuje.
![20180222194415_1](https://user-images.githubusercontent.com/34834709/36557543-dbaa8850-1808-11e8-9a71-b7a6a6fbdbf8.jpg)

**Comment by pavelhoral** [comment]
Čeština anglické přívlastky překládá jako štítky v hranatých závorkách (bohužel díky skloňování nemůžeme použít obyčejná přídavná jména). Místo `Sturdy` je `[Odolnost+]`, místo `Heavy` je v češtině `[Odolnost++]`. Ano, není to ideální (dost možná to brzy změním jen na `[ODO+]` nebo `[OVZ+]`), ale bohužel moc jinak to nejde.

Každopádně čeština nic nodstraňuje. Vždy nahrazujeme přívlastek za přívlastek / štítek.

**Comment by pavelhoral** [comment]
@cert23 Na screenshotu máš INNR ze svého modu. Naše čeština přídavná jména nemá.

**Comment by pavelhoral** [comment]
@Oriny Každopádně... pokud něco nefunguje, tak poprosím o screenshot. Pokud budeš mít nápad, jak to udělat jinak, tak uvítám diskuzi na Discordu https://discord.gg/rUxYwwp. Tuhle issue pro teď ale zavírám jako nevalidní.

**Comment by Oriny** [comment]
Jedine co tam mam navyse oproti zaklad je HD texture pack. Este skusim nejake veci.

**Comment by Oriny** [comment]
![fallout4 22 02 2018 20_32_00](https://user-images.githubusercontent.com/36742534/36560492-290ef5f6-1811-11e8-8cb8-1b29714b7262.png)
![fallout4 22 02 2018 20_32_56](https://user-images.githubusercontent.com/36742534/36560572-6302e9de-1811-11e8-9515-90d8e660ea76.png)
![fallout4 22 02 2018 20_33_10](https://user-images.githubusercontent.com/36742534/36560580-6c6b9b4c-1811-11e8-84ec-fdacfaef76e9.png)
![fallout4 22 02 2018 20_48_20](https://user-images.githubusercontent.com/36742534/36560695-c890cbea-1811-11e8-8d0d-8a11cefcf2d9.png)

**Comment by pavelhoral** [comment]
Tohle bude v originále mít vše přívlastek *Ultra-Light*.

**Comment by Oriny** [comment]
Cize v podstate vravis ze sa nedozviem ci je to standart, sturdy alebo heavy a budem to muset zistovat podla statov popripade nasadit to na seba a podla vzhladu ?

**Comment by pavelhoral** [comment]
Ano. A není to vlastnost češtiny, nýbrž hry jako takové. Pak jsou samozřejmě modifikace, které v těch "hloupých" přívlastcích dělají trošku pořádek, jak je třeba vidět na screenshotu od Čerta - https://www.nexusmods.com/fallout4/mods/29098.

**Comment by pavelhoral** [comment]
Jinak způsob generování názvů základní hry lze vyčíst z těchto tabulek:
* https://docs.google.com/spreadsheets/d/1FRFIqq9PLkL_aP1kAuzwzMILQfFA6dllbhMKPd7F7KI/edit#gid=2115701422
* https://docs.google.com/spreadsheets/d/1t1cy-uKAtEMW9jCi2LfN45Op-6jIkYFFW0FautBp8Jc/edit#gid=2115701422

**Comment by Oriny** [comment]
Dakujem za objasnenie situacie, v podstate som si myslel ze to tak bude ale chcel som sa spitat na to radsej. Dakujem za ochotu a vyvetlenie.
