### ISSUE TITLE
Teplota při seznámení hráče s Codsworthem

### ISSUE THREAD

**Issue by TimTheStranger** [prekladyher/fallout4-cestina#608]
Při prvním seznámení hráče s Codsworthem je teplota ve hře řečená ve stupnici Fahrenheita, ale v titulkách je udáná ve stupních Celsia. Je to detail, ale myslím si, že by bylo fajn tento problém opravit.
![20180223122318_1](https://user-images.githubusercontent.com/36762921/36592164-eb022b14-1894-11e8-9644-0fa4273ac7e2.jpg)

**Comment by pavelhoral** [comment]
Ale my to tam máme přepočítané :)

**Comment by pavelhoral** [comment]
```
<Source>Ah, good morning, mum! Your coffee. 173.5 degree Fahrenheit. Brewed to perfection!</Source>
<Dest>Dobré ráno, paní! Vaše káva. 78,5 stupňů Celsia. Uvařeno k dokonalosti!</Dest>
```

Myslím, že se stupni Celsia je to čitelnější a pochopitelnější. Nejde o chybu, ale úmysl.
