### ISSUE TITLE
Dialog se syntetikem v Institutu

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#628]
![20180303174311_1](https://user-images.githubusercontent.com/34947824/36939322-2d680a8c-1f2f-11e8-8386-3f26f27a9e90.jpg)
![20180303174316_1](https://user-images.githubusercontent.com/34947824/36939323-2eac32ec-1f2f-11e8-87da-d8d8ac15297a.jpg)
![20180303174339_1](https://user-images.githubusercontent.com/34947824/36939324-2fdf70de-1f2f-11e8-9193-576a1e7c6cc9.jpg)

**V**ašeho, **V**ás

**Comment by Fluik** [comment]
#717
