### ISSUE TITLE
Dialog se Z1-14

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#629]
![20180303182427_1](https://user-images.githubusercontent.com/34947824/36939352-92ce79ec-1f2f-11e8-9798-030b6575c53e.jpg)
![20180303182610_1](https://user-images.githubusercontent.com/34947824/36939353-92ebf120-1f2f-11e8-8d00-e3fd502dddc3.jpg)

**V**ám, **V**aší

**Comment by Fluik** [comment]
#717
