### ISSUE TITLE
Rozhovor s Bobbi.Quest The Big Dig.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#632]
![20180303202344_1](https://user-images.githubusercontent.com/35151787/36939376-23c52536-1f30-11e8-8451-3e45837b0207.jpg)
Slovo (chlapi) - nahradil bych slovem _lidi,nebo úplně vynechal._
Hra za ženu s ženským společníkem.

Wiki:
000A7D11 |   | {To yourself, sarcastic} Great, now my socks are wet. |   | A
-- | -- | -- | -- | --
199 |   | {Rallying the team, excited}Well guys, we're right under the Diamond City strongroom. | Mel: You sure this is the right place? | A

**Comment by Milhousek** [comment]
Tady chlapi nesedí no, jelikož tam je hráč (muž nebo  žena) + Mel (muž). 
Takže pokud hráč hraje za mužskou postavu, tak _chlapi_ by bylo na místě, ale pokud hráč hraje za ženskou postavu, tak je to blbost.
