### ISSUE TITLE
Rozhovor s Bobbi.Quest The Big Dig.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#634]
![20180303202642_1](https://user-images.githubusercontent.com/35151787/36939449-90a00454-1f31-11e8-927a-8b153360ec98.jpg)
Originál je teda jinak.

Wiki:
Player Default: I trust you, Bobbi. | That's why you are my favorite. |   | A1a
-- | -- | -- | --

**Comment by Milhousek** [comment]
Je to přeloženo volněji. A neřekl bych, že tento překlad mění význam originálu.

**Comment by Fluik** [comment]
Zavírám, přeloženo úmyslně volněji :)

**Comment by pavelhoral** [comment]
> Zavírám, přeloženo úmyslně volněji :)

Doplním, že velmi pravděpodobně kvůli neutrálnosti vůči pohlaví.
