### ISSUE TITLE
Dialog s Alanou Secord

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#643]
![20180303184822_1](https://user-images.githubusercontent.com/34947824/36939791-91b69e7e-1f37-11e8-93dc-096c9bca67e7.jpg)

_Snaž **Se si** pamatovat_ zní dost blbě.

**Comment by MANUS-manww** [comment]
To je úplná kravina.Tady má být - _snaž si zapamatovat..._

**Comment by Fluik** [comment]
Mě se zdá blbý i to "snaž si zapamatovat". Takže nahrazeno "zkus si pamatovat".
