### ISSUE TITLE
valout 88

### ISSUE THREAD

**Issue by DEDOKA** [prekladyher/fallout4-cestina#652]
> 
![20180311175841_1](https://user-images.githubusercontent.com/37277035/37259057-9d4b591e-2581-11e8-8c36-31e095691fc5.jpg)
![20180311180055_1](https://user-images.githubusercontent.com/37277035/37259058-9d6cc02c-2581-11e8-88e3-2203332ebc6f.jpg)

**Comment by pavelhoral** [comment]
Tohle je quest z DLC Vault-Tec Workshop, který teprve překládáme. http://fallout.wikia.com/wiki/Vault-Tec_Calling

**Comment by DEDOKA** [comment]
OK. Dik.
