### ISSUE TITLE
Terminál v testovací laboratoři prototypu.Quest Spoils of War [Válečná kořist]

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#655]
![20180312212522_1](https://user-images.githubusercontent.com/35151787/37308098-3b72e47a-263d-11e8-8cad-ff5692d0a1ea.jpg)
Dnes jsem přešli - _jsme._

**Comment by Fluik** [comment]
Zavírám, ten text už je jiný. Asi v rámci změn z jiného issue.
