### ISSUE TITLE
V dialogu s Desdemonou se používá množné číslo místo jednotného

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#662]
![20180312220414_1](https://user-images.githubusercontent.com/34947824/37312796-cae31184-264c-11e8-8063-78fc2790aaea.jpg)
![20180312220500_1](https://user-images.githubusercontent.com/34947824/37312807-cf847156-264c-11e8-8bdc-2af32947ac22.jpg)
![20180312220659_1](https://user-images.githubusercontent.com/34947824/37312873-11cfb6c4-264d-11e8-9c78-887a627438e0.jpg)

**Setkali jste se** s Patriotem - Tady by mělo být jednotné číslo, ale pokud se jedná o jednotnou větu jak pro hráče za muže, tak za ženu, tak tu nastane problém. Jednotné číslo tady má být z toho důvodu, že se do Institutu hráč vydá sám, nikdo jiný se tam s ním nedostane.
Zároveň se v jedné větě používá **Tomova páska** a v druhé **Tomova holopáska** - chělo by to sjednotit.

**Comment by MANUS-manww** [comment]
2064        <REC>INFO:NAM1</REC>
 2065        <Source>And Tom's holotape? Did you make contact with Patriot?</Source>
 2066:       <Dest>A Tomova holopáska? Setkali jste se s Patriotem?</Dest>
 2067      </String>
 2068      <String List="2" sID="018448">


 2706        <REC>INFO:NAM1</REC>
 2707        <Source>Besides meeting your boy, did you meet Patriot, too? Did Tom's holotape work?</Source>
 2708:       <Dest>A krom tvýho kluka, potkali jste se i s Patriotem? Fungovala Tomova páska?</Dest>
 2709      </String>
 2710      <String List="2" sID="01CED4">


 2286        <REC>INFO:NAM1</REC>
 2287        <Source>I met Patriot. His name is Liam Binet.</Source>
 2288:       <Dest>S Patriotem jsme se setkali. Jmenuje se Liam Binet.</Dest>
 2289      </String>
 2290      <String List="2" sID="01E0EF">

Zde se určitě jedná o záměr.
Napadá mě jedině ohnout originál:

Je tam Patriot?
Patriot tam je.
