### ISSUE TITLE
Dialogová volba při rozhovoru s Desdemonou

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#663]
![20180312220549_1](https://user-images.githubusercontent.com/34947824/37313020-acb74e9a-264d-11e8-8763-7952dfd42626.jpg)

Povedlo se **mi** najít mého syna.

**Comment by pavelhoral** [comment]
Já bych se možná nebál i změny na *Byl tam můj syn* (ale musel by se ověřit kontext a navazující dialog)
