### ISSUE TITLE
Dialog s Z1-14 #2

### ISSUE THREAD

**Issue by Milhousek** [prekladyher/fallout4-cestina#668]
![20180314205354_1](https://user-images.githubusercontent.com/34947824/37435346-3a201b0e-27e3-11e8-98ce-264fbf38a804.jpg)

**V**ás.

**Comment by MANUS-manww** [comment]
![20180401215859_1](https://user-images.githubusercontent.com/35151787/38176979-36ab57b2-35f9-11e8-8355-bbf982ef9817.jpg)
Tady je další...(**V**aši)

**Comment by Milhousek** [comment]
Tenhle screen jsem již hlásil v issue #629, každopádně tyhle 2 issue by se dali klidně spojit (vůbec nevím, proč jsem je zakládal odděleně, asi kvůli tomu časovému rozestupu)

**Comment by Fluik** [comment]
#717
