### ISSUE TITLE
Rozhovor s Maxon-em.Quest The Nuclear Option (Brotherhood of Steel) 3.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#687]
![20180324164922_1](https://user-images.githubusercontent.com/35151787/37865995-8d185ef4-2f84-11e8-84f1-8bfa15a6360c.jpg)
První věta by chtěla odosobnit.
Třeba použít jen: _Příkladná práce,paladine._

**Comment by Fluik** [comment]
Upraveno na "Příkladná práce, paladine."
