### ISSUE TITLE
Rozhovor s Alie.Quest Mass Fusion.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#689]
![20180325122032_1](https://user-images.githubusercontent.com/35151787/37874088-e2630528-3027-11e8-95cf-5b9ebbcf280f.jpg)
Slovo zesložiťuje - to je na zlomení jazyka.
Dal bych - _komplikuje._

Origo:
2869        <Source>You're going? That complicates things.</Source>
 2870:       <Dest>Chceš jít? Tím se to celé zesložiťuje.</Dest>

Našel jsem to ještě jednou...
 175        <Source>That Complicates Things</Source>
  176:       <Dest>Tím se to zesložiťuje</Dest>

**Comment by Fluik** [comment]
Upraveno na "komplikuje".
