### ISSUE TITLE
Rozhovor s Newton-em.Quest A House Divided.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#691]
![20180325132436_1](https://user-images.githubusercontent.com/35151787/37874480-583b46e0-3030-11e8-99e5-a277209c2535.jpg)
Slovo (ty) předměty - špatně přeloženo.
Mělo by tam být - _tyto nebo tyhle._

Origo:
3145        <Source>I gathered these items together for you. I think you'll find them useful.</Source>
 3146:       <Dest>Posbíral jsem pro tebe ty předměty. Myslím, že ti přijdou vhod.</Dest>

**Comment by Milhousek** [comment]
Tohle jsem již hlásil v issue #680

**Comment by MANUS-manww** [comment]
Jo,nevšiml jsem si.
