### ISSUE TITLE
Dialog s Z1-14.Quest The Nuclear Option (Railroad).

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#696]
![20180329062713_1](https://user-images.githubusercontent.com/35151787/38070117-7faa0896-331a-11e8-936f-706d25237ddc.jpg)
Věta se musí přeformulovat tak,aby byla použitelná pro oba rody.

Origo:
6307        <Source>I've been looking for you...</Source>
 6308:       <Dest>Tebe jsem hledal...</Dest>

**Comment by Fluik** [comment]
Upraveno na "Zrovna tebe hledám..." Je to "greeting" hláška.
