### ISSUE TITLE
Dialog se Syntetikem v Institutu.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#697]
![20180401215257_1](https://user-images.githubusercontent.com/35151787/38177005-9fb08ce6-35f9-11e8-8ac7-735bc6f323fb.jpg)
![20180401215209_1](https://user-images.githubusercontent.com/35151787/38177006-9fcc1ed4-35f9-11e8-96bf-d8f52381ce4b.jpg)
![20180401215219_1](https://user-images.githubusercontent.com/35151787/38177007-9fe6fa9c-35f9-11e8-87f4-c959fd0a0477.jpg)
Velké V.

**Comment by Milhousek** [comment]
Tohle jsem už zakládal viz #628. Týká se to nejspíše všech dialogů syntetiků v institutu, resp. všichni syntetici v Institutu mají stejné repliky vět.

**Comment by MANUS-manww** [comment]
OK,ale nechal bych to otevřené... Ať se na ty synty podívají kompletně.

**Comment by pavelhoral** [comment]
Vytvořil jsem jednotnou issue pro opravu velkých písmen u vykání - #717.
