### ISSUE TITLE
Holopáska Poklady Jamajské Pláně

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#713]
![20180511154528_1](https://user-images.githubusercontent.com/35151787/39927487-a899b8fc-5532-11e8-83b1-a0e2c26fa9fa.jpg)
(2077 Vám) - má být malé _v._

**Comment by pavelhoral** [comment]
Vytvořil jsem jednotnou issue pro opravu velkých písmen u vykání - #717.
