### ISSUE TITLE
Oslovení (dítě)

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#715]
5179        <Source>Hey, pal.</Source>
 5180:       <Dest>Ahoj kamaráde.</Dest>

Bude to chtít lepší formulaci.- oslovit můžu i dívku...

**Comment by pavelhoral** [comment]
Co je na tomhle špatně? Tohle konkrétní oslovení jsem dokonce měl jako součást videa :)

https://youtu.be/A-jyVuyUerE?t=1m32s

**Comment by MANUS-manww** [comment]
Dívce přeci neříkáš kamaráde... nebo jo?

**Comment by MANUS-manww** [comment]
![20180514083542_1](https://user-images.githubusercontent.com/35151787/39981682-dd29ea58-5751-11e8-9d34-f5d505f13dc8.jpg)
Je to takové divné...

**Comment by MANUS-manww** [comment]
@prekladyher/fallout4-cestina - Tak po poradách s různými lidmi,co byli v Anglii a USA -jsem dospěl k názoru,že to oslovení je celkem v pohodě.
Pokud to tedy nikomu nevadí(zatím se nikdo neozval kromě palka),tak to zavřu.

**Comment by Milhousek** [comment]
Myslím, že s tímhle by se stejně nic dělat nedalo, protože by jsi mohl vyměnit _pal_ za _mate_ a vyšlo by to nastejno. Hold to je problém těch anglických oboupohlavních výrazů.

**Comment by MANUS-manww** [comment]
OK - close
