### ISSUE TITLE
Dialog Erin.Quest Krátké příběhy.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#716]
![20180514111259_1](https://user-images.githubusercontent.com/35151787/39988832-b27cc7aa-5768-11e8-8613-0d65e51eeddc.jpg)
Vámi - má být malé _v_.

Origo:
5065        <Source>I bet you were glad he was there.</Source>
 5066:       <Dest>Určitě máte radost, že tam s Vámi byl.</Dest>

**Comment by pavelhoral** [comment]
Chyby na velké písmeno při vykání asi nemusíš zakládat odděleně... opravím to pak najednou.

**Comment by MANUS-manww** [comment]
Jak tedy - do nějaké předchozí?

**Comment by pavelhoral** [comment]
Já to budu hledat tak, že si najdu všechny výskyty *Vám\* / Vás / Vaš\**, které jsou uprostřed věty a hromadně to změním. Takže mi vlastně stačí chyba ve stylu "V překladu se v dialogových titulcích vyká s velkým písmenem". Jednotlivé výskyty pak nepotřebuji... maximálně že bys to pak chtěl ty zkontrolovat, že jsem to skutečně opravil všude.

**Comment by MANUS-manww** [comment]
OK tak tohle zavřu...

**Comment by pavelhoral** [comment]
Vytvořil jsem jednotnou issue pro opravu velkých písmen u vykání - #717.
