### ISSUE TITLE
Dialog s Valentine-m a Piper.Quest Reunions.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#718]
![20180519230638_1](https://user-images.githubusercontent.com/35151787/40273253-40de2874-5bbd-11e8-9be3-dc8e821d6c4f.jpg)
Kleště na zmrzlinu? - pokud vím,tak je to naběračka...

Dal bych: hodně ostrou naběračku...

Origo:
3811        <Source>I'm gonna need a really sharp ice cream scoop...</Source>
 3812:       <Dest>Budu potřebovat hodně nabroušené kleště na zmrzlinu...</Dest>

**Comment by Fluik** [comment]
Možností je víc, kleště, naběračka, porcovač, lžíce...
