### ISSUE TITLE
Dialog s Amari-ovou.Quest Reunions.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#722]
![20180520001901_1](https://user-images.githubusercontent.com/35151787/40282935-92a397fc-5c76-11e8-9061-bd4282815d64.jpg)
Kosmickou kombinézu - chtělo by to upravit....

**Comment by MANUS-manww** [comment]
Vlastně jsem to už založil.... :)

**Comment by pavelhoral** [comment]
@MANUS-manww Pokud jsi to už někde jinde založil, prosím o provázání přes číslo issue.

**Comment by pavelhoral** [comment]
Už jsem to našel -  #719.

**Comment by MANUS-manww** [comment]
Jj-sry-příště na to hodím pamatováka.
