### ISSUE TITLE
Stačí říct slovo

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#723]
Prošel jsem ve hře vedle Piper a ta na mě vybafla: *"Můžu něco udělat? Stačí říct slovo."*, což mi tedy dvakrát česky nezní.

**Comment by MANUS-manww** [comment]
To bude tohle...

 1573        <Source>Anything I can do? You just say the word.</Source>
 1574:       <Dest>Můžu něco udělat? Stačí říct slovo.</Dest>
