### ISSUE TITLE
Rozhovor s Čestným Dan-em.Quest Human Error (Covenant).

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#734]
![20180615152938_1](https://user-images.githubusercontent.com/35151787/41470597-5a93f8d0-70b1-11e8-8c1b-c31197f0e043.jpg)
V kontextu odpověď nesedí.
(Dal bych - _Ty taky._)

Origo:
1741        <Source>Same to you.</Source>
 1742:       <Dest>Tobě také.</Dest>

Předchozí (moje) věta:
![20180615153009_1](https://user-images.githubusercontent.com/35151787/41470655-8be92310-70b1-11e8-9784-d016e319d805.jpg)

**Comment by Milhousek** [comment]
Tuto chybu jsem již reportoval, viz. #477

**Comment by MANUS-manww** [comment]
OK zavírám jako duplikát.
