### ISSUE TITLE
Call to Arms quest

### ISSUE THREAD

**Issue by Warysek** [prekladyher/fallout4-cestina#736]
Ahoj, doufám že to nedělám nějak špatně, ale při hře questu call to arms, poté, co s paladinem Dansem vlezeme do budovy ArcJet Systems a najdeme vyřazenou vnitřní obranu, paladin zapřednáší o syntech a institutu a rozhovor jde kladně ukončit slovy "ill be on guard", které jsou v překladu jako budu tu hlídat, což mi nepřijde uplně v pořádku ^^ Jinak Dík moc za vaši práci 👍 #

**Comment by pavelhoral** [comment]
Díky za nahlášení. Chvilku mi možná bude trvat, než se k tomu dostanu, ale rozhodně to nezapadne.

**Comment by Warysek** [comment]
Stejně tak když vás po misi přijímá do svých řad, bych v přijímacím dialogu kde povídá "{Confident} I only ask for two things from anyone under my command. Honesty and respect." Bych nepřekládal Honesty jako uřpímnost ale spíš jako čestnost :) 
Jinak překlad "{re-record / Confident} We're not soldiers of fortune. We're an army and we've dedicated our lives to uphold a strict code of ethics."
Nejsme vojáci štěstěny, to snad není ani český výraz, ale archaický špatný překlad, není normální už říkat žoldák? 
Sry za hnidopišství :D ale třeba to k něčemu bude :)

**Comment by Starfis** [comment]
Bratrstvo si hraje na rytíře a používá poměrně zastaralý jazyk takže by to tam možná i sedělo.
