### ISSUE TITLE
(DLC Workshop) Rozhovory s kandidáty.Quest Power of the People.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#738]
![20180714193353_1](https://user-images.githubusercontent.com/35151787/42727013-afa9ac26-879e-11e8-8dac-27e89d0890ff.jpg)
Větu by chtělo lépe odosobnit.
Navrhuji - (kolegův) změnit na _partnerův._
Nebo  - Omlovám se za humor mého partnera.

Origo:
960        <REC>INFO:NAM1</REC>
  961        <Source>Yes. Sorry about my associate's... yes, humor.</Source>
  962:       <Dest>Ano. Omlouvám se za kolegův... humor, ano.</Dest>
  963      </String>
  964      <String List="2" sID="000204">

**Comment by Fluik** [comment]
Jestli správně chápu, tak tady jde o odpohlavnění? V tom případě mi kolega příjde stejné jako partner. Co to vynechat? "Omlouvá se za ten... humor." (Ono i to "ano" se mi tam zdá zvláštní)

**Comment by MANUS-manww** [comment]
Jo,myslím že by bylo lepší to úplně vynechat.
