### ISSUE TITLE
Rozhovor s Piper (Affinity Perk). 

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#745]
![20180227232501_1](https://user-images.githubusercontent.com/35151787/43663364-7aefe84e-9769-11e8-967d-1d9302d85b40.jpg)
Když je přeloženo slovo Affinity jako náklonnost,tak dát místo (s) _od._

Origo:
      <Source>Having reached the highest level of affinity with Piper, you have gained the "Gift of Gab" perk.</Source>
      <Dest>Za dosažení nejvyššího stupně náklonnosti s Piper získáváš perk „Mluvka“.</Dest>

**Comment by pavelhoral** [comment]
Úplně bych tu předložku odstranil. Správně je *náklonnost někoho*, spíše než *náklonnost od někoho*.
