### ISSUE TITLE
Dialog s ADA-ou.Quest A New Threat.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#749]
![20180808225240_1](https://user-images.githubusercontent.com/35151787/43863800-1caa9650-9b5e-11e8-8fb9-77fb22af6723.jpg)
ADA o sobě mluví v mužském rodě.

    <String List="2" sID="0007F2">
      <EDID>[0100101F]</EDID>
      <REC>INFO:NAM1</REC>
      <Source>I'd be happy to help if I can.</Source>
      <Dest>Rád bych pomohl, jestli můžu.</Dest>
    </String>

**Comment by Fluik** [comment]
Bude se muset vymyslet něco neutrálního, je to sdílené mezi všemi roboty.

**Comment by pavelhoral** [comment]
Aniž bych to blíže zkoumal, tak mě napadá: *S radostí pomohu, bude-li to možné.*
