### ISSUE TITLE
Dialog s ADA-ou.Quest A New Threat.#3

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#751]
![20180813222711_1](https://user-images.githubusercontent.com/35151787/44056489-b4d43ee8-9f48-11e8-9af2-c9bf6c6fca6e.jpg)
Druhá věta se musí přeformulovat na oba rody.
Dal bych: (_Takže, to bylo vsěchno zbytečná práce?)_

Origo:
642        <REC>INFO:NAM1</REC>
  643        <Source>Well, that's useless. I did all this for nothing?</Source>
  644:       <Dest>No, ale to je nám k ničemu. Takže jsem to všechno dělal zbytečně?</Dest>
  645      </String>
  646      <String List="2" sID="000EBD">

**Comment by Fluik** [comment]
Tohle už je opraveno.
