### ISSUE TITLE
Nejednotný překlad Quality Assurance

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#752]
Na pár místech je Quality Assurance department of General Atomics přeloženo více způsoby.

**Comment by pavelhoral** [comment]
Jinak na většině míst to je jako *oddělení jakosti*, ale nejsem si jistý, zda není obvyklejší *oddělení řízení kvality*. Jakost mám obvykle spojenou s potravinářským průmyslem.

**Comment by MANUS-manww** [comment]
řízení kvality...

**Comment by MANUS-manww** [comment]
Je to odborný výraz. Odělení kvality - kvalitář/ka
