### ISSUE TITLE
(DLC Automatron) Terminál (Zadržovací blok a - pozorovatelna),(terminál extrakce mozku 02).

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#753]
![20180921183536_1](https://user-images.githubusercontent.com/35151787/45894128-cd977280-bdcd-11e8-9392-06e158364dd5.jpg)

ty muži a ženy - _ti._
že ty lidé - _ti._

![20180921185137_1](https://user-images.githubusercontent.com/35151787/45894765-a477e180-bdcf-11e8-87f4-1d10550fef57.jpg)

s lidmi z montážního oddělení a ty se mě ptali... - _ti._

**Comment by pavelhoral** [comment]
Tohle jsou celkem divné překlady. První je kandidát na odstranění pár zájmen (aneb když se otrocky překládá určitý člen) a u druhého jsem se nedostal přes první větu.

**Comment by pavelhoral** [comment]
Jo, tak ten druhý překlad je chyba, kdy tam překladatel nechal Google Translate verzi :) (skutečný překlad je ten druhý odstavec).

**Comment by pavelhoral** [comment]
Oboje upraveno v rámci nedávných hromadných oprav.
