### ISSUE TITLE
Dialogy Ady (DLC Automatron).

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#762]
![20181022213833_1](https://user-images.githubusercontent.com/35151787/47314917-4e52c400-d643-11e8-9fc9-dba9d3e8059b.jpg)
Mluví o sobě v mužském rodě.
Chybka ve slově (jsem) - _jsme._(už opraveno).

Origo:
744        <REC>INFO:NAM1</REC>
  745        <Source>I'm not certain what caused this mess, but perhaps it's best that we weren't here to find out.</Source>
  746:       <Dest>!Nejsem si jistý co způsobilo tento nepořádek, ale možná je to nejlepší co jsme tu našli.</Dest>
  747      </String>
  748      <String List="2" sID="000271" Partial="1">

![20181024114537_1](https://user-images.githubusercontent.com/35151787/47423478-616dad00-d785-11e8-814e-7d0d8b077e6c.jpg)

 1974        <REC>INFO:NAM1</REC>
 1975        <Source>If I had access to a vacuum modification, I could make this place shine.</Source>
 1976:       <Dest>Kdybych měl přístup k vysávací modifikaci, mohl bych toto místo rozzářit čistotou.</Dest>
 1977      </String>
 1978      <String List="2" sID="00075A">

**Comment by Fluik** [comment]
Bylo už upraveno.
