### ISSUE TITLE
Terminál ROBCO E-601

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#763]
![20181107220619_1](https://user-images.githubusercontent.com/35151787/48161263-64ff4900-e2da-11e8-8201-27c983953678.jpg)
Chybka ve slově (operačníjo)

Origo:
DLCRobot\noinfo-edids-03.xml:
 1293              - Viceprezident účetního oddělení&#xD;
 1294              - Viceprezident oddělení odbytu&#xD;
 1295: 12:00: Pracovní oběd se zástupci operačníjo řízení&#xD;
 1296  15:00: Zasedání rady ohledně globálního slučování.&#xD;
 1297              Shrnutí: Výhody globální expanze&#xD;

**Comment by pavelhoral** [comment]
Bylo opraveno na _Pracovní oběd se zástupci vedení provozu_ v rámci hromadných oprav.
