### ISSUE TITLE
Terminál VEDOUCÍHO INŽENÝRA.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#764]
![20181107224941_1](https://user-images.githubusercontent.com/35151787/48163595-63388400-e2e0-11e8-9247-76d8104840f0.jpg)
Chybka ve slově (přemýšl).

![20181107225057_1](https://user-images.githubusercontent.com/35151787/48163629-7d726200-e2e0-11e8-99ea-51f19dbc874e.jpg)
Aspoň bych zaměnil za _Alespoň._

DLCRobot\noinfo-edids-03.xml:
 1414  Tak se nám vrátila první várka robomozků z testování a jsou v žalostném stavu. Prasklé kopule, vyhozené pásy, přetížené fúzní články, usmažené obvody - a takhle bych mohl pokračovat dál a dál.&#xD;
 1415  &#xD;
 1416: Konkrétně tohle je znepokojující problém. Podle uživatelů někteří z robomozků špatně interpretují příkazy. Jak se zdá, palubní mozek nad těmito pokyny tak dlouho přemýšl, až se „rozhodne“ si je sám přeformulovat. To má většinou za následek poškození majetku nebo dokonce i pár civilních obětí.&#xD;
 1417  &#xD;
 1418  Projel jsem každý centimetr čtvereční vadných kusů a nenašel jsem na nich žádnou závadu. Budu tenhle problém muset předat na výzkumné oddělení a uvidíme, s čím přijdou. Aspoň že v tomhle případě jsme z obliga.</Dest>

**Comment by pavelhoral** [comment]
Bude opraveno v rámci hromadných oprav v nejbližším commitu (u sebe lokálně mám již opraveno).
