### ISSUE TITLE
Terminálový systém -> terminál

### ISSUE THREAD

**Issue by pavelhoral** [prekladyher/fallout4-cestina#765]
V DLCRobot překládáme *"XYZ Terminal System"* jako *"Terminálový systém XYZ"*. Slůvko systém je tu ale zbytečné a malinko zavádějící, protože jde o model terminálu jako takového. Navrhuji tedy *terminálové systémy* překládat jako *terminály* (vynechat slůvko *systém*).

**Comment by Dumec** [comment]
Jo, souhlasím.
