### ISSUE TITLE
Rozhovory s Rei a Kenji Nakano-vými.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#770]
![20190602155326_1](https://user-images.githubusercontent.com/35151787/58762518-fb35dd80-8550-11e9-8307-79ae1eaf40df.jpg)

scopná - _schopná_

![20190602155546_1](https://user-images.githubusercontent.com/35151787/58762537-21f41400-8551-11e9-9e6a-3c731fcad2d6.jpg)
![20190602160435_1](https://user-images.githubusercontent.com/35151787/58762550-33d5b700-8551-11e9-95c7-9a1a5690a130.jpg)

Během pauzy v rozhovoru mi tykají (celý rozhovor si vykáme).(nevím jestli je vykáni správně - dospělé osoby)

**Comment by Fluik** [comment]
Podle slovníčku mají vykat. (Jen poznámka pro mě až budu opravovat)
