### ISSUE TITLE
Rozhovor s Dítětem Atoma...

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#772]
![20190615071803_1](https://user-images.githubusercontent.com/35151787/59547409-c194a780-8f3e-11e9-9de2-937a5a2be50d.jpg)

Místo slova cizinče,bych dal _člověče_ - je to více neutrální... (hra za ženu).

**Comment by Fluik** [comment]
Tohle je na hodně místech, takže je otázka jestli to chceme měnit. Podobně je "problém" i s kámo a dalším oslovením.

**Comment by MANUS-manww** [comment]
Já jsem pro změnit - cizinče/cizinko - člověče je pro oba rody stejné oslovení.
