### ISSUE TITLE
Úkol ve FAR HARBOR

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#774]
![20190615074821_1](https://user-images.githubusercontent.com/35151787/59547635-34ebe880-8f42-11e9-8132-21fd60fe4ec8.jpg)

Pomoz kapitánu Averiové - _Pomoz kapitánce Averyové_

**Comment by Fluik** [comment]
Hodnosti nepřechylujeme, takže je to správně.
