### ISSUE TITLE
Rozhovor s Faraday-em.

### ISSUE THREAD

**Issue by MANUS-manww** [prekladyher/fallout4-cestina#777]
![20190724152146_1](https://user-images.githubusercontent.com/35151787/61797211-3b199280-ae27-11e9-985f-a41aa8108781.jpg)
toudělali. - _to udělali._

![20190724152246_1](https://user-images.githubusercontent.com/35151787/61797296-6ac89a80-ae27-11e9-98e5-5c5d99197a8e.jpg)
Věty se musí přeformulovat tak,aby byly použitelné pro oba rody.

**Comment by Fluik** [comment]
Zároveň jsem zkontrolovala ostatní texty v celém rozhovoru.
