### ISSUE TITLE
Malá chybka

### ISSUE THREAD

**Issue by Derlag** [prekladyher/fallout4-cestina#778]
Zdravím  na začátku základní hry po probuzení  jsem zjistil že pokud si chci vzít novou uniformu  vaultu 111 tak mne to napsalo chybové hlášeni a v pipboy při otevíraní dveří se píše popisek v angličtině ale to si nejsem jistý jestli to bylo vůbec nikdy přeloženo 
tak zatím ahoj super překlad

**Comment by Derlag** [comment]
ještě jsem zapomněl ze se mne nezobrazoval text při prvním úkolu  pro ty osadníky  něco ? komentář od toho chlápka u pc který mne má dat informace o tom jádře ve sklepě pro energozbroj u té helikoptéry ?? tak to je zatím vše

**Comment by pavelhoral** [comment]
Díky za info. O chybě víme (může za ní aktualizace Creation Club).

![obrazek](https://user-images.githubusercontent.com/2012726/64074872-44f9a580-ccb1-11e9-9b90-c71112412813.png)

Bude brzy opraveno. O "nezobrazování úkolu" nic nevíme.

**Comment by Derlag** [comment]
poupravil jsem ten text nahoře tak zatím jdu hrát dál

**Comment by pavelhoral** [comment]
Jo, to je známá chyba hry - https://www.youtube.com/watch?v=063KepfGebc. Na to nemá čeština vliv.
