### ISSUE TITLE
Spanner - špatný překlad

### ISSUE THREAD

**Issue by Martin005** [prekladyher/fallout4-cestina#79]
Institute_Spanner01 - "Spanner" přeloženo jako "Francouzský klíč". Z obrázku je jasné, že o francouzský (nastavitelný) klíč nejde, avšak žádný takový podobný jsem po 10 minutách hledání na e-shopech nenašel.
Navhruji dát obyčejné "Klíč", vycházím z wiki: "A wrench (or **spanner** outside of North America) is a tool used to..." (https://en.wikipedia.org/wiki/Wrench)

![screenshot50](https://cloud.githubusercontent.com/assets/10096404/20042321/3972c71e-a478-11e6-9956-91ef88b4ebea.png)

**Comment by pavelhoral** [comment]
Tak ještě otvírám, protože "stavitelný klíč" v překladech již existuje. Navíc @StoupaJ přistihl jednoho vědce v Institutu s přístrojem pracovat a rozhodně ho jako klíč nepoužíval.

Použití vypadalo jako nějaká diagnostika zařízení a použití vypadalo celkem blízko použití detektoru kovů při hledání drátů ve zdi. Změníme tedy na strohý "detektor", abychom tomu nepodsouvali význam, který to případně nemá.

**Comment by StoupaJ** [comment]
opraveno v rámci 02ed4f0 (Detektor) - [a tady je na ukázku i video](https://drive.google.com/open?id=0B0OsHDeEAfE8ME5SUDhEcU8xd0U) (se sníženou kvalitou obrazu) :)
