### ISSUE TITLE
s cestinou nejde hra

### ISSUE THREAD

**Issue by SKINETcz** [prekladyher/fallout4-cestina#791]
cus mam problem s cestinou pri spusteni hry cerny obraz a hnedka pad hry a dela to falout4custom.ini jak dam nahradit zacne padat hra tento problem mam od doby co mam novy monitor 32:9 Samsung C49HG90 predem dik za rady

**Comment by pavelhoral** [comment]
Fallout má extrémní problém s nestandardním poměrem stran... zkus hru spustit ve "Windowed mode" režimu.

![image](https://user-images.githubusercontent.com/2012726/88652755-85cd8a80-d0cb-11ea-9bad-1362e961d856.png)

https://help.bethesda.net/app/answers/detail/a_id/41682/~/what-do-i-do-if-fallout-4-wont-launch-in-full-screen%3F

**Comment by pavelhoral** [comment]
Jinak trošku pochybuji, že by chyba měla souviset s češtinou. Dej vědět, jestli ti ta změna režimu pomůže.

**Comment by MANUS-manww** [comment]
Určitě nejde o problém s češtinou - bude spíše v ovladačích...

**Comment by SKINETcz** [comment]
dik za rady zatim poreseno bez fallout4custom.ini skousel sem hodne veci chci si zahrat tak zatim jedu takto cestina je neuplna ale de to az budu mit chut se rejpat v tom tak poresim lip
