### ISSUE TITLE
Nefunkční čeština na Xboxu

### ISSUE THREAD

**Issue by IceWolfCZ** [prekladyher/fallout4-cestina#793]
Po první instalaci a provedení všeho podle pokynů vše fungovalo jak má. Bohužel hned následující den už hra jede v angličtině a přes veškeré snahy se mi čeština nepodařila aktivovat. Nepomohlo ani odinstalování módu. A nesledná instalace a postup podle návodu.

**Comment by pavelhoral** [comment]
Zeptal jsem se na Discordu, zda by to mohl někdo ověřit. Nehraješ ještě s nějakými dalšími mody? Třeba Unofficial Fallout 4 Patch?

**Comment by IceWolfCZ** [comment]
Ne, mám tam pouze češtinu

**Comment by IceWolfCZ** [comment]
Odpovídal jsem, ale asi neodeslal. Používám pouze češtinu, žádný jiný mod.

**Comment by pavelhoral** [comment]
Možná teda ještě zkus znovu vytáhnout z elektřiny, jak je napsáno v návodu https://github.com/prekladyher/fallout4-cestina/wiki/Instalace-%C4%8De%C5%A1tiny-na-konzol%C3%ADch

> POZOR, u Xboxu nebude napoprvé čeština fungovat bez vymazání mezipaměti konzole. Toho dosáhnete vypnutím konzole a vytažením z elektřiny alespoň na 2 minuty.

**Comment by IceWolfCZ** [comment]
To jsem už zkoušel. Jednak jen vypojit z elektriky, tak i odinstalovat MOD a vše udělat dle návodu. Instaloval jsem celkem 3x, ale jen u té první to fungovalo 😕
Nemůže být problém někde v nastavení samotného Xboxu?

**Comment by pavelhoral** [comment]
Já bohužel Xbox nemám, tak nemohu ověřit. Uvidíme, zda se mi ozve někdo z Discordu, kdo má Xbox...

Ještě se pro jistotu se zeptám - to, že nefunguje čeština, usuzuješ až z titulků ve hře? Je to tak? Jsi si vědom toho, že menu přeložené není?

**Comment by IceWolfCZ** [comment]
Jj až ve hře. Tipy ve hře, povely pro psa, rozhovory ... Vše v angličtině.

**Comment by IceWolfCZ** [comment]
Tak a jsem úplně v koncích. Že zoufalství jsem hru odinstalovat a znovu nainstaloval. Ve hře nainstaloval mód čeština, mod aktivoval, potvrdil a potvrdil, že se to projeví po restartu, nechal hru restartovat a pak vypnul Xbox na cca 5 minut (z elektriky). A ejhle po češtině ani stopa. Pomoooooc 😕

**Comment by IceWolfCZ** [comment]
Tvl, ne,ne ne. Už to mám, ale ani nevím jak mě to napadlo. Když je u módu napsáno disable, tak je aktivován a když activate tak je vypnut. Já myslel, že tam musí být napsáno activate a ono je to naopak 😁

**Comment by pavelhoral** [comment]
Stane se, no :D. Popravdě mě to napadlo, ale nestihl jsem se zeptat. Tak já tuhle issue zavřu.

![](https://media.giphy.com/media/TJawtKM6OCKkvwCIqX/giphy.gif)

**Comment by pavelhoral** [comment]
Ono je vlastně dobře, že to byla taková maličkost. Popravdě moc netuším, jak bych to jinak řešil.
