### ISSUE TITLE
Fallout 4 VR - Ztraceené ovládací prvky

### ISSUE THREAD

**Issue by VodanCZ** [prekladyher/fallout4-cestina#794]
po překladu Zmizely popisky tlacitek pro jednotlive akce .... uz nekoikrat jsem se ve spechu omylem pokusil zastrelit sveho pejska

**Comment by pavelhoral** [comment]
PC, Xbox, neboo PS4? A nebyl by screenshot?

**Comment by VodanCZ** [comment]
Pardon zapomel jsem napsat platformu je to na PC

**Comment by VodanCZ** [comment]
nevim jak se mvlozit screen ....

**Comment by pavelhoral** [comment]
Dej print screen a normálně CTRL-V pro vložení obrázku (funguje to, když máš kurzor v políčku pro psaní komentáře).

**Comment by VodanCZ** [comment]
![20211008144625_1](https://user-images.githubusercontent.com/91762126/136593664-a562874a-627b-48c0-bd3c-5363b20541a8.jpg)

![20211008144558_1](https://user-images.githubusercontent.com/91762126/136593683-f05e328e-b6ac-434f-a81f-e7d6a0b30f97.jpg)

**Comment by VodanCZ** [comment]
před instalaci překladu bylo u prohledat atd Tlacitk ktere se ma zmacknout ...

**Comment by pavelhoral** [comment]
To hraješ VR verzi? Nebo to je klasická verze? Já tam mám klasicky klávesy.

**Comment by VodanCZ** [comment]
VR

**Comment by pavelhoral** [comment]
Ok... to bude problém s fontem. Kouknu se na to. VR verzi jsme moc neřešili.

**Comment by VodanCZ** [comment]
to by bylo super. Je to lehce nepohodlne :) ja jsem si 4ku koupil jen kvuli VR verzi.

**Comment by pavelhoral** [comment]
Mělo by být opraveno v další verzi.
