### ISSUE TITLE
Crash Game

### ISSUE THREAD

**Issue by Branfaolan** [prekladyher/fallout4-cestina#796]

**Comment by pavelhoral** [comment]
Je velmi nepravděpodobné, že by čeština mohla způsobovat na PC nějaké problémy. Víceméně do hry vůbec nezasahuje a nahrazuje skutečně jen a pouze herní texty. Naopak hra samotná má několik známých problémů, kdy padá.

Pokud podezříváš češtinu, můžeš ji zkusit odinstalovat. Pokud bude hra stále padat, tak je to opravdu spíše něco ve hře.

Já si matně vybavuji, že byl často problém v několika vybraných lokacích - Virgilova jeskyně, budova Greentech Genetics atp. Na to se dají vygooglit nějaké návody, co s tím.
