### ISSUE TITLE
Pocitacovi terminal neukazuje text po update dnes.

### ISSUE THREAD

**Issue by lektorsk** [prekladyher/fallout4-cestina#797]
![Screenshot 2024-04-25 205253](https://github.com/prekladyher/fallout4-cestina/assets/168129272/74e8e6ab-6d73-487d-972c-d95bb917fc98)
![Screenshot 2024-04-25 205253](https://github.com/prekladyher/fallout4-cestina/assets/168129272/c25add62-09d2-4717-aa44-2c93670e70fd)

**Comment by pavelhoral** [comment]
Před pěti minutami jsem vydal novou opravnou verzi :)

**Comment by pavelhoral** [comment]
https://prekladyher.github.io/fallout4-cestina/ (stránku je nutné obnovit - nová verze má číslo 1.1.0)
