### ISSUE TITLE
Chemické laboratoře- výroba

### ISSUE THREAD

**Issue by Jethrot30** [prekladyher/fallout4-cestina#8]
"označené přísady budou mít "ve světě"vedle svého názvu zobrazenou(spíš snad zobrazenu)malou lupu."
Asi jsem natvrdlá,ale moc nerozumím."ve světě"jako přímo ve hře?Na mapě?Nebo jak?...
Ten pojem se objevuje opakovaně v nápovědě.Např vaření,součástky.

**Comment by pavelhoral** [comment]
Přepsal jsem velkou část textů v nápovědě a tutoriálových hláškách. Tam, kde byl *svět*, jsem větu buď přeformuloval tak, aby tam nebylo nic, nebo jsem z toho udělal *herní svět*.
