### ISSUE TITLE
Nečitelný text v terminálech po next gen updatu

### ISSUE THREAD

**Issue by jtregl** [prekladyher/fallout4-cestina#800]
Ahoj,
po posledním next gen updatu na PC se špatně zobrazujou texty v terminálech a při dialozích. Po odinstalování češtiny se vše zobrazuje správně.
![image](https://github.com/prekladyher/fallout4-cestina/assets/77359947/b30e0f7c-1833-4108-b2b6-5aead4581975)
![image](https://github.com/prekladyher/fallout4-cestina/assets/77359947/9d7abf1f-5e4d-4766-916e-96c9fe7d9669)

**Comment by Fluik** [comment]
Ahoj, nainstaluj si nejnovější verzi 1.1.0
