### ISSUE TITLE
Chyba v hackovacím terminálu

### ISSUE THREAD

**Issue by Mefitek** [prekladyher/fallout4-cestina#801]
Jak se vidět ze screenshotu, slova MRKEV i TRHAT mají obě Podobnost 1, přičemž sdílí pouze písmenko R. Slovo TRASA by tudíž mělo mít Podobnost minimálně 1, ale má 0.
Může se jednat o překladovou chybu nebo je to Bethesdovina?

![MRKEV](https://github.com/prekladyher/fallout4-cestina/assets/99727231/6394e301-dc59-4491-8410-3602006cdc31)

**Comment by pavelhoral** [comment]
Takhle to ale nefunguje :). Pokud MRKEV a TRHAT mají jednu shodu, tak to může být vždy jiné písmenko - tzn. vůbec to nemusí (a nejspíš není) písmeno R.

**Comment by Mefitek** [comment]
Aha, mb then

**Comment by pavelhoral** [comment]
Jinak to heslo bylo nejspíš MAMUT:

* s MRKEV sdílí první M 
* s TRHAT sdílí poslední T
* s TRASA nesdílí nic
