### ISSUE TITLE
Úprava postavy - nevejdou se tam názvy

### ISSUE THREAD

**Issue by Radek33** [prekladyher/fallout4-cestina#85]
![uprava postavy1](https://cloud.githubusercontent.com/assets/23244726/20055013/915567fe-a4df-11e6-9334-4f4ee509dacf.jpg)
![uprava postavy2](https://cloud.githubusercontent.com/assets/23244726/20055015/94431c2c-a4df-11e6-8cc2-382214959235.jpg)

Obličejové barvy a Obličejové tetování jsou moc dlouhé.

**Comment by pavelhoral** [comment]
Stále nerozumím Stoupovu komentáři a zmiňované *zradě*, ale *tetování* jsem opravil. Takže zavírám a barvy vyřeším v rámci #11.
